// Code generated by gig/packages/tool. DO NOT EDIT.
package encoding_hex

import (
	encoding_hex "encoding/hex"
	"reflect"

	"gig/importer"
	"gig/value"
)

func init() {
	pkg := importer.RegisterPackage("encoding/hex", "hex")

	// Functions
	pkg.AddFunction("AppendDecode", encoding_hex.AppendDecode, "", direct_AppendDecode)
	pkg.AddFunction("AppendEncode", encoding_hex.AppendEncode, "", direct_AppendEncode)
	pkg.AddFunction("Decode", encoding_hex.Decode, "", direct_Decode)
	pkg.AddFunction("DecodeString", encoding_hex.DecodeString, "", direct_DecodeString)
	pkg.AddFunction("DecodedLen", encoding_hex.DecodedLen, "", direct_DecodedLen)
	pkg.AddFunction("Dump", encoding_hex.Dump, "", direct_Dump)
	pkg.AddFunction("Dumper", encoding_hex.Dumper, "", nil)
	pkg.AddFunction("Encode", encoding_hex.Encode, "", direct_Encode)
	pkg.AddFunction("EncodeToString", encoding_hex.EncodeToString, "", direct_EncodeToString)
	pkg.AddFunction("EncodedLen", encoding_hex.EncodedLen, "", direct_EncodedLen)
	pkg.AddFunction("NewDecoder", encoding_hex.NewDecoder, "", nil)
	pkg.AddFunction("NewEncoder", encoding_hex.NewEncoder, "", nil)

	// Variables
	pkg.AddVariable("ErrLength", &encoding_hex.ErrLength, "")

	// Types
	pkg.AddType("InvalidByteError", reflect.TypeOf((*encoding_hex.InvalidByteError)(nil)).Elem(), "")

}

func direct_AppendDecode(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	a1 := args[1].Interface().([]byte)
	r0, r1 := encoding_hex.AppendDecode(a0, a1)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_AppendEncode(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	a1 := args[1].Interface().([]byte)
	return value.FromInterface(encoding_hex.AppendEncode(a0, a1))
}

func direct_Decode(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	a1 := args[1].Interface().([]byte)
	r0, r1 := encoding_hex.Decode(a0, a1)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_DecodeString(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := encoding_hex.DecodeString(a0)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_DecodedLen(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	return value.MakeInt(int64(encoding_hex.DecodedLen(a0)))
}

func direct_Dump(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	return value.MakeString(string(encoding_hex.Dump(a0)))
}

func direct_Encode(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	a1 := args[1].Interface().([]byte)
	return value.MakeInt(int64(encoding_hex.Encode(a0, a1)))
}

func direct_EncodeToString(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	return value.MakeString(string(encoding_hex.EncodeToString(a0)))
}

func direct_EncodedLen(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	return value.MakeInt(int64(encoding_hex.EncodedLen(a0)))
}
