// Code generated by gig/packages/tool. DO NOT EDIT.
package fmt

import (
	"fmt"
	"reflect"

	"gig/importer"
	"gig/value"
)

func init() {
	pkg := importer.RegisterPackage("fmt", "fmt")

	// Functions
	pkg.AddFunction("Append", fmt.Append, "", direct_Append)
	pkg.AddFunction("Appendf", fmt.Appendf, "", direct_Appendf)
	pkg.AddFunction("Appendln", fmt.Appendln, "", direct_Appendln)
	pkg.AddFunction("Errorf", fmt.Errorf, "", direct_Errorf)
	pkg.AddFunction("FormatString", fmt.FormatString, "", nil)
	pkg.AddFunction("Fprint", fmt.Fprint, "", nil)
	pkg.AddFunction("Fprintf", fmt.Fprintf, "", nil)
	pkg.AddFunction("Fprintln", fmt.Fprintln, "", nil)
	pkg.AddFunction("Fscan", fmt.Fscan, "", nil)
	pkg.AddFunction("Fscanf", fmt.Fscanf, "", nil)
	pkg.AddFunction("Fscanln", fmt.Fscanln, "", nil)
	pkg.AddFunction("Print", fmt.Print, "", direct_Print)
	pkg.AddFunction("Printf", fmt.Printf, "", direct_Printf)
	pkg.AddFunction("Println", fmt.Println, "", direct_Println)
	pkg.AddFunction("Scan", fmt.Scan, "", direct_Scan)
	pkg.AddFunction("Scanf", fmt.Scanf, "", direct_Scanf)
	pkg.AddFunction("Scanln", fmt.Scanln, "", direct_Scanln)
	pkg.AddFunction("Sprint", fmt.Sprint, "", direct_Sprint)
	pkg.AddFunction("Sprintf", fmt.Sprintf, "", direct_Sprintf)
	pkg.AddFunction("Sprintln", fmt.Sprintln, "", direct_Sprintln)
	pkg.AddFunction("Sscan", fmt.Sscan, "", direct_Sscan)
	pkg.AddFunction("Sscanf", fmt.Sscanf, "", direct_Sscanf)
	pkg.AddFunction("Sscanln", fmt.Sscanln, "", direct_Sscanln)

	// Types
	pkg.AddType("Formatter", reflect.TypeOf((*fmt.Formatter)(nil)).Elem(), "")
	pkg.AddType("GoStringer", reflect.TypeOf((*fmt.GoStringer)(nil)).Elem(), "")
	pkg.AddType("ScanState", reflect.TypeOf((*fmt.ScanState)(nil)).Elem(), "")
	pkg.AddType("Scanner", reflect.TypeOf((*fmt.Scanner)(nil)).Elem(), "")
	pkg.AddType("State", reflect.TypeOf((*fmt.State)(nil)).Elem(), "")
	pkg.AddType("Stringer", reflect.TypeOf((*fmt.Stringer)(nil)).Elem(), "")

}

func direct_Append(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	return value.FromInterface(fmt.Append(a0, varArgs...))
}

func direct_Appendf(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	a1 := args[1].String()
	varArgs := make([]interface{}, len(args)-2)
	for i := 2; i < len(args); i++ {
		varArgs[i-2] = args[i].Interface()
	}
	return value.FromInterface(fmt.Appendf(a0, a1, varArgs...))
}

func direct_Appendln(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	return value.FromInterface(fmt.Appendln(a0, varArgs...))
}

func direct_Errorf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	return value.FromInterface(fmt.Errorf(a0, varArgs...))
}

func direct_Print(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	r0, r1 := fmt.Print(varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Printf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	r0, r1 := fmt.Printf(a0, varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Println(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	r0, r1 := fmt.Println(varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Scan(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	r0, r1 := fmt.Scan(varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Scanf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	r0, r1 := fmt.Scanf(a0, varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Scanln(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	r0, r1 := fmt.Scanln(varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Sprint(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	return value.MakeString(string(fmt.Sprint(varArgs...)))
}

func direct_Sprintf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	return value.MakeString(string(fmt.Sprintf(a0, varArgs...)))
}

func direct_Sprintln(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	return value.MakeString(string(fmt.Sprintln(varArgs...)))
}

func direct_Sscan(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	r0, r1 := fmt.Sscan(a0, varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Sscanf(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	varArgs := make([]interface{}, len(args)-2)
	for i := 2; i < len(args); i++ {
		varArgs[i-2] = args[i].Interface()
	}
	r0, r1 := fmt.Sscanf(a0, a1, varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Sscanln(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	r0, r1 := fmt.Sscanln(a0, varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}
