// Package pkgs contains the list of packages to import for gig.
package pkgs

// ImportPkgs lists the import paths of packages to generate registration code for.
// Standard library packages use their standard import path.
// Third-party packages use their full module path.
var ImportPkgs = []string{
	"bytes",
	"cmp",
	"container/heap",
	"container/list",
	"container/ring",
	"context",
	"crypto/md5",
	"crypto/sha256",
	"crypto/hmac",
	"encoding/base64",
	"encoding/csv",
	"encoding/hex",
	"encoding/json",
	"encoding/xml",
	"errors",
	"fmt",
	"html",
	"html/template",
	"io",
	"log",
	"maps",
	"math",
	"math/rand",
	"net/http",
	"net/url",
	"os",
	"path",
	"path/filepath",
	"regexp",
	"slices",
	"sort",
	"strconv",
	"strings",
	"sync",
	"sync/atomic",
	"text/template",
	"time",
	"unicode",
	"unicode/utf8",
	"unicode/utf16",
}
