// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	archive_zip "archive/zip"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("archive/zip", "zip")

	// Functions
	pkg.AddFunction("FileInfoHeader", archive_zip.FileInfoHeader, "")
	pkg.AddFunction("NewReader", archive_zip.NewReader, "")
	pkg.AddFunction("NewWriter", archive_zip.NewWriter, "")
	pkg.AddFunction("OpenReader", archive_zip.OpenReader, "")
	pkg.AddFunction("RegisterCompressor", archive_zip.RegisterCompressor, "")
	pkg.AddFunction("RegisterDecompressor", archive_zip.RegisterDecompressor, "")

	// Constants
	pkg.AddConstant("Deflate", archive_zip.Deflate, "")
	pkg.AddConstant("Store", archive_zip.Store, "")

	// Variables
	pkg.AddVariable("ErrAlgorithm", &archive_zip.ErrAlgorithm, "")
	pkg.AddVariable("ErrChecksum", &archive_zip.ErrChecksum, "")
	pkg.AddVariable("ErrFormat", &archive_zip.ErrFormat, "")
	pkg.AddVariable("ErrInsecurePath", &archive_zip.ErrInsecurePath, "")

	// Types
	pkg.AddType("Compressor", reflect.TypeOf((*archive_zip.Compressor)(nil)).Elem(), "")
	pkg.AddType("Decompressor", reflect.TypeOf((*archive_zip.Decompressor)(nil)).Elem(), "")
	pkg.AddType("File", reflect.TypeOf(archive_zip.File{}), "")
	pkg.AddType("FileHeader", reflect.TypeOf(archive_zip.FileHeader{}), "")
	pkg.AddType("ReadCloser", reflect.TypeOf(archive_zip.ReadCloser{}), "")
	pkg.AddType("Reader", reflect.TypeOf(archive_zip.Reader{}), "")
	pkg.AddType("Writer", reflect.TypeOf(archive_zip.Writer{}), "")

}
