// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"bufio"
	io "io"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("bufio", "bufio")

	// Functions
	pkg.AddFunction("NewReadWriter", bufio.NewReadWriter, "", direct_bufio_NewReadWriter)
	pkg.AddFunction("NewReader", bufio.NewReader, "", direct_bufio_NewReader)
	pkg.AddFunction("NewReaderSize", bufio.NewReaderSize, "", direct_bufio_NewReaderSize)
	pkg.AddFunction("NewScanner", bufio.NewScanner, "", direct_bufio_NewScanner)
	pkg.AddFunction("NewWriter", bufio.NewWriter, "", direct_bufio_NewWriter)
	pkg.AddFunction("NewWriterSize", bufio.NewWriterSize, "", direct_bufio_NewWriterSize)
	pkg.AddFunction("ScanBytes", bufio.ScanBytes, "", direct_bufio_ScanBytes)
	pkg.AddFunction("ScanLines", bufio.ScanLines, "", direct_bufio_ScanLines)
	pkg.AddFunction("ScanRunes", bufio.ScanRunes, "", direct_bufio_ScanRunes)
	pkg.AddFunction("ScanWords", bufio.ScanWords, "", direct_bufio_ScanWords)

	// Constants
	pkg.AddConstant("MaxScanTokenSize", bufio.MaxScanTokenSize, "")

	// Variables
	pkg.AddVariable("ErrAdvanceTooFar", &bufio.ErrAdvanceTooFar, "")
	pkg.AddVariable("ErrBadReadCount", &bufio.ErrBadReadCount, "")
	pkg.AddVariable("ErrBufferFull", &bufio.ErrBufferFull, "")
	pkg.AddVariable("ErrFinalToken", &bufio.ErrFinalToken, "")
	pkg.AddVariable("ErrInvalidUnreadByte", &bufio.ErrInvalidUnreadByte, "")
	pkg.AddVariable("ErrInvalidUnreadRune", &bufio.ErrInvalidUnreadRune, "")
	pkg.AddVariable("ErrNegativeAdvance", &bufio.ErrNegativeAdvance, "")
	pkg.AddVariable("ErrNegativeCount", &bufio.ErrNegativeCount, "")
	pkg.AddVariable("ErrTooLong", &bufio.ErrTooLong, "")

	// Types
	pkg.AddType("ReadWriter", reflect.TypeOf(bufio.ReadWriter{}), "")
	pkg.AddType("Reader", reflect.TypeOf(bufio.Reader{}), "")
	pkg.AddType("Scanner", reflect.TypeOf(bufio.Scanner{}), "")
	pkg.AddType("SplitFunc", reflect.TypeOf((*bufio.SplitFunc)(nil)).Elem(), "")
	pkg.AddType("Writer", reflect.TypeOf(bufio.Writer{}), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("Reader", "Buffered", direct_method_bufio_Reader_Buffered)
	pkg.AddMethodDirectCall("Reader", "Discard", direct_method_bufio_Reader_Discard)
	pkg.AddMethodDirectCall("Reader", "Peek", direct_method_bufio_Reader_Peek)
	pkg.AddMethodDirectCall("Reader", "Read", direct_method_bufio_Reader_Read)
	pkg.AddMethodDirectCall("Reader", "ReadByte", direct_method_bufio_Reader_ReadByte)
	pkg.AddMethodDirectCall("Reader", "ReadBytes", direct_method_bufio_Reader_ReadBytes)
	pkg.AddMethodDirectCall("Reader", "ReadLine", direct_method_bufio_Reader_ReadLine)
	pkg.AddMethodDirectCall("Reader", "ReadRune", direct_method_bufio_Reader_ReadRune)
	pkg.AddMethodDirectCall("Reader", "ReadSlice", direct_method_bufio_Reader_ReadSlice)
	pkg.AddMethodDirectCall("Reader", "ReadString", direct_method_bufio_Reader_ReadString)
	pkg.AddMethodDirectCall("Reader", "Reset", direct_method_bufio_Reader_Reset)
	pkg.AddMethodDirectCall("Reader", "Size", direct_method_bufio_Reader_Size)
	pkg.AddMethodDirectCall("Reader", "UnreadByte", direct_method_bufio_Reader_UnreadByte)
	pkg.AddMethodDirectCall("Reader", "UnreadRune", direct_method_bufio_Reader_UnreadRune)
	pkg.AddMethodDirectCall("Reader", "WriteTo", direct_method_bufio_Reader_WriteTo)
	pkg.AddMethodDirectCall("Scanner", "Buffer", direct_method_bufio_Scanner_Buffer)
	pkg.AddMethodDirectCall("Scanner", "Bytes", direct_method_bufio_Scanner_Bytes)
	pkg.AddMethodDirectCall("Scanner", "Err", direct_method_bufio_Scanner_Err)
	pkg.AddMethodDirectCall("Scanner", "Scan", direct_method_bufio_Scanner_Scan)
	pkg.AddMethodDirectCall("Scanner", "Split", direct_method_bufio_Scanner_Split)
	pkg.AddMethodDirectCall("Scanner", "Text", direct_method_bufio_Scanner_Text)
	pkg.AddMethodDirectCall("Writer", "Available", direct_method_bufio_Writer_Available)
	pkg.AddMethodDirectCall("Writer", "AvailableBuffer", direct_method_bufio_Writer_AvailableBuffer)
	pkg.AddMethodDirectCall("Writer", "Buffered", direct_method_bufio_Writer_Buffered)
	pkg.AddMethodDirectCall("Writer", "Flush", direct_method_bufio_Writer_Flush)
	pkg.AddMethodDirectCall("Writer", "ReadFrom", direct_method_bufio_Writer_ReadFrom)
	pkg.AddMethodDirectCall("Writer", "Reset", direct_method_bufio_Writer_Reset)
	pkg.AddMethodDirectCall("Writer", "Size", direct_method_bufio_Writer_Size)
	pkg.AddMethodDirectCall("Writer", "Write", direct_method_bufio_Writer_Write)
	pkg.AddMethodDirectCall("Writer", "WriteByte", direct_method_bufio_Writer_WriteByte)
	pkg.AddMethodDirectCall("Writer", "WriteRune", direct_method_bufio_Writer_WriteRune)
	pkg.AddMethodDirectCall("Writer", "WriteString", direct_method_bufio_Writer_WriteString)

}

func direct_bufio_NewReadWriter(args []value.Value) value.Value {
	a0 := args[0].Interface().(*bufio.Reader)
	a1 := args[1].Interface().(*bufio.Writer)
	return value.FromInterface(bufio.NewReadWriter(a0, a1))
}

func direct_bufio_NewReader(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Reader)
	return value.FromInterface(bufio.NewReader(a0))
}

func direct_bufio_NewReaderSize(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Reader)
	a1 := int(args[1].Int())
	return value.FromInterface(bufio.NewReaderSize(a0, a1))
}

func direct_bufio_NewScanner(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Reader)
	return value.FromInterface(bufio.NewScanner(a0))
}

func direct_bufio_NewWriter(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Writer)
	return value.FromInterface(bufio.NewWriter(a0))
}

func direct_bufio_NewWriterSize(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Writer)
	a1 := int(args[1].Int())
	return value.FromInterface(bufio.NewWriterSize(a0, a1))
}

func direct_bufio_ScanBytes(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Bool()
	r0, r1, r2 := bufio.ScanBytes(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.MakeBytes([]byte(r1)), value.FromInterface(r2)})
}

func direct_bufio_ScanLines(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Bool()
	r0, r1, r2 := bufio.ScanLines(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.MakeBytes([]byte(r1)), value.FromInterface(r2)})
}

func direct_bufio_ScanRunes(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Bool()
	r0, r1, r2 := bufio.ScanRunes(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.MakeBytes([]byte(r1)), value.FromInterface(r2)})
}

func direct_bufio_ScanWords(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Bool()
	r0, r1, r2 := bufio.ScanWords(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.MakeBytes([]byte(r1)), value.FromInterface(r2)})
}

func direct_method_bufio_Reader_Buffered(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	return value.MakeInt(int64(recv.Buffered()))
}

func direct_method_bufio_Reader_Discard(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	a0 := int(args[1].Int())
	r0, r1 := recv.Discard(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Reader_Peek(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	a0 := int(args[1].Int())
	r0, r1 := recv.Peek(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Reader_Read(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := recv.Read(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Reader_ReadByte(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	r0, r1 := recv.ReadByte()
	return value.MakeValueSlice([]value.Value{value.MakeUint(uint64(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Reader_ReadBytes(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	a0 := byte(args[1].Uint())
	r0, r1 := recv.ReadBytes(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Reader_ReadLine(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	r0, r1, r2 := recv.ReadLine()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.MakeBool(r1), value.FromInterface(r2)})
}

func direct_method_bufio_Reader_ReadRune(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	r0, r1, r2 := recv.ReadRune()
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.MakeInt(int64(r1)), value.FromInterface(r2)})
}

func direct_method_bufio_Reader_ReadSlice(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	a0 := byte(args[1].Uint())
	r0, r1 := recv.ReadSlice(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Reader_ReadString(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	a0 := byte(args[1].Uint())
	r0, r1 := recv.ReadString(a0)
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Reader_Reset(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	a0 := args[1].Interface().(io.Reader)
	recv.Reset(a0)
	return value.MakeNil()
}

func direct_method_bufio_Reader_Size(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	return value.MakeInt(int64(recv.Size()))
}

func direct_method_bufio_Reader_UnreadByte(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	return value.FromInterface(recv.UnreadByte())
}

func direct_method_bufio_Reader_UnreadRune(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	return value.FromInterface(recv.UnreadRune())
}

func direct_method_bufio_Reader_WriteTo(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Reader)
	a0 := args[1].Interface().(io.Writer)
	r0, r1 := recv.WriteTo(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt64(r0), value.FromInterface(r1)})
}

func direct_method_bufio_Scanner_Buffer(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Scanner)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := int(args[2].Int())
	recv.Buffer(a0, a1)
	return value.MakeNil()
}

func direct_method_bufio_Scanner_Bytes(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Scanner)
	return value.MakeBytes([]byte(recv.Bytes()))
}

func direct_method_bufio_Scanner_Err(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Scanner)
	return value.FromInterface(recv.Err())
}

func direct_method_bufio_Scanner_Scan(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Scanner)
	return value.MakeBool(recv.Scan())
}

func direct_method_bufio_Scanner_Split(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Scanner)
	a0 := args[1].Interface().(bufio.SplitFunc)
	recv.Split(a0)
	return value.MakeNil()
}

func direct_method_bufio_Scanner_Text(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Scanner)
	return value.MakeString(string(recv.Text()))
}

func direct_method_bufio_Writer_Available(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	return value.MakeInt(int64(recv.Available()))
}

func direct_method_bufio_Writer_AvailableBuffer(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	return value.MakeBytes([]byte(recv.AvailableBuffer()))
}

func direct_method_bufio_Writer_Buffered(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	return value.MakeInt(int64(recv.Buffered()))
}

func direct_method_bufio_Writer_Flush(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	return value.FromInterface(recv.Flush())
}

func direct_method_bufio_Writer_ReadFrom(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	a0 := args[1].Interface().(io.Reader)
	r0, r1 := recv.ReadFrom(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt64(r0), value.FromInterface(r1)})
}

func direct_method_bufio_Writer_Reset(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	a0 := args[1].Interface().(io.Writer)
	recv.Reset(a0)
	return value.MakeNil()
}

func direct_method_bufio_Writer_Size(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	return value.MakeInt(int64(recv.Size()))
}

func direct_method_bufio_Writer_Write(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := recv.Write(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Writer_WriteByte(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	a0 := byte(args[1].Uint())
	return value.FromInterface(recv.WriteByte(a0))
}

func direct_method_bufio_Writer_WriteRune(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	a0 := int32(args[1].Int())
	r0, r1 := recv.WriteRune(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_method_bufio_Writer_WriteString(args []value.Value) value.Value {
	recv := args[0].Interface().(*bufio.Writer)
	a0 := args[1].String()
	r0, r1 := recv.WriteString(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}
