// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	compress_gzip "compress/gzip"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("compress/gzip", "gzip")

	// Functions
	pkg.AddFunction("NewReader", compress_gzip.NewReader, "")
	pkg.AddFunction("NewWriter", compress_gzip.NewWriter, "")
	pkg.AddFunction("NewWriterLevel", compress_gzip.NewWriterLevel, "")

	// Constants
	pkg.AddConstant("BestCompression", compress_gzip.BestCompression, "")
	pkg.AddConstant("BestSpeed", compress_gzip.BestSpeed, "")
	pkg.AddConstant("DefaultCompression", compress_gzip.DefaultCompression, "")
	pkg.AddConstant("HuffmanOnly", compress_gzip.HuffmanOnly, "")
	pkg.AddConstant("NoCompression", compress_gzip.NoCompression, "")

	// Variables
	pkg.AddVariable("ErrChecksum", &compress_gzip.ErrChecksum, "")
	pkg.AddVariable("ErrHeader", &compress_gzip.ErrHeader, "")

	// Types
	pkg.AddType("Header", reflect.TypeOf(compress_gzip.Header{}), "")
	pkg.AddType("Reader", reflect.TypeOf(compress_gzip.Reader{}), "")
	pkg.AddType("Writer", reflect.TypeOf(compress_gzip.Writer{}), "")

}
