// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	compress_flate "compress/flate"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("compress/flate", "flate")

	// Functions
	pkg.AddFunction("NewReader", compress_flate.NewReader, "")
	pkg.AddFunction("NewReaderDict", compress_flate.NewReaderDict, "")
	pkg.AddFunction("NewWriter", compress_flate.NewWriter, "")
	pkg.AddFunction("NewWriterDict", compress_flate.NewWriterDict, "")

	// Constants
	pkg.AddConstant("BestCompression", compress_flate.BestCompression, "")
	pkg.AddConstant("BestSpeed", compress_flate.BestSpeed, "")
	pkg.AddConstant("DefaultCompression", compress_flate.DefaultCompression, "")
	pkg.AddConstant("HuffmanOnly", compress_flate.HuffmanOnly, "")
	pkg.AddConstant("NoCompression", compress_flate.NoCompression, "")

	// Types
	pkg.AddType("CorruptInputError", reflect.TypeOf((*compress_flate.CorruptInputError)(nil)).Elem(), "")
	pkg.AddType("InternalError", reflect.TypeOf((*compress_flate.InternalError)(nil)).Elem(), "")
	pkg.AddType("ReadError", reflect.TypeOf(compress_flate.ReadError{}), "")
	pkg.AddType("Reader", reflect.TypeOf((*compress_flate.Reader)(nil)).Elem(), "")
	pkg.AddType("Resetter", reflect.TypeOf((*compress_flate.Resetter)(nil)).Elem(), "")
	pkg.AddType("WriteError", reflect.TypeOf(compress_flate.WriteError{}), "")
	pkg.AddType("Writer", reflect.TypeOf(compress_flate.Writer{}), "")

}
