// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	compress_bzip2 "compress/bzip2"
	io "io"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("compress/bzip2", "bzip2")

	// Functions
	pkg.AddFunction("NewReader", compress_bzip2.NewReader, "", direct_compress_bzip2_NewReader)

	// Types
	pkg.AddType("StructuralError", reflect.TypeOf((*compress_bzip2.StructuralError)(nil)).Elem(), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("StructuralError", "Error", direct_method_compress_bzip2_StructuralError_Error)

}

func direct_compress_bzip2_NewReader(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Reader)
	return value.FromInterface(compress_bzip2.NewReader(a0))
}

func direct_method_compress_bzip2_StructuralError_Error(args []value.Value) value.Value {
	recv := compress_bzip2.StructuralError(args[0].String())
	return value.MakeString(string(recv.Error()))
}
