// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	compress_gzip "compress/gzip"
	"fmt"
	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
	"io"
	"reflect"
)

func init() {
	pkg := importer.RegisterPackage("compress/gzip", "gzip")

	// Functions
	pkg.AddFunction("NewReader", compress_gzip.NewReader, "", directCallCompressGzipNewReader)
	pkg.AddFunction("NewWriter", compress_gzip.NewWriter, "", directCallCompressGzipNewWriter)
	pkg.AddFunction("NewWriterLevel", compress_gzip.NewWriterLevel, "", directCallCompressGzipNewWriterLevel)

	// Constants
	pkg.AddConstant("BestCompression", compress_gzip.BestCompression, "")
	pkg.AddConstant("BestSpeed", compress_gzip.BestSpeed, "")
	pkg.AddConstant("DefaultCompression", compress_gzip.DefaultCompression, "")
	pkg.AddConstant("HuffmanOnly", compress_gzip.HuffmanOnly, "")
	pkg.AddConstant("NoCompression", compress_gzip.NoCompression, "")

	// Variables
	pkg.AddVariable("ErrChecksum", &compress_gzip.ErrChecksum, "")
	pkg.AddVariable("ErrHeader", &compress_gzip.ErrHeader, "")

	// Types
	pkg.AddType("Header", reflect.TypeOf(compress_gzip.Header{}), "")
	pkg.AddType("Reader", reflect.TypeOf(compress_gzip.Reader{}), "")
	pkg.AddType("Writer", reflect.TypeOf(compress_gzip.Writer{}), "")

}

func directArgCompressGzip[T any](v value.Value) (T, error) {
	var zero T
	rt := reflect.TypeFor[T]()
	rv, err := value.DefaultConverter().ToReflect(v, rt)
	if err != nil {
		return zero, err
	}
	if !rv.IsValid() {
		return zero, nil
	}
	if rv.Type().AssignableTo(rt) {
		return rv.Interface().(T), nil
	}
	if rv.Type().ConvertibleTo(rt) {
		return rv.Convert(rt).Interface().(T), nil
	}
	return zero, fmt.Errorf("cannot convert %s to %s", rv.Type(), rt)
}

func directVariadicArgsCompressGzip[T any](args []value.Value) ([]T, error) {
	if len(args) == 1 {
		if packed, err := directArgCompressGzip[[]T](args[0]); err == nil {
			return packed, nil
		}
		if rv, ok := args[0].Reflect(); ok && rv.IsValid() {
			for rv.Kind() == reflect.Interface && !rv.IsNil() {
				rv = rv.Elem()
			}
			if rv.Kind() == reflect.Slice {
				out := make([]T, rv.Len())
				conv := value.DefaultConverter()
				for i := 0; i < rv.Len(); i++ {
					vv, err := conv.FromReflect(rv.Index(i))
					if err != nil {
						return nil, fmt.Errorf("variadic explode %d: %w", i, err)
					}
					out[i], err = directArgCompressGzip[T](vv)
					if err != nil {
						return nil, fmt.Errorf("variadic arg %d: %w", i, err)
					}
				}
				return out, nil
			}
		}
	}
	out := make([]T, len(args))
	for i, arg := range args {
		v, err := directArgCompressGzip[T](arg)
		if err != nil {
			return nil, fmt.Errorf("variadic arg %d: %w", i, err)
		}
		out[i] = v
	}
	return out, nil
}

func directResultsCompressGzip(vals ...any) ([]value.Value, error) {
	out := make([]value.Value, len(vals))
	conv := value.DefaultConverter()
	for i, v := range vals {
		vv, err := conv.FromAny(v)
		if err != nil {
			return nil, fmt.Errorf("result %d: %w", i, err)
		}
		out[i] = vv
	}
	return out, nil
}

func directCallCompressGzipNewReader(args []value.Value) ([]value.Value, error) {
	if len(args) != 1 {
		return nil, fmt.Errorf("arg count %d != 1", len(args))
	}
	a0, err := directArgCompressGzip[io.Reader](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	r0, r1 := compress_gzip.NewReader(a0)
	return directResultsCompressGzip(r0, r1)
}

func directCallCompressGzipNewWriter(args []value.Value) ([]value.Value, error) {
	if len(args) != 1 {
		return nil, fmt.Errorf("arg count %d != 1", len(args))
	}
	a0, err := directArgCompressGzip[io.Writer](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	r0 := compress_gzip.NewWriter(a0)
	return directResultsCompressGzip(r0)
}

func directCallCompressGzipNewWriterLevel(args []value.Value) ([]value.Value, error) {
	if len(args) != 2 {
		return nil, fmt.Errorf("arg count %d != 2", len(args))
	}
	a0, err := directArgCompressGzip[io.Writer](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	a1, err := directArgCompressGzip[int](args[1])
	if err != nil {
		return nil, fmt.Errorf("arg 1: %w", err)
	}
	r0, r1 := compress_gzip.NewWriterLevel(a0, a1)
	return directResultsCompressGzip(r0, r1)
}
