// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	container_heap "container/heap"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("container/heap", "heap")

	// Functions
	pkg.AddFunction("Fix", container_heap.Fix, "", direct_container_heap_Fix)
	pkg.AddFunction("Init", container_heap.Init, "", direct_container_heap_Init)
	pkg.AddFunction("Pop", container_heap.Pop, "", direct_container_heap_Pop)
	pkg.AddFunction("Push", container_heap.Push, "", direct_container_heap_Push)
	pkg.AddFunction("Remove", container_heap.Remove, "", direct_container_heap_Remove)

	// Types
	pkg.AddType("Interface", reflect.TypeOf((*container_heap.Interface)(nil)).Elem(), "")

}

func direct_container_heap_Fix(args []value.Value) value.Value {
	a0 := args[0].Interface().(container_heap.Interface)
	a1 := int(args[1].Int())
	container_heap.Fix(a0, a1)
	return value.MakeNil()
}

func direct_container_heap_Init(args []value.Value) value.Value {
	a0 := args[0].Interface().(container_heap.Interface)
	container_heap.Init(a0)
	return value.MakeNil()
}

func direct_container_heap_Pop(args []value.Value) value.Value {
	a0 := args[0].Interface().(container_heap.Interface)
	return value.FromInterface(container_heap.Pop(a0))
}

func direct_container_heap_Push(args []value.Value) value.Value {
	a0 := args[0].Interface().(container_heap.Interface)
	a1 := args[1].Interface()
	container_heap.Push(a0, a1)
	return value.MakeNil()
}

func direct_container_heap_Remove(args []value.Value) value.Value {
	a0 := args[0].Interface().(container_heap.Interface)
	a1 := int(args[1].Int())
	return value.FromInterface(container_heap.Remove(a0, a1))
}
