// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	crypto_cipher "crypto/cipher"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("crypto/cipher", "cipher")

	// Functions
	pkg.AddFunction("NewCBCDecrypter", crypto_cipher.NewCBCDecrypter, "")
	pkg.AddFunction("NewCBCEncrypter", crypto_cipher.NewCBCEncrypter, "")
	pkg.AddFunction("NewCFBDecrypter", crypto_cipher.NewCFBDecrypter, "")
	pkg.AddFunction("NewCFBEncrypter", crypto_cipher.NewCFBEncrypter, "")
	pkg.AddFunction("NewCTR", crypto_cipher.NewCTR, "")
	pkg.AddFunction("NewGCM", crypto_cipher.NewGCM, "")
	pkg.AddFunction("NewGCMWithNonceSize", crypto_cipher.NewGCMWithNonceSize, "")
	pkg.AddFunction("NewGCMWithTagSize", crypto_cipher.NewGCMWithTagSize, "")
	pkg.AddFunction("NewOFB", crypto_cipher.NewOFB, "")

	// Types
	pkg.AddType("AEAD", reflect.TypeOf((*crypto_cipher.AEAD)(nil)).Elem(), "")
	pkg.AddType("Block", reflect.TypeOf((*crypto_cipher.Block)(nil)).Elem(), "")
	pkg.AddType("BlockMode", reflect.TypeOf((*crypto_cipher.BlockMode)(nil)).Elem(), "")
	pkg.AddType("Stream", reflect.TypeOf((*crypto_cipher.Stream)(nil)).Elem(), "")
	pkg.AddType("StreamReader", reflect.TypeOf(crypto_cipher.StreamReader{}), "")
	pkg.AddType("StreamWriter", reflect.TypeOf(crypto_cipher.StreamWriter{}), "")

}
