// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	crypto_hmac "crypto/hmac"
	"fmt"
	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
	"hash"
	"reflect"
)

func init() {
	pkg := importer.RegisterPackage("crypto/hmac", "hmac")

	// Functions
	pkg.AddFunction("Equal", crypto_hmac.Equal, "", directCallCryptoHmacEqual)
	pkg.AddFunction("New", crypto_hmac.New, "", directCallCryptoHmacNew)

}

func directArgCryptoHmac[T any](v value.Value) (T, error) {
	var zero T
	rt := reflect.TypeFor[T]()
	rv, err := value.DefaultConverter().ToReflect(v, rt)
	if err != nil {
		return zero, err
	}
	if !rv.IsValid() {
		return zero, nil
	}
	if rv.Type().AssignableTo(rt) {
		return rv.Interface().(T), nil
	}
	if rv.Type().ConvertibleTo(rt) {
		return rv.Convert(rt).Interface().(T), nil
	}
	return zero, fmt.Errorf("cannot convert %s to %s", rv.Type(), rt)
}

func directVariadicArgsCryptoHmac[T any](args []value.Value) ([]T, error) {
	if len(args) == 1 {
		if packed, err := directArgCryptoHmac[[]T](args[0]); err == nil {
			return packed, nil
		}
		if rv, ok := args[0].Reflect(); ok && rv.IsValid() {
			for rv.Kind() == reflect.Interface && !rv.IsNil() {
				rv = rv.Elem()
			}
			if rv.Kind() == reflect.Slice {
				out := make([]T, rv.Len())
				conv := value.DefaultConverter()
				for i := 0; i < rv.Len(); i++ {
					vv, err := conv.FromReflect(rv.Index(i))
					if err != nil {
						return nil, fmt.Errorf("variadic explode %d: %w", i, err)
					}
					out[i], err = directArgCryptoHmac[T](vv)
					if err != nil {
						return nil, fmt.Errorf("variadic arg %d: %w", i, err)
					}
				}
				return out, nil
			}
		}
	}
	out := make([]T, len(args))
	for i, arg := range args {
		v, err := directArgCryptoHmac[T](arg)
		if err != nil {
			return nil, fmt.Errorf("variadic arg %d: %w", i, err)
		}
		out[i] = v
	}
	return out, nil
}

func directResultsCryptoHmac(vals ...any) ([]value.Value, error) {
	out := make([]value.Value, len(vals))
	conv := value.DefaultConverter()
	for i, v := range vals {
		vv, err := conv.FromAny(v)
		if err != nil {
			return nil, fmt.Errorf("result %d: %w", i, err)
		}
		out[i] = vv
	}
	return out, nil
}

func directCallCryptoHmacEqual(args []value.Value) ([]value.Value, error) {
	if len(args) != 2 {
		return nil, fmt.Errorf("arg count %d != 2", len(args))
	}
	a0, err := directArgCryptoHmac[[]byte](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	a1, err := directArgCryptoHmac[[]byte](args[1])
	if err != nil {
		return nil, fmt.Errorf("arg 1: %w", err)
	}
	r0 := crypto_hmac.Equal(a0, a1)
	return directResultsCryptoHmac(r0)
}

func directCallCryptoHmacNew(args []value.Value) ([]value.Value, error) {
	if len(args) != 2 {
		return nil, fmt.Errorf("arg count %d != 2", len(args))
	}
	a0, err := directArgCryptoHmac[func() hash.Hash](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	a1, err := directArgCryptoHmac[[]byte](args[1])
	if err != nil {
		return nil, fmt.Errorf("arg 1: %w", err)
	}
	r0 := crypto_hmac.New(a0, a1)
	return directResultsCryptoHmac(r0)
}
