// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	crypto_subtle "crypto/subtle"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("crypto/subtle", "subtle")

	// Functions
	pkg.AddFunction("ConstantTimeByteEq", crypto_subtle.ConstantTimeByteEq, "", direct_crypto_subtle_ConstantTimeByteEq)
	pkg.AddFunction("ConstantTimeCompare", crypto_subtle.ConstantTimeCompare, "", direct_crypto_subtle_ConstantTimeCompare)
	pkg.AddFunction("ConstantTimeCopy", crypto_subtle.ConstantTimeCopy, "", direct_crypto_subtle_ConstantTimeCopy)
	pkg.AddFunction("ConstantTimeEq", crypto_subtle.ConstantTimeEq, "", direct_crypto_subtle_ConstantTimeEq)
	pkg.AddFunction("ConstantTimeLessOrEq", crypto_subtle.ConstantTimeLessOrEq, "", direct_crypto_subtle_ConstantTimeLessOrEq)
	pkg.AddFunction("ConstantTimeSelect", crypto_subtle.ConstantTimeSelect, "", direct_crypto_subtle_ConstantTimeSelect)
	pkg.AddFunction("XORBytes", crypto_subtle.XORBytes, "", direct_crypto_subtle_XORBytes)

}

func direct_crypto_subtle_ConstantTimeByteEq(args []value.Value) value.Value {
	a0 := byte(args[0].Uint())
	a1 := byte(args[1].Uint())
	return value.MakeInt(int64(crypto_subtle.ConstantTimeByteEq(a0, a1)))
}

func direct_crypto_subtle_ConstantTimeCompare(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.MakeInt(int64(crypto_subtle.ConstantTimeCompare(a0, a1)))
}

func direct_crypto_subtle_ConstantTimeCopy(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	a1 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a2 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	crypto_subtle.ConstantTimeCopy(a0, a1, a2)
	return value.MakeNil()
}

func direct_crypto_subtle_ConstantTimeEq(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	a1 := int32(args[1].Int())
	return value.MakeInt(int64(crypto_subtle.ConstantTimeEq(a0, a1)))
}

func direct_crypto_subtle_ConstantTimeLessOrEq(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	a1 := int(args[1].Int())
	return value.MakeInt(int64(crypto_subtle.ConstantTimeLessOrEq(a0, a1)))
}

func direct_crypto_subtle_ConstantTimeSelect(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	a1 := int(args[1].Int())
	a2 := int(args[2].Int())
	return value.MakeInt(int64(crypto_subtle.ConstantTimeSelect(a0, a1, a2)))
}

func direct_crypto_subtle_XORBytes(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a2 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.MakeInt(int64(crypto_subtle.XORBytes(a0, a1, a2)))
}
