// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	crypto_rc4 "crypto/rc4"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("crypto/rc4", "rc4")

	// Functions
	pkg.AddFunction("NewCipher", crypto_rc4.NewCipher, "", direct_crypto_rc4_NewCipher)

	// Types
	pkg.AddType("Cipher", reflect.TypeOf(crypto_rc4.Cipher{}), "")
	pkg.AddType("KeySizeError", reflect.TypeOf((*crypto_rc4.KeySizeError)(nil)).Elem(), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("Cipher", "Reset", direct_method_crypto_rc4_Cipher_Reset)
	pkg.AddMethodDirectCall("Cipher", "XORKeyStream", direct_method_crypto_rc4_Cipher_XORKeyStream)
	pkg.AddMethodDirectCall("KeySizeError", "Error", direct_method_crypto_rc4_KeySizeError_Error)

}

func direct_crypto_rc4_NewCipher(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := crypto_rc4.NewCipher(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_crypto_rc4_Cipher_Reset(args []value.Value) value.Value {
	recv := args[0].Interface().(*crypto_rc4.Cipher)
	recv.Reset()
	return value.MakeNil()
}

func direct_method_crypto_rc4_Cipher_XORKeyStream(args []value.Value) value.Value {
	recv := args[0].Interface().(*crypto_rc4.Cipher)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	recv.XORKeyStream(a0, a1)
	return value.MakeNil()
}

func direct_method_crypto_rc4_KeySizeError_Error(args []value.Value) value.Value {
	recv := crypto_rc4.KeySizeError(int(args[0].Int()))
	return value.MakeString(string(recv.Error()))
}
