// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	encoding_binary "encoding/binary"
	io "io"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/external"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("encoding/binary", "binary")

	// Functions
	pkg.AddFunction("Append", encoding_binary.Append, "", direct_encoding_binary_Append)
	pkg.AddFunction("AppendUvarint", encoding_binary.AppendUvarint, "", direct_encoding_binary_AppendUvarint)
	pkg.AddFunction("AppendVarint", encoding_binary.AppendVarint, "", direct_encoding_binary_AppendVarint)
	pkg.AddFunction("Decode", encoding_binary.Decode, "", direct_encoding_binary_Decode)
	pkg.AddFunction("Encode", encoding_binary.Encode, "", direct_encoding_binary_Encode)
	pkg.AddFunction("PutUvarint", encoding_binary.PutUvarint, "", direct_encoding_binary_PutUvarint)
	pkg.AddFunction("PutVarint", encoding_binary.PutVarint, "", direct_encoding_binary_PutVarint)
	pkg.AddFunction("Read", encoding_binary.Read, "", direct_encoding_binary_Read)
	pkg.AddFunction("ReadUvarint", encoding_binary.ReadUvarint, "", direct_encoding_binary_ReadUvarint)
	pkg.AddFunction("ReadVarint", encoding_binary.ReadVarint, "", direct_encoding_binary_ReadVarint)
	pkg.AddFunction("Size", encoding_binary.Size, "", direct_encoding_binary_Size)
	pkg.AddFunction("Uvarint", encoding_binary.Uvarint, "", direct_encoding_binary_Uvarint)
	pkg.AddFunction("Varint", encoding_binary.Varint, "", direct_encoding_binary_Varint)
	pkg.AddFunction("Write", encoding_binary.Write, "", direct_encoding_binary_Write)

	// Constants
	pkg.AddConstant("MaxVarintLen16", encoding_binary.MaxVarintLen16, "")
	pkg.AddConstant("MaxVarintLen32", encoding_binary.MaxVarintLen32, "")
	pkg.AddConstant("MaxVarintLen64", encoding_binary.MaxVarintLen64, "")

	// Variables
	pkg.AddVariable("BigEndian", &encoding_binary.BigEndian, "")
	pkg.AddVariable("LittleEndian", &encoding_binary.LittleEndian, "")
	pkg.AddVariable("NativeEndian", &encoding_binary.NativeEndian, "")

	// Types
	pkg.AddType("AppendByteOrder", reflect.TypeOf((*encoding_binary.AppendByteOrder)(nil)).Elem(), "")
	pkg.AddType("ByteOrder", reflect.TypeOf((*encoding_binary.ByteOrder)(nil)).Elem(), "")

	// Interface Proxies
	pkg.AddInterfaceProxy("AppendByteOrder", reflect.TypeOf((*encoding_binary.AppendByteOrder)(nil)).Elem(), []string{"AppendUint16", "AppendUint32", "AppendUint64", "String"}, newProxy_encoding_binary_AppendByteOrder)
	pkg.AddInterfaceProxy("ByteOrder", reflect.TypeOf((*encoding_binary.ByteOrder)(nil)).Elem(), []string{"PutUint16", "PutUint32", "PutUint64", "String", "Uint16", "Uint32", "Uint64"}, newProxy_encoding_binary_ByteOrder)

}

func direct_encoding_binary_Append(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Interface().(encoding_binary.ByteOrder)
	a2 := args[2].Interface()
	r0, r1 := encoding_binary.Append(a0, a1, a2)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_encoding_binary_AppendUvarint(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Uint()
	return value.MakeBytes([]byte(encoding_binary.AppendUvarint(a0, a1)))
}

func direct_encoding_binary_AppendVarint(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Int()
	return value.MakeBytes([]byte(encoding_binary.AppendVarint(a0, a1)))
}

func direct_encoding_binary_Decode(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Interface().(encoding_binary.ByteOrder)
	a2 := args[2].Interface()
	r0, r1 := encoding_binary.Decode(a0, a1, a2)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_encoding_binary_Encode(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Interface().(encoding_binary.ByteOrder)
	a2 := args[2].Interface()
	r0, r1 := encoding_binary.Encode(a0, a1, a2)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_encoding_binary_PutUvarint(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Uint()
	return value.MakeInt(int64(encoding_binary.PutUvarint(a0, a1)))
}

func direct_encoding_binary_PutVarint(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Int()
	return value.MakeInt(int64(encoding_binary.PutVarint(a0, a1)))
}

func direct_encoding_binary_Read(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Reader)
	a1 := args[1].Interface().(encoding_binary.ByteOrder)
	a2 := args[2].Interface()
	return value.FromInterface(encoding_binary.Read(a0, a1, a2))
}

func direct_encoding_binary_ReadUvarint(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.ByteReader)
	r0, r1 := encoding_binary.ReadUvarint(a0)
	return value.MakeValueSlice([]value.Value{value.MakeUint64(r0), value.FromInterface(r1)})
}

func direct_encoding_binary_ReadVarint(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.ByteReader)
	r0, r1 := encoding_binary.ReadVarint(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt64(r0), value.FromInterface(r1)})
}

func direct_encoding_binary_Size(args []value.Value) value.Value {
	a0 := args[0].Interface()
	return value.MakeInt(int64(encoding_binary.Size(a0)))
}

func direct_encoding_binary_Uvarint(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := encoding_binary.Uvarint(a0)
	return value.MakeValueSlice([]value.Value{value.MakeUint64(r0), value.MakeInt(int64(r1))})
}

func direct_encoding_binary_Varint(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := encoding_binary.Varint(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt64(r0), value.MakeInt(int64(r1))})
}

func direct_encoding_binary_Write(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Writer)
	a1 := args[1].Interface().(encoding_binary.ByteOrder)
	a2 := args[2].Interface()
	return value.FromInterface(encoding_binary.Write(a0, a1, a2))
}

type proxy_encoding_binary_AppendByteOrder struct {
	call external.InterfaceMethodCaller
}

func newProxy_encoding_binary_AppendByteOrder(_ value.Value, _ string, call external.InterfaceMethodCaller) (any, bool) {
	return &proxy_encoding_binary_AppendByteOrder{call: call}, true
}

func (p *proxy_encoding_binary_AppendByteOrder) AppendUint16(a0 []byte, a1 uint16) []byte {
	result, ok := p.call("AppendUint16", value.FromInterface(a0), value.FromInterface(a1))
	if !ok {
		return nil
	}
	return func() []byte {
		if b, ok := (result).Bytes(); ok {
			return b
		}
		v := (result).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
}

func (p *proxy_encoding_binary_AppendByteOrder) AppendUint32(a0 []byte, a1 uint32) []byte {
	result, ok := p.call("AppendUint32", value.FromInterface(a0), value.FromInterface(a1))
	if !ok {
		return nil
	}
	return func() []byte {
		if b, ok := (result).Bytes(); ok {
			return b
		}
		v := (result).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
}

func (p *proxy_encoding_binary_AppendByteOrder) AppendUint64(a0 []byte, a1 uint64) []byte {
	result, ok := p.call("AppendUint64", value.FromInterface(a0), value.FromInterface(a1))
	if !ok {
		return nil
	}
	return func() []byte {
		if b, ok := (result).Bytes(); ok {
			return b
		}
		v := (result).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
}

func (p *proxy_encoding_binary_AppendByteOrder) String() string {
	result, ok := p.call("String")
	if !ok {
		return ""
	}
	return result.String()
}

type proxy_encoding_binary_ByteOrder struct {
	call external.InterfaceMethodCaller
}

func newProxy_encoding_binary_ByteOrder(_ value.Value, _ string, call external.InterfaceMethodCaller) (any, bool) {
	return &proxy_encoding_binary_ByteOrder{call: call}, true
}

func (p *proxy_encoding_binary_ByteOrder) PutUint16(a0 []byte, a1 uint16) {
	_, _ = p.call("PutUint16", value.FromInterface(a0), value.FromInterface(a1))
}

func (p *proxy_encoding_binary_ByteOrder) PutUint32(a0 []byte, a1 uint32) {
	_, _ = p.call("PutUint32", value.FromInterface(a0), value.FromInterface(a1))
}

func (p *proxy_encoding_binary_ByteOrder) PutUint64(a0 []byte, a1 uint64) {
	_, _ = p.call("PutUint64", value.FromInterface(a0), value.FromInterface(a1))
}

func (p *proxy_encoding_binary_ByteOrder) String() string {
	result, ok := p.call("String")
	if !ok {
		return ""
	}
	return result.String()
}

func (p *proxy_encoding_binary_ByteOrder) Uint16(a0 []byte) uint16 {
	result, ok := p.call("Uint16", value.FromInterface(a0))
	if !ok {
		return 0
	}
	return uint16(result.Uint())
}

func (p *proxy_encoding_binary_ByteOrder) Uint32(a0 []byte) uint32 {
	result, ok := p.call("Uint32", value.FromInterface(a0))
	if !ok {
		return 0
	}
	return uint32(result.Uint())
}

func (p *proxy_encoding_binary_ByteOrder) Uint64(a0 []byte) uint64 {
	result, ok := p.call("Uint64", value.FromInterface(a0))
	if !ok {
		return 0
	}
	return result.Uint()
}
