// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	encoding_base32 "encoding/base32"
	"fmt"
	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
	"io"
	"reflect"
)

func init() {
	pkg := importer.RegisterPackage("encoding/base32", "base32")

	// Functions
	pkg.AddFunction("NewDecoder", encoding_base32.NewDecoder, "", directCallEncodingBase32NewDecoder)
	pkg.AddFunction("NewEncoder", encoding_base32.NewEncoder, "", directCallEncodingBase32NewEncoder)
	pkg.AddFunction("NewEncoding", encoding_base32.NewEncoding, "", directCallEncodingBase32NewEncoding)

	// Constants
	pkg.AddConstant("NoPadding", encoding_base32.NoPadding, "")
	pkg.AddConstant("StdPadding", encoding_base32.StdPadding, "")

	// Variables
	pkg.AddVariable("HexEncoding", &encoding_base32.HexEncoding, "")
	pkg.AddVariable("StdEncoding", &encoding_base32.StdEncoding, "")

	// Types
	pkg.AddType("CorruptInputError", reflect.TypeOf((*encoding_base32.CorruptInputError)(nil)).Elem(), "")
	pkg.AddType("Encoding", reflect.TypeOf(encoding_base32.Encoding{}), "")

}

func directArgEncodingBase32[T any](v value.Value) (T, error) {
	var zero T
	rt := reflect.TypeFor[T]()
	rv, err := value.DefaultConverter().ToReflect(v, rt)
	if err != nil {
		return zero, err
	}
	if !rv.IsValid() {
		return zero, nil
	}
	if rv.Type().AssignableTo(rt) {
		return rv.Interface().(T), nil
	}
	if rv.Type().ConvertibleTo(rt) {
		return rv.Convert(rt).Interface().(T), nil
	}
	return zero, fmt.Errorf("cannot convert %s to %s", rv.Type(), rt)
}

func directVariadicArgsEncodingBase32[T any](args []value.Value) ([]T, error) {
	if len(args) == 1 {
		if packed, err := directArgEncodingBase32[[]T](args[0]); err == nil {
			return packed, nil
		}
		if rv, ok := args[0].Reflect(); ok && rv.IsValid() {
			for rv.Kind() == reflect.Interface && !rv.IsNil() {
				rv = rv.Elem()
			}
			if rv.Kind() == reflect.Slice {
				out := make([]T, rv.Len())
				conv := value.DefaultConverter()
				for i := 0; i < rv.Len(); i++ {
					vv, err := conv.FromReflect(rv.Index(i))
					if err != nil {
						return nil, fmt.Errorf("variadic explode %d: %w", i, err)
					}
					out[i], err = directArgEncodingBase32[T](vv)
					if err != nil {
						return nil, fmt.Errorf("variadic arg %d: %w", i, err)
					}
				}
				return out, nil
			}
		}
	}
	out := make([]T, len(args))
	for i, arg := range args {
		v, err := directArgEncodingBase32[T](arg)
		if err != nil {
			return nil, fmt.Errorf("variadic arg %d: %w", i, err)
		}
		out[i] = v
	}
	return out, nil
}

func directResultsEncodingBase32(vals ...any) ([]value.Value, error) {
	out := make([]value.Value, len(vals))
	conv := value.DefaultConverter()
	for i, v := range vals {
		vv, err := conv.FromAny(v)
		if err != nil {
			return nil, fmt.Errorf("result %d: %w", i, err)
		}
		out[i] = vv
	}
	return out, nil
}

func directCallEncodingBase32NewDecoder(args []value.Value) ([]value.Value, error) {
	if len(args) != 2 {
		return nil, fmt.Errorf("arg count %d != 2", len(args))
	}
	a0, err := directArgEncodingBase32[*encoding_base32.Encoding](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	a1, err := directArgEncodingBase32[io.Reader](args[1])
	if err != nil {
		return nil, fmt.Errorf("arg 1: %w", err)
	}
	r0 := encoding_base32.NewDecoder(a0, a1)
	return directResultsEncodingBase32(r0)
}

func directCallEncodingBase32NewEncoder(args []value.Value) ([]value.Value, error) {
	if len(args) != 2 {
		return nil, fmt.Errorf("arg count %d != 2", len(args))
	}
	a0, err := directArgEncodingBase32[*encoding_base32.Encoding](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	a1, err := directArgEncodingBase32[io.Writer](args[1])
	if err != nil {
		return nil, fmt.Errorf("arg 1: %w", err)
	}
	r0 := encoding_base32.NewEncoder(a0, a1)
	return directResultsEncodingBase32(r0)
}

func directCallEncodingBase32NewEncoding(args []value.Value) ([]value.Value, error) {
	if len(args) != 1 {
		return nil, fmt.Errorf("arg count %d != 1", len(args))
	}
	a0, err := directArgEncodingBase32[string](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	r0 := encoding_base32.NewEncoding(a0)
	return directResultsEncodingBase32(r0)
}
