// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	encoding_json "encoding/json"
	"reflect"

	"gig/importer"
	"gig/value"
)

func init() {
	pkg := importer.RegisterPackage("encoding/json", "json")

	// Functions
	pkg.AddFunction("Compact", encoding_json.Compact, "", nil)
	pkg.AddFunction("HTMLEscape", encoding_json.HTMLEscape, "", nil)
	pkg.AddFunction("Indent", encoding_json.Indent, "", nil)
	pkg.AddFunction("Marshal", encoding_json.Marshal, "", nil)
	pkg.AddFunction("MarshalIndent", encoding_json.MarshalIndent, "", nil)
	pkg.AddFunction("NewDecoder", encoding_json.NewDecoder, "", nil)
	pkg.AddFunction("NewEncoder", encoding_json.NewEncoder, "", nil)
	pkg.AddFunction("Unmarshal", encoding_json.Unmarshal, "", nil)
	pkg.AddFunction("Valid", encoding_json.Valid, "", direct_encoding_json_Valid)

	// Types
	pkg.AddType("Decoder", reflect.TypeOf(encoding_json.Decoder{}), "")
	pkg.AddType("Delim", reflect.TypeOf((*encoding_json.Delim)(nil)).Elem(), "")
	pkg.AddType("Encoder", reflect.TypeOf(encoding_json.Encoder{}), "")
	pkg.AddType("InvalidUTF8Error", reflect.TypeOf(encoding_json.InvalidUTF8Error{}), "")
	pkg.AddType("InvalidUnmarshalError", reflect.TypeOf(encoding_json.InvalidUnmarshalError{}), "")
	pkg.AddType("Marshaler", reflect.TypeOf((*encoding_json.Marshaler)(nil)).Elem(), "")
	pkg.AddType("MarshalerError", reflect.TypeOf(encoding_json.MarshalerError{}), "")
	pkg.AddType("Number", reflect.TypeOf((*encoding_json.Number)(nil)).Elem(), "")
	pkg.AddType("RawMessage", reflect.TypeOf((*encoding_json.RawMessage)(nil)).Elem(), "")
	pkg.AddType("SyntaxError", reflect.TypeOf(encoding_json.SyntaxError{}), "")
	pkg.AddType("Token", reflect.TypeOf((*encoding_json.Token)(nil)).Elem(), "")
	pkg.AddType("UnmarshalFieldError", reflect.TypeOf(encoding_json.UnmarshalFieldError{}), "")
	pkg.AddType("UnmarshalTypeError", reflect.TypeOf(encoding_json.UnmarshalTypeError{}), "")
	pkg.AddType("Unmarshaler", reflect.TypeOf((*encoding_json.Unmarshaler)(nil)).Elem(), "")
	pkg.AddType("UnsupportedTypeError", reflect.TypeOf(encoding_json.UnsupportedTypeError{}), "")
	pkg.AddType("UnsupportedValueError", reflect.TypeOf(encoding_json.UnsupportedValueError{}), "")

}

func direct_encoding_json_Valid(args []value.Value) value.Value {
	a0 := args[0].Interface().([]byte)
	return value.MakeBool(encoding_json.Valid(a0))
}
