// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	encoding_pem "encoding/pem"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("encoding/pem", "pem")

	// Functions
	pkg.AddFunction("Decode", encoding_pem.Decode, "")
	pkg.AddFunction("Encode", encoding_pem.Encode, "")
	pkg.AddFunction("EncodeToMemory", encoding_pem.EncodeToMemory, "")

	// Types
	pkg.AddType("Block", reflect.TypeOf(encoding_pem.Block{}), "")

}
