// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	encoding_ascii85 "encoding/ascii85"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("encoding/ascii85", "ascii85")

	// Functions
	pkg.AddFunction("Decode", encoding_ascii85.Decode, "")
	pkg.AddFunction("Encode", encoding_ascii85.Encode, "")
	pkg.AddFunction("MaxEncodedLen", encoding_ascii85.MaxEncodedLen, "")
	pkg.AddFunction("NewDecoder", encoding_ascii85.NewDecoder, "")
	pkg.AddFunction("NewEncoder", encoding_ascii85.NewEncoder, "")

	// Types
	pkg.AddType("CorruptInputError", reflect.TypeOf((*encoding_ascii85.CorruptInputError)(nil)).Elem(), "")

}
