// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"errors"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("errors", "errors")

	// Functions
	pkg.AddFunction("As", errors.As, "", nil)
	pkg.AddFunction("Is", errors.Is, "", direct_errors_Is)
	pkg.AddFunction("Join", errors.Join, "", direct_errors_Join)
	pkg.AddFunction("New", errors.New, "", direct_errors_New)
	pkg.AddFunction("Unwrap", errors.Unwrap, "", direct_errors_Unwrap)

	// Variables
	pkg.AddVariable("ErrUnsupported", &errors.ErrUnsupported, "")

}

func direct_errors_Is(args []value.Value) value.Value {
	a0 := args[0].Interface().(error)
	a1 := args[1].Interface().(error)
	return value.MakeBool(errors.Is(a0, a1))
}

func direct_errors_Join(args []value.Value) value.Value {
	varArgs := make([]error, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface().(error)
	}
	return value.FromInterface(errors.Join(varArgs...))
}

func direct_errors_New(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(errors.New(a0))
}

func direct_errors_Unwrap(args []value.Value) value.Value {
	a0 := args[0].Interface().(error)
	return value.FromInterface(errors.Unwrap(a0))
}
