// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"fmt"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("fmt", "fmt")

	// Functions
	pkg.AddFunction("Append", fmt.Append, "")
	pkg.AddFunction("Appendf", fmt.Appendf, "")
	pkg.AddFunction("Appendln", fmt.Appendln, "")
	pkg.AddFunction("Errorf", fmt.Errorf, "")
	pkg.AddFunction("FormatString", fmt.FormatString, "")
	pkg.AddFunction("Fprint", fmt.Fprint, "")
	pkg.AddFunction("Fprintf", fmt.Fprintf, "")
	pkg.AddFunction("Fprintln", fmt.Fprintln, "")
	pkg.AddFunction("Fscan", fmt.Fscan, "")
	pkg.AddFunction("Fscanf", fmt.Fscanf, "")
	pkg.AddFunction("Fscanln", fmt.Fscanln, "")
	pkg.AddFunction("Print", fmt.Print, "")
	pkg.AddFunction("Printf", fmt.Printf, "")
	pkg.AddFunction("Println", fmt.Println, "")
	pkg.AddFunction("Scan", fmt.Scan, "")
	pkg.AddFunction("Scanf", fmt.Scanf, "")
	pkg.AddFunction("Scanln", fmt.Scanln, "")
	pkg.AddFunction("Sprint", fmt.Sprint, "")
	pkg.AddFunction("Sprintf", fmt.Sprintf, "")
	pkg.AddFunction("Sprintln", fmt.Sprintln, "")
	pkg.AddFunction("Sscan", fmt.Sscan, "")
	pkg.AddFunction("Sscanf", fmt.Sscanf, "")
	pkg.AddFunction("Sscanln", fmt.Sscanln, "")

	// Types
	pkg.AddType("Formatter", reflect.TypeOf((*fmt.Formatter)(nil)).Elem(), "")
	pkg.AddType("GoStringer", reflect.TypeOf((*fmt.GoStringer)(nil)).Elem(), "")
	pkg.AddType("ScanState", reflect.TypeOf((*fmt.ScanState)(nil)).Elem(), "")
	pkg.AddType("Scanner", reflect.TypeOf((*fmt.Scanner)(nil)).Elem(), "")
	pkg.AddType("State", reflect.TypeOf((*fmt.State)(nil)).Elem(), "")
	pkg.AddType("Stringer", reflect.TypeOf((*fmt.Stringer)(nil)).Elem(), "")

}
