// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"fmt"
	io "io"
	"reflect"
	"strings"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("fmt", "fmt")

	// Functions
	pkg.AddFunction("Append", fmt.Append, "", direct_fmt_Append)
	pkg.AddFunction("Appendf", fmt.Appendf, "", direct_fmt_Appendf)
	pkg.AddFunction("Appendln", fmt.Appendln, "", direct_fmt_Appendln)
	pkg.AddFunction("Errorf", fmt.Errorf, "", direct_fmt_Errorf)
	pkg.AddFunction("FormatString", fmt.FormatString, "", direct_fmt_FormatString)
	pkg.AddFunction("Fprint", fmt.Fprint, "", direct_fmt_Fprint)
	pkg.AddFunction("Fprintf", fmt.Fprintf, "", direct_fmt_Fprintf)
	pkg.AddFunction("Fprintln", fmt.Fprintln, "", direct_fmt_Fprintln)
	pkg.AddFunction("Fscan", fmt.Fscan, "", direct_fmt_Fscan)
	pkg.AddFunction("Fscanf", fmt.Fscanf, "", direct_fmt_Fscanf)
	pkg.AddFunction("Fscanln", fmt.Fscanln, "", direct_fmt_Fscanln)
	pkg.AddFunction("Print", fmt.Print, "", direct_fmt_Print)
	pkg.AddFunction("Printf", fmt.Printf, "", direct_fmt_Printf)
	pkg.AddFunction("Println", fmt.Println, "", direct_fmt_Println)
	pkg.AddFunction("Scan", fmt.Scan, "", direct_fmt_Scan)
	pkg.AddFunction("Scanf", fmt.Scanf, "", direct_fmt_Scanf)
	pkg.AddFunction("Scanln", fmt.Scanln, "", direct_fmt_Scanln)
	pkg.AddFunction("Sprint", fmt.Sprint, "", direct_fmt_Sprint)
	pkg.AddFunction("Sprintf", fmt.Sprintf, "", direct_fmt_Sprintf)
	pkg.AddFunction("Sprintln", fmt.Sprintln, "", direct_fmt_Sprintln)
	pkg.AddFunction("Sscan", fmt.Sscan, "", direct_fmt_Sscan)
	pkg.AddFunction("Sscanf", fmt.Sscanf, "", direct_fmt_Sscanf)
	pkg.AddFunction("Sscanln", fmt.Sscanln, "", direct_fmt_Sscanln)

	// Types
	pkg.AddType("Formatter", reflect.TypeOf((*fmt.Formatter)(nil)).Elem(), "")
	pkg.AddType("GoStringer", reflect.TypeOf((*fmt.GoStringer)(nil)).Elem(), "")
	pkg.AddType("ScanState", reflect.TypeOf((*fmt.ScanState)(nil)).Elem(), "")
	pkg.AddType("Scanner", reflect.TypeOf((*fmt.Scanner)(nil)).Elem(), "")
	pkg.AddType("State", reflect.TypeOf((*fmt.State)(nil)).Elem(), "")
	pkg.AddType("Stringer", reflect.TypeOf((*fmt.Stringer)(nil)).Elem(), "")

}

func direct_fmt_Append(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	return value.MakeBytes([]byte(fmt.Append(a0, varArgs...)))
}

func direct_fmt_Appendf(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].String()
	varArgs := make([]interface{}, len(args)-2)
	for i := 2; i < len(args); i++ {
		varArgs[i-2] = sanitizeArgForFmt(args[i])
	}
	return value.MakeBytes([]byte(fmt.Appendf(a0, a1, varArgs...)))
}

func direct_fmt_Appendln(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	return value.MakeBytes([]byte(fmt.Appendln(a0, varArgs...)))
}

func direct_fmt_Errorf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	return value.FromInterface(fmt.Errorf(a0, varArgs...))
}

func direct_fmt_FormatString(args []value.Value) value.Value {
	a0 := args[0].Interface().(fmt.State)
	a1 := int32(args[1].Int())
	return value.MakeString(string(fmt.FormatString(a0, a1)))
}

func direct_fmt_Fprint(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Writer)
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Fprint(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Fprintf(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Writer)
	a1 := args[1].String()
	varArgs := make([]interface{}, len(args)-2)
	for i := 2; i < len(args); i++ {
		varArgs[i-2] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Fprintf(a0, a1, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Fprintln(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Writer)
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Fprintln(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Fscan(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Reader)
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Fscan(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Fscanf(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Reader)
	a1 := args[1].String()
	varArgs := make([]interface{}, len(args)-2)
	for i := 2; i < len(args); i++ {
		varArgs[i-2] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Fscanf(a0, a1, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Fscanln(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Reader)
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Fscanln(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Print(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Print(varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Printf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Printf(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Println(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Println(varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Scan(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Scan(varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Scanf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Scanf(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Scanln(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Scanln(varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Sprint(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = sanitizeArgForFmt(args[i])
	}
	return value.MakeString(string(fmt.Sprint(varArgs...)))
}

func direct_fmt_Sprintf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	return value.MakeString(string(sprintfWithTypeAwareness(a0, varArgs...)))
}

func direct_fmt_Sprintln(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = sanitizeArgForFmt(args[i])
	}
	return value.MakeString(string(fmt.Sprintln(varArgs...)))
}

func direct_fmt_Sscan(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Sscan(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Sscanf(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	varArgs := make([]interface{}, len(args)-2)
	for i := 2; i < len(args); i++ {
		varArgs[i-2] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Sscanf(a0, a1, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_fmt_Sscanln(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = sanitizeArgForFmt(args[i])
	}
	r0, r1 := fmt.Sscanln(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

// --- fmt sanitization helpers (generated by gentool) ---

// gigStructFormatter wraps an interpreter-synthesized struct for proper fmt formatting.
// It implements fmt.Formatter and fmt.Stringer to:
// - Hide the _gig_id sentinel field from %v output
// - Report the correct type name for %T
// - Call the interpreted String() method for %v/%s if available
type gigStructFormatter struct {
	rv       reflect.Value // the full struct including _gig_id
	typeName string        // qualified type name (e.g., "known_issues.point")
	stringer func() string // nil if no String() method
}

var _ fmt.Formatter = (*gigStructFormatter)(nil)

func (g *gigStructFormatter) Format(f fmt.State, verb rune) {
	switch verb {
	case 'T':
		fmt.Fprint(f, g.typeName)
	case 'v', 's':
		if g.stringer != nil && (verb == 's' || (verb == 'v' && !f.Flag('#'))) {
			fmt.Fprint(f, g.stringer())
			return
		}
		// Print struct fields without _gig_id
		if verb == 'v' && f.Flag('#') {
			// %#v: detailed format
			fmt.Fprintf(f, "%s{", g.typeName)
		} else {
			fmt.Fprint(f, "{")
		}
		rt := g.rv.Type()
		first := true
		for i := 0; i < rt.NumField(); i++ {
			sf := rt.Field(i)
			if sf.Name == "_gig_id" {
				continue
			}
			if !first {
				fmt.Fprint(f, " ")
			}
			if verb == 'v' && f.Flag('#') {
				fmt.Fprintf(f, "%s:", sf.Name)
			}
			fmt.Fprintf(f, "%"+string(verb), g.rv.Field(i).Interface())
			first = false
		}
		fmt.Fprint(f, "}")
	default:
		// For other verbs, use default formatting of the clean struct
		fmt.Fprintf(f, "%"+string(verb), g.cleanInterface())
	}
}

func (g *gigStructFormatter) String() string {
	if g.stringer != nil {
		return g.stringer()
	}
	return fmt.Sprintf("%v", g)
}

// cleanInterface returns the struct value without _gig_id for use with standard fmt.
func (g *gigStructFormatter) cleanInterface() any {
	rt := g.rv.Type()
	fields := make([]reflect.StructField, 0, rt.NumField())
	for i := 0; i < rt.NumField(); i++ {
		sf := rt.Field(i)
		if sf.Name == "_gig_id" {
			continue
		}
		fields = append(fields, sf)
	}
	cleanType := reflect.StructOf(fields)
	cleanVal := reflect.New(cleanType).Elem()
	fi := 0
	for i := 0; i < rt.NumField(); i++ {
		if rt.Field(i).Name == "_gig_id" {
			continue
		}
		cleanVal.Field(fi).Set(g.rv.Field(i))
		fi++
	}
	return cleanVal.Interface()
}

// isGigStruct checks if a value is an interpreter-synthesized struct with _gig_id field.
// Returns the reflect.Value and the qualified type name extracted from _gig_id.PkgPath.
func isGigStruct(v any) (reflect.Value, string, bool) {
	rv := reflect.ValueOf(v)
	if rv.Kind() != reflect.Struct {
		return rv, "", false
	}
	rt := rv.Type()
	for i := 0; i < rt.NumField(); i++ {
		sf := rt.Field(i)
		if sf.Name == "_gig_id" {
			// Extract type name from PkgPath (format: "gig/internal#pkg.TypeName" or "pkg#TypeName")
			typeName := ""
			if idx := strings.LastIndex(sf.PkgPath, "#"); idx >= 0 {
				typeName = sf.PkgPath[idx+1:]
			}
			return rv, typeName, true
		}
	}
	return rv, "", false
}

// sanitizeArgForFmt wraps interpreter-synthesized structs in gigStructFormatter.
// Takes value.Value to enable compiled method lookup for fmt.Stringer support.
func sanitizeArgForFmt(v value.Value) any {
	iface := v.Interface()
	rv, typeName, ok := isGigStruct(iface)
	if !ok {
		return iface
	}
	gsf := &gigStructFormatter{
		rv:       rv,
		typeName: typeName,
	}
	// Check if the interpreted type has a String() method
	if result, found := value.CallMethod(nil, "String", v); found {
		str := result.String()
		gsf.stringer = func() string { return str }
	}
	return gsf
}

// sprintfWithTypeAwareness handles %T correctly for gigStructFormatter values.
// Standard fmt.Sprintf("%T") bypasses fmt.Formatter, so we intercept it here.
func sprintfWithTypeAwareness(format string, args ...any) string {
	// Fast path: no %T in format string
	if !strings.Contains(format, "%T") {
		return fmt.Sprintf(format, args...)
	}
	// Slow path: replace each %T that corresponds to a gigStructFormatter arg
	// with the correct type name.
	var result strings.Builder
	argIdx := 0
	i := 0
	for i < len(format) {
		if format[i] == '%' {
			if i+1 < len(format) && format[i+1] == '%' {
				result.WriteString("%%")
				i += 2
				continue
			}
			// Find the verb
			j := i + 1
			// Skip flags, width, precision
			for j < len(format) && (format[j] == '-' || format[j] == '+' || format[j] == '#' || format[j] == ' ' || format[j] == '0') {
				j++
			}
			// Skip width
			for j < len(format) && format[j] >= '0' && format[j] <= '9' {
				j++
			}
			// Skip precision
			if j < len(format) && format[j] == '.' {
				j++
				for j < len(format) && format[j] >= '0' && format[j] <= '9' {
					j++
				}
			}
			if j < len(format) {
				verb := format[j]
				if verb == 'T' && argIdx < len(args) {
					if gsf, ok := args[argIdx].(*gigStructFormatter); ok {
						result.WriteString(gsf.typeName)
						argIdx++
						i = j + 1
						continue
					}
				}
				// For non-T verbs or non-gig args, use fmt.Sprintf for this single verb
				if argIdx < len(args) {
					result.WriteString(fmt.Sprintf(format[i:j+1], args[argIdx]))
					argIdx++
				} else {
					result.WriteString(format[i : j+1])
				}
				i = j + 1
				continue
			}
		}
		result.WriteByte(format[i])
		i++
	}
	return result.String()
}
