// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	hash_crc64 "hash/crc64"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("hash/crc64", "crc64")

	// Functions
	pkg.AddFunction("Checksum", hash_crc64.Checksum, "")
	pkg.AddFunction("MakeTable", hash_crc64.MakeTable, "")
	pkg.AddFunction("New", hash_crc64.New, "")
	pkg.AddFunction("Update", hash_crc64.Update, "")

	// Constants
	pkg.AddConstant("ECMA", uint64(hash_crc64.ECMA), "")
	pkg.AddConstant("ISO", uint64(hash_crc64.ISO), "")
	pkg.AddConstant("Size", hash_crc64.Size, "")

	// Types
	pkg.AddType("Table", reflect.TypeOf((*hash_crc64.Table)(nil)).Elem(), "")

}
