// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	hash_fnv "hash/fnv"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("hash/fnv", "fnv")

	// Functions
	pkg.AddFunction("New128", hash_fnv.New128, "")
	pkg.AddFunction("New128a", hash_fnv.New128a, "")
	pkg.AddFunction("New32", hash_fnv.New32, "")
	pkg.AddFunction("New32a", hash_fnv.New32a, "")
	pkg.AddFunction("New64", hash_fnv.New64, "")
	pkg.AddFunction("New64a", hash_fnv.New64a, "")

}
