// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	hash_crc32 "hash/crc32"
	"reflect"

	"git.woa.com/youngjin/gig/importer"
	"git.woa.com/youngjin/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("hash/crc32", "crc32")

	// Functions
	pkg.AddFunction("Checksum", hash_crc32.Checksum, "", direct_hash_crc32_Checksum)
	pkg.AddFunction("ChecksumIEEE", hash_crc32.ChecksumIEEE, "", direct_hash_crc32_ChecksumIEEE)
	pkg.AddFunction("MakeTable", hash_crc32.MakeTable, "", direct_hash_crc32_MakeTable)
	pkg.AddFunction("New", hash_crc32.New, "", direct_hash_crc32_New)
	pkg.AddFunction("NewIEEE", hash_crc32.NewIEEE, "", direct_hash_crc32_NewIEEE)
	pkg.AddFunction("Update", hash_crc32.Update, "", direct_hash_crc32_Update)

	// Constants
	pkg.AddConstant("Castagnoli", hash_crc32.Castagnoli, "")
	pkg.AddConstant("IEEE", hash_crc32.IEEE, "")
	pkg.AddConstant("Koopman", hash_crc32.Koopman, "")
	pkg.AddConstant("Size", hash_crc32.Size, "")

	// Variables
	pkg.AddVariable("IEEETable", &hash_crc32.IEEETable, "")

	// Types
	pkg.AddType("Table", reflect.TypeOf((*hash_crc32.Table)(nil)).Elem(), "")

}

func direct_hash_crc32_Checksum(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].Interface().(*hash_crc32.Table)
	return value.MakeUint(uint64(hash_crc32.Checksum(a0, a1)))
}

func direct_hash_crc32_ChecksumIEEE(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.MakeUint(uint64(hash_crc32.ChecksumIEEE(a0)))
}

func direct_hash_crc32_MakeTable(args []value.Value) value.Value {
	a0 := uint32(args[0].Uint())
	return value.FromInterface(hash_crc32.MakeTable(a0))
}

func direct_hash_crc32_New(args []value.Value) value.Value {
	a0 := args[0].Interface().(*hash_crc32.Table)
	return value.FromInterface(hash_crc32.New(a0))
}

func direct_hash_crc32_NewIEEE(args []value.Value) value.Value {
	return value.FromInterface(hash_crc32.NewIEEE())
}

func direct_hash_crc32_Update(args []value.Value) value.Value {
	a0 := uint32(args[0].Uint())
	a1 := args[1].Interface().(*hash_crc32.Table)
	a2 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.MakeUint(uint64(hash_crc32.Update(a0, a1, a2)))
}
