// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	hash_adler32 "hash/adler32"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("hash/adler32", "adler32")

	// Functions
	pkg.AddFunction("Checksum", hash_adler32.Checksum, "")
	pkg.AddFunction("New", hash_adler32.New, "")

	// Constants
	pkg.AddConstant("Size", hash_adler32.Size, "")

}
