// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	html_template "html/template"
	io "io"
	io_fs "io/fs"
	"reflect"
	text_template_parse "text/template/parse"

	"git.woa.com/youngjin/gig/importer"
	"git.woa.com/youngjin/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("html/template", "template")

	// Functions
	pkg.AddFunction("HTMLEscape", html_template.HTMLEscape, "", direct_html_template_HTMLEscape)
	pkg.AddFunction("HTMLEscapeString", html_template.HTMLEscapeString, "", direct_html_template_HTMLEscapeString)
	pkg.AddFunction("HTMLEscaper", html_template.HTMLEscaper, "", direct_html_template_HTMLEscaper)
	pkg.AddFunction("IsTrue", html_template.IsTrue, "", direct_html_template_IsTrue)
	pkg.AddFunction("JSEscape", html_template.JSEscape, "", direct_html_template_JSEscape)
	pkg.AddFunction("JSEscapeString", html_template.JSEscapeString, "", direct_html_template_JSEscapeString)
	pkg.AddFunction("JSEscaper", html_template.JSEscaper, "", direct_html_template_JSEscaper)
	pkg.AddFunction("Must", html_template.Must, "", direct_html_template_Must)
	pkg.AddFunction("New", html_template.New, "", direct_html_template_New)
	pkg.AddFunction("ParseFS", html_template.ParseFS, "", direct_html_template_ParseFS)
	pkg.AddFunction("ParseFiles", html_template.ParseFiles, "", direct_html_template_ParseFiles)
	pkg.AddFunction("ParseGlob", html_template.ParseGlob, "", direct_html_template_ParseGlob)
	pkg.AddFunction("URLQueryEscaper", html_template.URLQueryEscaper, "", direct_html_template_URLQueryEscaper)

	// Constants
	pkg.AddConstant("ErrAmbigContext", html_template.ErrAmbigContext, "")
	pkg.AddConstant("ErrBadHTML", html_template.ErrBadHTML, "")
	pkg.AddConstant("ErrBranchEnd", html_template.ErrBranchEnd, "")
	pkg.AddConstant("ErrEndContext", html_template.ErrEndContext, "")
	pkg.AddConstant("ErrJSTemplate", html_template.ErrJSTemplate, "")
	pkg.AddConstant("ErrNoSuchTemplate", html_template.ErrNoSuchTemplate, "")
	pkg.AddConstant("ErrOutputContext", html_template.ErrOutputContext, "")
	pkg.AddConstant("ErrPartialCharset", html_template.ErrPartialCharset, "")
	pkg.AddConstant("ErrPartialEscape", html_template.ErrPartialEscape, "")
	pkg.AddConstant("ErrPredefinedEscaper", html_template.ErrPredefinedEscaper, "")
	pkg.AddConstant("ErrRangeLoopReentry", html_template.ErrRangeLoopReentry, "")
	pkg.AddConstant("ErrSlashAmbig", html_template.ErrSlashAmbig, "")
	pkg.AddConstant("OK", html_template.OK, "")

	// Types
	pkg.AddType("CSS", reflect.TypeOf((*html_template.CSS)(nil)).Elem(), "")
	pkg.AddType("Error", reflect.TypeOf(html_template.Error{}), "")
	pkg.AddType("ErrorCode", reflect.TypeOf((*html_template.ErrorCode)(nil)).Elem(), "")
	pkg.AddType("HTML", reflect.TypeOf((*html_template.HTML)(nil)).Elem(), "")
	pkg.AddType("HTMLAttr", reflect.TypeOf((*html_template.HTMLAttr)(nil)).Elem(), "")
	pkg.AddType("JS", reflect.TypeOf((*html_template.JS)(nil)).Elem(), "")
	pkg.AddType("JSStr", reflect.TypeOf((*html_template.JSStr)(nil)).Elem(), "")
	pkg.AddType("Srcset", reflect.TypeOf((*html_template.Srcset)(nil)).Elem(), "")
	pkg.AddType("Template", reflect.TypeOf(html_template.Template{}), "")
	pkg.AddType("URL", reflect.TypeOf((*html_template.URL)(nil)).Elem(), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("Error", "Error", direct_method_html_template_Error_Error)
	pkg.AddMethodDirectCall("Template", "AddParseTree", direct_method_html_template_Template_AddParseTree)
	pkg.AddMethodDirectCall("Template", "Clone", direct_method_html_template_Template_Clone)
	pkg.AddMethodDirectCall("Template", "DefinedTemplates", direct_method_html_template_Template_DefinedTemplates)
	pkg.AddMethodDirectCall("Template", "Delims", direct_method_html_template_Template_Delims)
	pkg.AddMethodDirectCall("Template", "Execute", direct_method_html_template_Template_Execute)
	pkg.AddMethodDirectCall("Template", "ExecuteTemplate", direct_method_html_template_Template_ExecuteTemplate)
	pkg.AddMethodDirectCall("Template", "Funcs", direct_method_html_template_Template_Funcs)
	pkg.AddMethodDirectCall("Template", "Lookup", direct_method_html_template_Template_Lookup)
	pkg.AddMethodDirectCall("Template", "Name", direct_method_html_template_Template_Name)
	pkg.AddMethodDirectCall("Template", "New", direct_method_html_template_Template_New)
	pkg.AddMethodDirectCall("Template", "Option", direct_method_html_template_Template_Option)
	pkg.AddMethodDirectCall("Template", "Parse", direct_method_html_template_Template_Parse)
	pkg.AddMethodDirectCall("Template", "ParseFS", direct_method_html_template_Template_ParseFS)
	pkg.AddMethodDirectCall("Template", "ParseFiles", direct_method_html_template_Template_ParseFiles)
	pkg.AddMethodDirectCall("Template", "ParseGlob", direct_method_html_template_Template_ParseGlob)
	pkg.AddMethodDirectCall("Template", "Templates", direct_method_html_template_Template_Templates)

}

func direct_html_template_HTMLEscape(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Writer)
	a1 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	html_template.HTMLEscape(a0, a1)
	return value.MakeNil()
}

func direct_html_template_HTMLEscapeString(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(html_template.HTMLEscapeString(a0)))
}

func direct_html_template_HTMLEscaper(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	return value.MakeString(string(html_template.HTMLEscaper(varArgs...)))
}

func direct_html_template_IsTrue(args []value.Value) value.Value {
	a0 := args[0].Interface()
	r0, r1 := html_template.IsTrue(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBool(r0), value.MakeBool(r1)})
}

func direct_html_template_JSEscape(args []value.Value) value.Value {
	a0 := args[0].Interface().(io.Writer)
	a1 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	html_template.JSEscape(a0, a1)
	return value.MakeNil()
}

func direct_html_template_JSEscapeString(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(html_template.JSEscapeString(a0)))
}

func direct_html_template_JSEscaper(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	return value.MakeString(string(html_template.JSEscaper(varArgs...)))
}

func direct_html_template_Must(args []value.Value) value.Value {
	a0 := args[0].Interface().(*html_template.Template)
	a1 := args[1].Interface().(error)
	return value.FromInterface(html_template.Must(a0, a1))
}

func direct_html_template_New(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(html_template.New(a0))
}

func direct_html_template_ParseFS(args []value.Value) value.Value {
	a0 := args[0].Interface().(io_fs.FS)
	varArgs := make([]string, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].String()
	}
	r0, r1 := html_template.ParseFS(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_html_template_ParseFiles(args []value.Value) value.Value {
	varArgs := make([]string, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].String()
	}
	r0, r1 := html_template.ParseFiles(varArgs...)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_html_template_ParseGlob(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := html_template.ParseGlob(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_html_template_URLQueryEscaper(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	return value.MakeString(string(html_template.URLQueryEscaper(varArgs...)))
}

func direct_method_html_template_Error_Error(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Error)
	return value.MakeString(string(recv.Error()))
}

func direct_method_html_template_Template_AddParseTree(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].String()
	a1 := args[2].Interface().(*text_template_parse.Tree)
	r0, r1 := recv.AddParseTree(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_html_template_Template_Clone(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	r0, r1 := recv.Clone()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_html_template_Template_DefinedTemplates(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	return value.MakeString(string(recv.DefinedTemplates()))
}

func direct_method_html_template_Template_Delims(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].String()
	a1 := args[2].String()
	return value.FromInterface(recv.Delims(a0, a1))
}

func direct_method_html_template_Template_Execute(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].Interface().(io.Writer)
	a1 := args[2].Interface()
	return value.FromInterface(recv.Execute(a0, a1))
}

func direct_method_html_template_Template_ExecuteTemplate(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].Interface().(io.Writer)
	a1 := args[2].String()
	a2 := args[3].Interface()
	return value.FromInterface(recv.ExecuteTemplate(a0, a1, a2))
}

func direct_method_html_template_Template_Funcs(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].Interface().(html_template.FuncMap)
	return value.FromInterface(recv.Funcs(a0))
}

func direct_method_html_template_Template_Lookup(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].String()
	return value.FromInterface(recv.Lookup(a0))
}

func direct_method_html_template_Template_Name(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	return value.MakeString(string(recv.Name()))
}

func direct_method_html_template_Template_New(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].String()
	return value.FromInterface(recv.New(a0))
}

func direct_method_html_template_Template_Option(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	varArgs := make([]string, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].String()
	}
	return value.FromInterface(recv.Option(varArgs...))
}

func direct_method_html_template_Template_Parse(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].String()
	r0, r1 := recv.Parse(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_html_template_Template_ParseFS(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].Interface().(io_fs.FS)
	varArgs := make([]string, len(args)-2)
	for i := 2; i < len(args); i++ {
		varArgs[i-2] = args[i].String()
	}
	r0, r1 := recv.ParseFS(a0, varArgs...)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_html_template_Template_ParseFiles(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	varArgs := make([]string, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].String()
	}
	r0, r1 := recv.ParseFiles(varArgs...)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_html_template_Template_ParseGlob(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	a0 := args[1].String()
	r0, r1 := recv.ParseGlob(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_html_template_Template_Templates(args []value.Value) value.Value {
	recv := args[0].Interface().(*html_template.Template)
	return value.FromInterface(recv.Templates())
}
