// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	index_suffixarray "index/suffixarray"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("index/suffixarray", "suffixarray")

	// Functions
	pkg.AddFunction("New", index_suffixarray.New, "")

	// Types
	pkg.AddType("Index", reflect.TypeOf(index_suffixarray.Index{}), "")

}
