// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	math_big "math/big"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("math/big", "big")

	// Functions
	pkg.AddFunction("Jacobi", math_big.Jacobi, "")
	pkg.AddFunction("NewFloat", math_big.NewFloat, "")
	pkg.AddFunction("NewInt", math_big.NewInt, "")
	pkg.AddFunction("NewRat", math_big.NewRat, "")
	pkg.AddFunction("ParseFloat", math_big.ParseFloat, "")

	// Constants
	pkg.AddConstant("Above", math_big.Above, "")
	pkg.AddConstant("AwayFromZero", math_big.AwayFromZero, "")
	pkg.AddConstant("Below", math_big.Below, "")
	pkg.AddConstant("Exact", math_big.Exact, "")
	pkg.AddConstant("MaxBase", math_big.MaxBase, "")
	pkg.AddConstant("MaxExp", math_big.MaxExp, "")
	pkg.AddConstant("MaxPrec", math_big.MaxPrec, "")
	pkg.AddConstant("MinExp", math_big.MinExp, "")
	pkg.AddConstant("ToNearestAway", math_big.ToNearestAway, "")
	pkg.AddConstant("ToNearestEven", math_big.ToNearestEven, "")
	pkg.AddConstant("ToNegativeInf", math_big.ToNegativeInf, "")
	pkg.AddConstant("ToPositiveInf", math_big.ToPositiveInf, "")
	pkg.AddConstant("ToZero", math_big.ToZero, "")

	// Types
	pkg.AddType("Accuracy", reflect.TypeOf((*math_big.Accuracy)(nil)).Elem(), "")
	pkg.AddType("ErrNaN", reflect.TypeOf(math_big.ErrNaN{}), "")
	pkg.AddType("Float", reflect.TypeOf(math_big.Float{}), "")
	pkg.AddType("Int", reflect.TypeOf(math_big.Int{}), "")
	pkg.AddType("Rat", reflect.TypeOf(math_big.Rat{}), "")
	pkg.AddType("RoundingMode", reflect.TypeOf((*math_big.RoundingMode)(nil)).Elem(), "")
	pkg.AddType("Word", reflect.TypeOf((*math_big.Word)(nil)).Elem(), "")

}
