// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	math_bits "math/bits"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("math/bits", "bits")

	// Functions
	pkg.AddFunction("Add", math_bits.Add, "")
	pkg.AddFunction("Add32", math_bits.Add32, "")
	pkg.AddFunction("Add64", math_bits.Add64, "")
	pkg.AddFunction("Div", math_bits.Div, "")
	pkg.AddFunction("Div32", math_bits.Div32, "")
	pkg.AddFunction("Div64", math_bits.Div64, "")
	pkg.AddFunction("LeadingZeros", math_bits.LeadingZeros, "")
	pkg.AddFunction("LeadingZeros16", math_bits.LeadingZeros16, "")
	pkg.AddFunction("LeadingZeros32", math_bits.LeadingZeros32, "")
	pkg.AddFunction("LeadingZeros64", math_bits.LeadingZeros64, "")
	pkg.AddFunction("LeadingZeros8", math_bits.LeadingZeros8, "")
	pkg.AddFunction("Len", math_bits.Len, "")
	pkg.AddFunction("Len16", math_bits.Len16, "")
	pkg.AddFunction("Len32", math_bits.Len32, "")
	pkg.AddFunction("Len64", math_bits.Len64, "")
	pkg.AddFunction("Len8", math_bits.Len8, "")
	pkg.AddFunction("Mul", math_bits.Mul, "")
	pkg.AddFunction("Mul32", math_bits.Mul32, "")
	pkg.AddFunction("Mul64", math_bits.Mul64, "")
	pkg.AddFunction("OnesCount", math_bits.OnesCount, "")
	pkg.AddFunction("OnesCount16", math_bits.OnesCount16, "")
	pkg.AddFunction("OnesCount32", math_bits.OnesCount32, "")
	pkg.AddFunction("OnesCount64", math_bits.OnesCount64, "")
	pkg.AddFunction("OnesCount8", math_bits.OnesCount8, "")
	pkg.AddFunction("Rem", math_bits.Rem, "")
	pkg.AddFunction("Rem32", math_bits.Rem32, "")
	pkg.AddFunction("Rem64", math_bits.Rem64, "")
	pkg.AddFunction("Reverse", math_bits.Reverse, "")
	pkg.AddFunction("Reverse16", math_bits.Reverse16, "")
	pkg.AddFunction("Reverse32", math_bits.Reverse32, "")
	pkg.AddFunction("Reverse64", math_bits.Reverse64, "")
	pkg.AddFunction("Reverse8", math_bits.Reverse8, "")
	pkg.AddFunction("ReverseBytes", math_bits.ReverseBytes, "")
	pkg.AddFunction("ReverseBytes16", math_bits.ReverseBytes16, "")
	pkg.AddFunction("ReverseBytes32", math_bits.ReverseBytes32, "")
	pkg.AddFunction("ReverseBytes64", math_bits.ReverseBytes64, "")
	pkg.AddFunction("RotateLeft", math_bits.RotateLeft, "")
	pkg.AddFunction("RotateLeft16", math_bits.RotateLeft16, "")
	pkg.AddFunction("RotateLeft32", math_bits.RotateLeft32, "")
	pkg.AddFunction("RotateLeft64", math_bits.RotateLeft64, "")
	pkg.AddFunction("RotateLeft8", math_bits.RotateLeft8, "")
	pkg.AddFunction("Sub", math_bits.Sub, "")
	pkg.AddFunction("Sub32", math_bits.Sub32, "")
	pkg.AddFunction("Sub64", math_bits.Sub64, "")
	pkg.AddFunction("TrailingZeros", math_bits.TrailingZeros, "")
	pkg.AddFunction("TrailingZeros16", math_bits.TrailingZeros16, "")
	pkg.AddFunction("TrailingZeros32", math_bits.TrailingZeros32, "")
	pkg.AddFunction("TrailingZeros64", math_bits.TrailingZeros64, "")
	pkg.AddFunction("TrailingZeros8", math_bits.TrailingZeros8, "")

	// Constants
	pkg.AddConstant("UintSize", math_bits.UintSize, "")

}
