// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	math_cmplx "math/cmplx"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("math/cmplx", "cmplx")

	// Functions
	pkg.AddFunction("Abs", math_cmplx.Abs, "")
	pkg.AddFunction("Acos", math_cmplx.Acos, "")
	pkg.AddFunction("Acosh", math_cmplx.Acosh, "")
	pkg.AddFunction("Asin", math_cmplx.Asin, "")
	pkg.AddFunction("Asinh", math_cmplx.Asinh, "")
	pkg.AddFunction("Atan", math_cmplx.Atan, "")
	pkg.AddFunction("Atanh", math_cmplx.Atanh, "")
	pkg.AddFunction("Conj", math_cmplx.Conj, "")
	pkg.AddFunction("Cos", math_cmplx.Cos, "")
	pkg.AddFunction("Cosh", math_cmplx.Cosh, "")
	pkg.AddFunction("Cot", math_cmplx.Cot, "")
	pkg.AddFunction("Exp", math_cmplx.Exp, "")
	pkg.AddFunction("Inf", math_cmplx.Inf, "")
	pkg.AddFunction("IsInf", math_cmplx.IsInf, "")
	pkg.AddFunction("IsNaN", math_cmplx.IsNaN, "")
	pkg.AddFunction("Log", math_cmplx.Log, "")
	pkg.AddFunction("Log10", math_cmplx.Log10, "")
	pkg.AddFunction("NaN", math_cmplx.NaN, "")
	pkg.AddFunction("Phase", math_cmplx.Phase, "")
	pkg.AddFunction("Polar", math_cmplx.Polar, "")
	pkg.AddFunction("Pow", math_cmplx.Pow, "")
	pkg.AddFunction("Rect", math_cmplx.Rect, "")
	pkg.AddFunction("Sin", math_cmplx.Sin, "")
	pkg.AddFunction("Sinh", math_cmplx.Sinh, "")
	pkg.AddFunction("Sqrt", math_cmplx.Sqrt, "")
	pkg.AddFunction("Tan", math_cmplx.Tan, "")
	pkg.AddFunction("Tanh", math_cmplx.Tanh, "")

}
