// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"fmt"
	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
	math_big "math/big"
	"reflect"
)

func init() {
	pkg := importer.RegisterPackage("math/big", "big")

	// Functions
	pkg.AddFunction("Jacobi", math_big.Jacobi, "", directCallMathBigJacobi)
	pkg.AddFunction("NewFloat", math_big.NewFloat, "", directCallMathBigNewFloat)
	pkg.AddFunction("NewInt", math_big.NewInt, "", directCallMathBigNewInt)
	pkg.AddFunction("NewRat", math_big.NewRat, "", directCallMathBigNewRat)
	pkg.AddFunction("ParseFloat", math_big.ParseFloat, "", directCallMathBigParseFloat)

	// Constants
	pkg.AddConstant("Above", math_big.Above, "")
	pkg.AddConstant("AwayFromZero", math_big.AwayFromZero, "")
	pkg.AddConstant("Below", math_big.Below, "")
	pkg.AddConstant("Exact", math_big.Exact, "")
	pkg.AddConstant("MaxBase", math_big.MaxBase, "")
	pkg.AddConstant("MaxExp", math_big.MaxExp, "")
	pkg.AddConstant("MaxPrec", math_big.MaxPrec, "")
	pkg.AddConstant("MinExp", math_big.MinExp, "")
	pkg.AddConstant("ToNearestAway", math_big.ToNearestAway, "")
	pkg.AddConstant("ToNearestEven", math_big.ToNearestEven, "")
	pkg.AddConstant("ToNegativeInf", math_big.ToNegativeInf, "")
	pkg.AddConstant("ToPositiveInf", math_big.ToPositiveInf, "")
	pkg.AddConstant("ToZero", math_big.ToZero, "")

	// Types
	pkg.AddType("Accuracy", reflect.TypeOf((*math_big.Accuracy)(nil)).Elem(), "")
	pkg.AddType("ErrNaN", reflect.TypeOf(math_big.ErrNaN{}), "")
	pkg.AddType("Float", reflect.TypeOf(math_big.Float{}), "")
	pkg.AddType("Int", reflect.TypeOf(math_big.Int{}), "")
	pkg.AddType("Rat", reflect.TypeOf(math_big.Rat{}), "")
	pkg.AddType("RoundingMode", reflect.TypeOf((*math_big.RoundingMode)(nil)).Elem(), "")
	pkg.AddType("Word", reflect.TypeOf((*math_big.Word)(nil)).Elem(), "")

}

func directArgMathBig[T any](v value.Value) (T, error) {
	var zero T
	rt := reflect.TypeFor[T]()
	rv, err := value.DefaultConverter().ToReflect(v, rt)
	if err != nil {
		return zero, err
	}
	if !rv.IsValid() {
		return zero, nil
	}
	if rv.Type().AssignableTo(rt) {
		return rv.Interface().(T), nil
	}
	if rv.Type().ConvertibleTo(rt) {
		return rv.Convert(rt).Interface().(T), nil
	}
	return zero, fmt.Errorf("cannot convert %s to %s", rv.Type(), rt)
}

func directVariadicArgsMathBig[T any](args []value.Value) ([]T, error) {
	if len(args) == 1 {
		if packed, err := directArgMathBig[[]T](args[0]); err == nil {
			return packed, nil
		}
		if rv, ok := args[0].Reflect(); ok && rv.IsValid() {
			for rv.Kind() == reflect.Interface && !rv.IsNil() {
				rv = rv.Elem()
			}
			if rv.Kind() == reflect.Slice {
				out := make([]T, rv.Len())
				conv := value.DefaultConverter()
				for i := 0; i < rv.Len(); i++ {
					vv, err := conv.FromReflect(rv.Index(i))
					if err != nil {
						return nil, fmt.Errorf("variadic explode %d: %w", i, err)
					}
					out[i], err = directArgMathBig[T](vv)
					if err != nil {
						return nil, fmt.Errorf("variadic arg %d: %w", i, err)
					}
				}
				return out, nil
			}
		}
	}
	out := make([]T, len(args))
	for i, arg := range args {
		v, err := directArgMathBig[T](arg)
		if err != nil {
			return nil, fmt.Errorf("variadic arg %d: %w", i, err)
		}
		out[i] = v
	}
	return out, nil
}

func directResultsMathBig(vals ...any) ([]value.Value, error) {
	out := make([]value.Value, len(vals))
	conv := value.DefaultConverter()
	for i, v := range vals {
		vv, err := conv.FromAny(v)
		if err != nil {
			return nil, fmt.Errorf("result %d: %w", i, err)
		}
		out[i] = vv
	}
	return out, nil
}

func directCallMathBigJacobi(args []value.Value) ([]value.Value, error) {
	if len(args) != 2 {
		return nil, fmt.Errorf("arg count %d != 2", len(args))
	}
	a0, err := directArgMathBig[*math_big.Int](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	a1, err := directArgMathBig[*math_big.Int](args[1])
	if err != nil {
		return nil, fmt.Errorf("arg 1: %w", err)
	}
	r0 := math_big.Jacobi(a0, a1)
	return directResultsMathBig(r0)
}

func directCallMathBigNewFloat(args []value.Value) ([]value.Value, error) {
	if len(args) != 1 {
		return nil, fmt.Errorf("arg count %d != 1", len(args))
	}
	a0, err := directArgMathBig[float64](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	r0 := math_big.NewFloat(a0)
	return directResultsMathBig(r0)
}

func directCallMathBigNewInt(args []value.Value) ([]value.Value, error) {
	if len(args) != 1 {
		return nil, fmt.Errorf("arg count %d != 1", len(args))
	}
	a0, err := directArgMathBig[int64](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	r0 := math_big.NewInt(a0)
	return directResultsMathBig(r0)
}

func directCallMathBigNewRat(args []value.Value) ([]value.Value, error) {
	if len(args) != 2 {
		return nil, fmt.Errorf("arg count %d != 2", len(args))
	}
	a0, err := directArgMathBig[int64](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	a1, err := directArgMathBig[int64](args[1])
	if err != nil {
		return nil, fmt.Errorf("arg 1: %w", err)
	}
	r0 := math_big.NewRat(a0, a1)
	return directResultsMathBig(r0)
}

func directCallMathBigParseFloat(args []value.Value) ([]value.Value, error) {
	if len(args) != 4 {
		return nil, fmt.Errorf("arg count %d != 4", len(args))
	}
	a0, err := directArgMathBig[string](args[0])
	if err != nil {
		return nil, fmt.Errorf("arg 0: %w", err)
	}
	a1, err := directArgMathBig[int](args[1])
	if err != nil {
		return nil, fmt.Errorf("arg 1: %w", err)
	}
	a2, err := directArgMathBig[uint](args[2])
	if err != nil {
		return nil, fmt.Errorf("arg 2: %w", err)
	}
	a3, err := directArgMathBig[math_big.RoundingMode](args[3])
	if err != nil {
		return nil, fmt.Errorf("arg 3: %w", err)
	}
	r0, r1, r2 := math_big.ParseFloat(a0, a1, a2, a3)
	return directResultsMathBig(r0, r1, r2)
}
