// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"mime"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("mime", "mime")

	// Functions
	pkg.AddFunction("AddExtensionType", mime.AddExtensionType, "")
	pkg.AddFunction("ExtensionsByType", mime.ExtensionsByType, "")
	pkg.AddFunction("FormatMediaType", mime.FormatMediaType, "")
	pkg.AddFunction("ParseMediaType", mime.ParseMediaType, "")
	pkg.AddFunction("TypeByExtension", mime.TypeByExtension, "")

	// Constants
	pkg.AddConstant("BEncoding", mime.BEncoding, "")
	pkg.AddConstant("QEncoding", mime.QEncoding, "")

	// Variables
	pkg.AddVariable("ErrInvalidMediaParameter", &mime.ErrInvalidMediaParameter, "")

	// Types
	pkg.AddType("WordDecoder", reflect.TypeOf(mime.WordDecoder{}), "")
	pkg.AddType("WordEncoder", reflect.TypeOf((*mime.WordEncoder)(nil)).Elem(), "")

}
