// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"path"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("path", "path")

	// Functions
	pkg.AddFunction("Base", path.Base, "", direct_path_Base)
	pkg.AddFunction("Clean", path.Clean, "", direct_path_Clean)
	pkg.AddFunction("Dir", path.Dir, "", direct_path_Dir)
	pkg.AddFunction("Ext", path.Ext, "", direct_path_Ext)
	pkg.AddFunction("IsAbs", path.IsAbs, "", direct_path_IsAbs)
	pkg.AddFunction("Join", path.Join, "", direct_path_Join)
	pkg.AddFunction("Match", path.Match, "", direct_path_Match)
	pkg.AddFunction("Split", path.Split, "", direct_path_Split)

	// Variables
	pkg.AddVariable("ErrBadPattern", &path.ErrBadPattern, "")

}

func direct_path_Base(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path.Base(a0)))
}

func direct_path_Clean(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path.Clean(a0)))
}

func direct_path_Dir(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path.Dir(a0)))
}

func direct_path_Ext(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path.Ext(a0)))
}

func direct_path_IsAbs(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(path.IsAbs(a0))
}

func direct_path_Join(args []value.Value) value.Value {
	varArgs := make([]string, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].String()
	}
	return value.MakeString(string(path.Join(varArgs...)))
}

func direct_path_Match(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	r0, r1 := path.Match(a0, a1)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_path_Split(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := path.Split(a0)
	return value.FromInterface([]interface{}{r0, r1})
}
