// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"reflect"
	regexp_syntax "regexp/syntax"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("regexp/syntax", "syntax")

	// Functions
	pkg.AddFunction("Compile", regexp_syntax.Compile, "", direct_regexp_syntax_Compile)
	pkg.AddFunction("EmptyOpContext", regexp_syntax.EmptyOpContext, "", direct_regexp_syntax_EmptyOpContext)
	pkg.AddFunction("IsWordChar", regexp_syntax.IsWordChar, "", direct_regexp_syntax_IsWordChar)
	pkg.AddFunction("Parse", regexp_syntax.Parse, "", direct_regexp_syntax_Parse)

	// Constants
	pkg.AddConstant("ClassNL", regexp_syntax.ClassNL, "")
	pkg.AddConstant("DotNL", regexp_syntax.DotNL, "")
	pkg.AddConstant("EmptyBeginLine", regexp_syntax.EmptyBeginLine, "")
	pkg.AddConstant("EmptyBeginText", regexp_syntax.EmptyBeginText, "")
	pkg.AddConstant("EmptyEndLine", regexp_syntax.EmptyEndLine, "")
	pkg.AddConstant("EmptyEndText", regexp_syntax.EmptyEndText, "")
	pkg.AddConstant("EmptyNoWordBoundary", regexp_syntax.EmptyNoWordBoundary, "")
	pkg.AddConstant("EmptyWordBoundary", regexp_syntax.EmptyWordBoundary, "")
	pkg.AddConstant("ErrInternalError", regexp_syntax.ErrInternalError, "")
	pkg.AddConstant("ErrInvalidCharClass", regexp_syntax.ErrInvalidCharClass, "")
	pkg.AddConstant("ErrInvalidCharRange", regexp_syntax.ErrInvalidCharRange, "")
	pkg.AddConstant("ErrInvalidEscape", regexp_syntax.ErrInvalidEscape, "")
	pkg.AddConstant("ErrInvalidNamedCapture", regexp_syntax.ErrInvalidNamedCapture, "")
	pkg.AddConstant("ErrInvalidPerlOp", regexp_syntax.ErrInvalidPerlOp, "")
	pkg.AddConstant("ErrInvalidRepeatOp", regexp_syntax.ErrInvalidRepeatOp, "")
	pkg.AddConstant("ErrInvalidRepeatSize", regexp_syntax.ErrInvalidRepeatSize, "")
	pkg.AddConstant("ErrInvalidUTF8", regexp_syntax.ErrInvalidUTF8, "")
	pkg.AddConstant("ErrLarge", regexp_syntax.ErrLarge, "")
	pkg.AddConstant("ErrMissingBracket", regexp_syntax.ErrMissingBracket, "")
	pkg.AddConstant("ErrMissingParen", regexp_syntax.ErrMissingParen, "")
	pkg.AddConstant("ErrMissingRepeatArgument", regexp_syntax.ErrMissingRepeatArgument, "")
	pkg.AddConstant("ErrNestingDepth", regexp_syntax.ErrNestingDepth, "")
	pkg.AddConstant("ErrTrailingBackslash", regexp_syntax.ErrTrailingBackslash, "")
	pkg.AddConstant("ErrUnexpectedParen", regexp_syntax.ErrUnexpectedParen, "")
	pkg.AddConstant("FoldCase", regexp_syntax.FoldCase, "")
	pkg.AddConstant("InstAlt", regexp_syntax.InstAlt, "")
	pkg.AddConstant("InstAltMatch", regexp_syntax.InstAltMatch, "")
	pkg.AddConstant("InstCapture", regexp_syntax.InstCapture, "")
	pkg.AddConstant("InstEmptyWidth", regexp_syntax.InstEmptyWidth, "")
	pkg.AddConstant("InstFail", regexp_syntax.InstFail, "")
	pkg.AddConstant("InstMatch", regexp_syntax.InstMatch, "")
	pkg.AddConstant("InstNop", regexp_syntax.InstNop, "")
	pkg.AddConstant("InstRune", regexp_syntax.InstRune, "")
	pkg.AddConstant("InstRune1", regexp_syntax.InstRune1, "")
	pkg.AddConstant("InstRuneAny", regexp_syntax.InstRuneAny, "")
	pkg.AddConstant("InstRuneAnyNotNL", regexp_syntax.InstRuneAnyNotNL, "")
	pkg.AddConstant("Literal", regexp_syntax.Literal, "")
	pkg.AddConstant("MatchNL", regexp_syntax.MatchNL, "")
	pkg.AddConstant("NonGreedy", regexp_syntax.NonGreedy, "")
	pkg.AddConstant("OneLine", regexp_syntax.OneLine, "")
	pkg.AddConstant("OpAlternate", regexp_syntax.OpAlternate, "")
	pkg.AddConstant("OpAnyChar", regexp_syntax.OpAnyChar, "")
	pkg.AddConstant("OpAnyCharNotNL", regexp_syntax.OpAnyCharNotNL, "")
	pkg.AddConstant("OpBeginLine", regexp_syntax.OpBeginLine, "")
	pkg.AddConstant("OpBeginText", regexp_syntax.OpBeginText, "")
	pkg.AddConstant("OpCapture", regexp_syntax.OpCapture, "")
	pkg.AddConstant("OpCharClass", regexp_syntax.OpCharClass, "")
	pkg.AddConstant("OpConcat", regexp_syntax.OpConcat, "")
	pkg.AddConstant("OpEmptyMatch", regexp_syntax.OpEmptyMatch, "")
	pkg.AddConstant("OpEndLine", regexp_syntax.OpEndLine, "")
	pkg.AddConstant("OpEndText", regexp_syntax.OpEndText, "")
	pkg.AddConstant("OpLiteral", regexp_syntax.OpLiteral, "")
	pkg.AddConstant("OpNoMatch", regexp_syntax.OpNoMatch, "")
	pkg.AddConstant("OpNoWordBoundary", regexp_syntax.OpNoWordBoundary, "")
	pkg.AddConstant("OpPlus", regexp_syntax.OpPlus, "")
	pkg.AddConstant("OpQuest", regexp_syntax.OpQuest, "")
	pkg.AddConstant("OpRepeat", regexp_syntax.OpRepeat, "")
	pkg.AddConstant("OpStar", regexp_syntax.OpStar, "")
	pkg.AddConstant("OpWordBoundary", regexp_syntax.OpWordBoundary, "")
	pkg.AddConstant("POSIX", regexp_syntax.POSIX, "")
	pkg.AddConstant("Perl", regexp_syntax.Perl, "")
	pkg.AddConstant("PerlX", regexp_syntax.PerlX, "")
	pkg.AddConstant("Simple", regexp_syntax.Simple, "")
	pkg.AddConstant("UnicodeGroups", regexp_syntax.UnicodeGroups, "")
	pkg.AddConstant("WasDollar", regexp_syntax.WasDollar, "")

	// Types
	pkg.AddType("EmptyOp", reflect.TypeOf((*regexp_syntax.EmptyOp)(nil)).Elem(), "")
	pkg.AddType("Error", reflect.TypeOf(regexp_syntax.Error{}), "")
	pkg.AddType("ErrorCode", reflect.TypeOf((*regexp_syntax.ErrorCode)(nil)).Elem(), "")
	pkg.AddType("Flags", reflect.TypeOf((*regexp_syntax.Flags)(nil)).Elem(), "")
	pkg.AddType("Inst", reflect.TypeOf(regexp_syntax.Inst{}), "")
	pkg.AddType("InstOp", reflect.TypeOf((*regexp_syntax.InstOp)(nil)).Elem(), "")
	pkg.AddType("Op", reflect.TypeOf((*regexp_syntax.Op)(nil)).Elem(), "")
	pkg.AddType("Prog", reflect.TypeOf(regexp_syntax.Prog{}), "")
	pkg.AddType("Regexp", reflect.TypeOf(regexp_syntax.Regexp{}), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("Error", "Error", direct_method_regexp_syntax_Error_Error)
	pkg.AddMethodDirectCall("ErrorCode", "String", direct_method_regexp_syntax_ErrorCode_String)
	pkg.AddMethodDirectCall("Inst", "MatchEmptyWidth", direct_method_regexp_syntax_Inst_MatchEmptyWidth)
	pkg.AddMethodDirectCall("Inst", "MatchRune", direct_method_regexp_syntax_Inst_MatchRune)
	pkg.AddMethodDirectCall("Inst", "MatchRunePos", direct_method_regexp_syntax_Inst_MatchRunePos)
	pkg.AddMethodDirectCall("Inst", "String", direct_method_regexp_syntax_Inst_String)
	pkg.AddMethodDirectCall("InstOp", "String", direct_method_regexp_syntax_InstOp_String)
	pkg.AddMethodDirectCall("Op", "String", direct_method_regexp_syntax_Op_String)
	pkg.AddMethodDirectCall("Prog", "Prefix", direct_method_regexp_syntax_Prog_Prefix)
	pkg.AddMethodDirectCall("Prog", "StartCond", direct_method_regexp_syntax_Prog_StartCond)
	pkg.AddMethodDirectCall("Prog", "String", direct_method_regexp_syntax_Prog_String)
	pkg.AddMethodDirectCall("Regexp", "CapNames", direct_method_regexp_syntax_Regexp_CapNames)
	pkg.AddMethodDirectCall("Regexp", "Equal", direct_method_regexp_syntax_Regexp_Equal)
	pkg.AddMethodDirectCall("Regexp", "MaxCap", direct_method_regexp_syntax_Regexp_MaxCap)
	pkg.AddMethodDirectCall("Regexp", "Simplify", direct_method_regexp_syntax_Regexp_Simplify)
	pkg.AddMethodDirectCall("Regexp", "String", direct_method_regexp_syntax_Regexp_String)

}

func direct_regexp_syntax_Compile(args []value.Value) value.Value {
	a0 := args[0].Interface().(*regexp_syntax.Regexp)
	r0, r1 := regexp_syntax.Compile(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_regexp_syntax_EmptyOpContext(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	a1 := int32(args[1].Int())
	return value.MakeUint(uint64(uint8(regexp_syntax.EmptyOpContext(a0, a1))))
}

func direct_regexp_syntax_IsWordChar(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeBool(regexp_syntax.IsWordChar(a0))
}

func direct_regexp_syntax_Parse(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := regexp_syntax.Flags(uint16(args[1].Uint()))
	r0, r1 := regexp_syntax.Parse(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_regexp_syntax_Error_Error(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Error)
	return value.MakeString(string(recv.Error()))
}

func direct_method_regexp_syntax_ErrorCode_String(args []value.Value) value.Value {
	recv := regexp_syntax.ErrorCode(args[0].String())
	return value.MakeString(string(recv.String()))
}

func direct_method_regexp_syntax_Inst_MatchEmptyWidth(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Inst)
	a0 := int32(args[1].Int())
	a1 := int32(args[2].Int())
	return value.MakeBool(recv.MatchEmptyWidth(a0, a1))
}

func direct_method_regexp_syntax_Inst_MatchRune(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Inst)
	a0 := int32(args[1].Int())
	return value.MakeBool(recv.MatchRune(a0))
}

func direct_method_regexp_syntax_Inst_MatchRunePos(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Inst)
	a0 := int32(args[1].Int())
	return value.MakeInt(int64(recv.MatchRunePos(a0)))
}

func direct_method_regexp_syntax_Inst_String(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Inst)
	return value.MakeString(string(recv.String()))
}

func direct_method_regexp_syntax_InstOp_String(args []value.Value) value.Value {
	recv := regexp_syntax.InstOp(byte(args[0].Uint()))
	return value.MakeString(string(recv.String()))
}

func direct_method_regexp_syntax_Op_String(args []value.Value) value.Value {
	recv := regexp_syntax.Op(byte(args[0].Uint()))
	return value.MakeString(string(recv.String()))
}

func direct_method_regexp_syntax_Prog_Prefix(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Prog)
	r0, r1 := recv.Prefix()
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.MakeBool(r1)})
}

func direct_method_regexp_syntax_Prog_StartCond(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Prog)
	return value.MakeUint(uint64(uint8(recv.StartCond())))
}

func direct_method_regexp_syntax_Prog_String(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Prog)
	return value.MakeString(string(recv.String()))
}

func direct_method_regexp_syntax_Regexp_CapNames(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Regexp)
	return value.FromInterface(recv.CapNames())
}

func direct_method_regexp_syntax_Regexp_Equal(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Regexp)
	a0 := args[1].Interface().(*regexp_syntax.Regexp)
	return value.MakeBool(recv.Equal(a0))
}

func direct_method_regexp_syntax_Regexp_MaxCap(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Regexp)
	return value.MakeInt(int64(recv.MaxCap()))
}

func direct_method_regexp_syntax_Regexp_Simplify(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Regexp)
	return value.FromInterface(recv.Simplify())
}

func direct_method_regexp_syntax_Regexp_String(args []value.Value) value.Value {
	recv := args[0].Interface().(*regexp_syntax.Regexp)
	return value.MakeString(string(recv.String()))
}
