// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"reflect"
	"sort"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("sort", "sort")

	// Functions
	pkg.AddFunction("Find", sort.Find, "")
	pkg.AddFunction("Float64s", sort.Float64s, "")
	pkg.AddFunction("Float64sAreSorted", sort.Float64sAreSorted, "")
	pkg.AddFunction("Ints", sort.Ints, "")
	pkg.AddFunction("IntsAreSorted", sort.IntsAreSorted, "")
	pkg.AddFunction("IsSorted", sort.IsSorted, "")
	pkg.AddFunction("Reverse", sort.Reverse, "")
	pkg.AddFunction("Search", sort.Search, "")
	pkg.AddFunction("SearchFloat64s", sort.SearchFloat64s, "")
	pkg.AddFunction("SearchInts", sort.SearchInts, "")
	pkg.AddFunction("SearchStrings", sort.SearchStrings, "")
	pkg.AddFunction("Slice", sort.Slice, "")
	pkg.AddFunction("SliceIsSorted", sort.SliceIsSorted, "")
	pkg.AddFunction("SliceStable", sort.SliceStable, "")
	pkg.AddFunction("Sort", sort.Sort, "")
	pkg.AddFunction("Stable", sort.Stable, "")
	pkg.AddFunction("Strings", sort.Strings, "")
	pkg.AddFunction("StringsAreSorted", sort.StringsAreSorted, "")

	// Types
	pkg.AddType("Float64Slice", reflect.TypeOf((*sort.Float64Slice)(nil)).Elem(), "")
	pkg.AddType("IntSlice", reflect.TypeOf((*sort.IntSlice)(nil)).Elem(), "")
	pkg.AddType("Interface", reflect.TypeOf((*sort.Interface)(nil)).Elem(), "")
	pkg.AddType("StringSlice", reflect.TypeOf((*sort.StringSlice)(nil)).Elem(), "")

}
