// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	unicode_utf8 "unicode/utf8"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("unicode/utf8", "utf8")

	// Functions
	pkg.AddFunction("AppendRune", unicode_utf8.AppendRune, "")
	pkg.AddFunction("DecodeLastRune", unicode_utf8.DecodeLastRune, "")
	pkg.AddFunction("DecodeLastRuneInString", unicode_utf8.DecodeLastRuneInString, "")
	pkg.AddFunction("DecodeRune", unicode_utf8.DecodeRune, "")
	pkg.AddFunction("DecodeRuneInString", unicode_utf8.DecodeRuneInString, "")
	pkg.AddFunction("EncodeRune", unicode_utf8.EncodeRune, "")
	pkg.AddFunction("FullRune", unicode_utf8.FullRune, "")
	pkg.AddFunction("FullRuneInString", unicode_utf8.FullRuneInString, "")
	pkg.AddFunction("RuneCount", unicode_utf8.RuneCount, "")
	pkg.AddFunction("RuneCountInString", unicode_utf8.RuneCountInString, "")
	pkg.AddFunction("RuneLen", unicode_utf8.RuneLen, "")
	pkg.AddFunction("RuneStart", unicode_utf8.RuneStart, "")
	pkg.AddFunction("Valid", unicode_utf8.Valid, "")
	pkg.AddFunction("ValidRune", unicode_utf8.ValidRune, "")
	pkg.AddFunction("ValidString", unicode_utf8.ValidString, "")

	// Constants
	pkg.AddConstant("MaxRune", unicode_utf8.MaxRune, "")
	pkg.AddConstant("RuneError", unicode_utf8.RuneError, "")
	pkg.AddConstant("RuneSelf", unicode_utf8.RuneSelf, "")
	pkg.AddConstant("UTFMax", unicode_utf8.UTFMax, "")

}
