// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"log"
	"reflect"

	"git.woa.com/youngjin/gig/importer"
	"git.woa.com/youngjin/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("log", "log")

	// Functions
	pkg.AddFunction("Default", log.Default, "", direct_log_Default)
	pkg.AddFunction("Fatal", log.Fatal, "", direct_log_Fatal)
	pkg.AddFunction("Fatalf", log.Fatalf, "", direct_log_Fatalf)
	pkg.AddFunction("Fatalln", log.Fatalln, "", direct_log_Fatalln)
	pkg.AddFunction("Flags", log.Flags, "", direct_log_Flags)
	pkg.AddFunction("New", log.New, "", nil)
	pkg.AddFunction("Output", log.Output, "", direct_log_Output)
	pkg.AddFunction("Panic", log.Panic, "", direct_log_Panic)
	pkg.AddFunction("Panicf", log.Panicf, "", direct_log_Panicf)
	pkg.AddFunction("Panicln", log.Panicln, "", direct_log_Panicln)
	pkg.AddFunction("Prefix", log.Prefix, "", direct_log_Prefix)
	pkg.AddFunction("Print", log.Print, "", direct_log_Print)
	pkg.AddFunction("Printf", log.Printf, "", direct_log_Printf)
	pkg.AddFunction("Println", log.Println, "", direct_log_Println)
	pkg.AddFunction("SetFlags", log.SetFlags, "", direct_log_SetFlags)
	pkg.AddFunction("SetOutput", log.SetOutput, "", nil)
	pkg.AddFunction("SetPrefix", log.SetPrefix, "", direct_log_SetPrefix)
	pkg.AddFunction("Writer", log.Writer, "", direct_log_Writer)

	// Constants
	pkg.AddConstant("LUTC", log.LUTC, "")
	pkg.AddConstant("Ldate", log.Ldate, "")
	pkg.AddConstant("Llongfile", log.Llongfile, "")
	pkg.AddConstant("Lmicroseconds", log.Lmicroseconds, "")
	pkg.AddConstant("Lmsgprefix", log.Lmsgprefix, "")
	pkg.AddConstant("Lshortfile", log.Lshortfile, "")
	pkg.AddConstant("LstdFlags", log.LstdFlags, "")
	pkg.AddConstant("Ltime", log.Ltime, "")

	// Types
	pkg.AddType("Logger", reflect.TypeOf(log.Logger{}), "")

}

func direct_log_Default(args []value.Value) value.Value {
	return value.FromInterface(log.Default())
}

func direct_log_Fatal(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	log.Fatal(varArgs...)
	return value.MakeNil()
}

func direct_log_Fatalf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	log.Fatalf(a0, varArgs...)
	return value.MakeNil()
}

func direct_log_Fatalln(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	log.Fatalln(varArgs...)
	return value.MakeNil()
}

func direct_log_Flags(args []value.Value) value.Value {
	return value.MakeInt(int64(log.Flags()))
}

func direct_log_Output(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	a1 := args[1].String()
	return value.FromInterface(log.Output(a0, a1))
}

func direct_log_Panic(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	log.Panic(varArgs...)
	return value.MakeNil()
}

func direct_log_Panicf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	log.Panicf(a0, varArgs...)
	return value.MakeNil()
}

func direct_log_Panicln(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	log.Panicln(varArgs...)
	return value.MakeNil()
}

func direct_log_Prefix(args []value.Value) value.Value {
	return value.MakeString(string(log.Prefix()))
}

func direct_log_Print(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	log.Print(varArgs...)
	return value.MakeNil()
}

func direct_log_Printf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	log.Printf(a0, varArgs...)
	return value.MakeNil()
}

func direct_log_Println(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	log.Println(varArgs...)
	return value.MakeNil()
}

func direct_log_SetFlags(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	log.SetFlags(a0)
	return value.MakeNil()
}

func direct_log_SetPrefix(args []value.Value) value.Value {
	a0 := args[0].String()
	log.SetPrefix(a0)
	return value.MakeNil()
}

func direct_log_Writer(args []value.Value) value.Value {
	return value.FromInterface(log.Writer())
}
