// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	math_rand_v2 "math/rand/v2"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("math/rand/v2", "rand")

	// Functions
	pkg.AddFunction("ExpFloat64", math_rand_v2.ExpFloat64, "")
	pkg.AddFunction("Float32", math_rand_v2.Float32, "")
	pkg.AddFunction("Float64", math_rand_v2.Float64, "")
	pkg.AddFunction("Int", math_rand_v2.Int, "")
	pkg.AddFunction("Int32", math_rand_v2.Int32, "")
	pkg.AddFunction("Int32N", math_rand_v2.Int32N, "")
	pkg.AddFunction("Int64", math_rand_v2.Int64, "")
	pkg.AddFunction("Int64N", math_rand_v2.Int64N, "")
	pkg.AddFunction("IntN", math_rand_v2.IntN, "")
	pkg.AddFunction("New", math_rand_v2.New, "")
	pkg.AddFunction("NewChaCha8", math_rand_v2.NewChaCha8, "")
	pkg.AddFunction("NewPCG", math_rand_v2.NewPCG, "")
	pkg.AddFunction("NewZipf", math_rand_v2.NewZipf, "")
	pkg.AddFunction("NormFloat64", math_rand_v2.NormFloat64, "")
	pkg.AddFunction("Perm", math_rand_v2.Perm, "")
	pkg.AddFunction("Shuffle", math_rand_v2.Shuffle, "")
	pkg.AddFunction("Uint", math_rand_v2.Uint, "")
	pkg.AddFunction("Uint32", math_rand_v2.Uint32, "")
	pkg.AddFunction("Uint32N", math_rand_v2.Uint32N, "")
	pkg.AddFunction("Uint64", math_rand_v2.Uint64, "")
	pkg.AddFunction("Uint64N", math_rand_v2.Uint64N, "")
	pkg.AddFunction("UintN", math_rand_v2.UintN, "")

	// Types
	pkg.AddType("ChaCha8", reflect.TypeOf(math_rand_v2.ChaCha8{}), "")
	pkg.AddType("PCG", reflect.TypeOf(math_rand_v2.PCG{}), "")
	pkg.AddType("Rand", reflect.TypeOf(math_rand_v2.Rand{}), "")
	pkg.AddType("Source", reflect.TypeOf((*math_rand_v2.Source)(nil)).Elem(), "")
	pkg.AddType("Zipf", reflect.TypeOf(math_rand_v2.Zipf{}), "")

}
