// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"path"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("path", "path")

	// Functions
	pkg.AddFunction("Base", path.Base, "")
	pkg.AddFunction("Clean", path.Clean, "")
	pkg.AddFunction("Dir", path.Dir, "")
	pkg.AddFunction("Ext", path.Ext, "")
	pkg.AddFunction("IsAbs", path.IsAbs, "")
	pkg.AddFunction("Join", path.Join, "")
	pkg.AddFunction("Match", path.Match, "")
	pkg.AddFunction("Split", path.Split, "")

	// Variables
	pkg.AddVariable("ErrBadPattern", &path.ErrBadPattern, "")

}
