// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"reflect"
	"strconv"

	"git.woa.com/youngjin/gig/importer"
	"git.woa.com/youngjin/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("strconv", "strconv")

	// Functions
	pkg.AddFunction("AppendBool", strconv.AppendBool, "", direct_strconv_AppendBool)
	pkg.AddFunction("AppendFloat", strconv.AppendFloat, "", direct_strconv_AppendFloat)
	pkg.AddFunction("AppendInt", strconv.AppendInt, "", direct_strconv_AppendInt)
	pkg.AddFunction("AppendQuote", strconv.AppendQuote, "", direct_strconv_AppendQuote)
	pkg.AddFunction("AppendQuoteRune", strconv.AppendQuoteRune, "", direct_strconv_AppendQuoteRune)
	pkg.AddFunction("AppendQuoteRuneToASCII", strconv.AppendQuoteRuneToASCII, "", direct_strconv_AppendQuoteRuneToASCII)
	pkg.AddFunction("AppendQuoteRuneToGraphic", strconv.AppendQuoteRuneToGraphic, "", direct_strconv_AppendQuoteRuneToGraphic)
	pkg.AddFunction("AppendQuoteToASCII", strconv.AppendQuoteToASCII, "", direct_strconv_AppendQuoteToASCII)
	pkg.AddFunction("AppendQuoteToGraphic", strconv.AppendQuoteToGraphic, "", direct_strconv_AppendQuoteToGraphic)
	pkg.AddFunction("AppendUint", strconv.AppendUint, "", direct_strconv_AppendUint)
	pkg.AddFunction("Atoi", strconv.Atoi, "", direct_strconv_Atoi)
	pkg.AddFunction("CanBackquote", strconv.CanBackquote, "", direct_strconv_CanBackquote)
	pkg.AddFunction("FormatBool", strconv.FormatBool, "", direct_strconv_FormatBool)
	pkg.AddFunction("FormatComplex", strconv.FormatComplex, "", direct_strconv_FormatComplex)
	pkg.AddFunction("FormatFloat", strconv.FormatFloat, "", direct_strconv_FormatFloat)
	pkg.AddFunction("FormatInt", strconv.FormatInt, "", direct_strconv_FormatInt)
	pkg.AddFunction("FormatUint", strconv.FormatUint, "", direct_strconv_FormatUint)
	pkg.AddFunction("IsGraphic", strconv.IsGraphic, "", direct_strconv_IsGraphic)
	pkg.AddFunction("IsPrint", strconv.IsPrint, "", direct_strconv_IsPrint)
	pkg.AddFunction("Itoa", strconv.Itoa, "", direct_strconv_Itoa)
	pkg.AddFunction("ParseBool", strconv.ParseBool, "", direct_strconv_ParseBool)
	pkg.AddFunction("ParseComplex", strconv.ParseComplex, "", direct_strconv_ParseComplex)
	pkg.AddFunction("ParseFloat", strconv.ParseFloat, "", direct_strconv_ParseFloat)
	pkg.AddFunction("ParseInt", strconv.ParseInt, "", direct_strconv_ParseInt)
	pkg.AddFunction("ParseUint", strconv.ParseUint, "", direct_strconv_ParseUint)
	pkg.AddFunction("Quote", strconv.Quote, "", direct_strconv_Quote)
	pkg.AddFunction("QuoteRune", strconv.QuoteRune, "", direct_strconv_QuoteRune)
	pkg.AddFunction("QuoteRuneToASCII", strconv.QuoteRuneToASCII, "", direct_strconv_QuoteRuneToASCII)
	pkg.AddFunction("QuoteRuneToGraphic", strconv.QuoteRuneToGraphic, "", direct_strconv_QuoteRuneToGraphic)
	pkg.AddFunction("QuoteToASCII", strconv.QuoteToASCII, "", direct_strconv_QuoteToASCII)
	pkg.AddFunction("QuoteToGraphic", strconv.QuoteToGraphic, "", direct_strconv_QuoteToGraphic)
	pkg.AddFunction("QuotedPrefix", strconv.QuotedPrefix, "", direct_strconv_QuotedPrefix)
	pkg.AddFunction("Unquote", strconv.Unquote, "", direct_strconv_Unquote)
	pkg.AddFunction("UnquoteChar", strconv.UnquoteChar, "", direct_strconv_UnquoteChar)

	// Constants
	pkg.AddConstant("IntSize", strconv.IntSize, "")

	// Variables
	pkg.AddVariable("ErrRange", &strconv.ErrRange, "")
	pkg.AddVariable("ErrSyntax", &strconv.ErrSyntax, "")

	// Types
	pkg.AddType("NumError", reflect.TypeOf(strconv.NumError{}), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("NumError", "Error", direct_method_strconv_NumError_Error)
	pkg.AddMethodDirectCall("NumError", "Unwrap", direct_method_strconv_NumError_Unwrap)

}

func direct_strconv_AppendBool(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := args[1].Bool()
	return value.MakeBytes([]byte(strconv.AppendBool(a0, a1)))
}

func direct_strconv_AppendFloat(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := args[1].Float()
	a2 := byte(args[2].Uint())
	a3 := int(args[3].Int())
	a4 := int(args[4].Int())
	return value.MakeBytes([]byte(strconv.AppendFloat(a0, a1, a2, a3, a4)))
}

func direct_strconv_AppendInt(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := args[1].Int()
	a2 := int(args[2].Int())
	return value.MakeBytes([]byte(strconv.AppendInt(a0, a1, a2)))
}

func direct_strconv_AppendQuote(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := args[1].String()
	return value.MakeBytes([]byte(strconv.AppendQuote(a0, a1)))
}

func direct_strconv_AppendQuoteRune(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := int32(args[1].Int())
	return value.MakeBytes([]byte(strconv.AppendQuoteRune(a0, a1)))
}

func direct_strconv_AppendQuoteRuneToASCII(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := int32(args[1].Int())
	return value.MakeBytes([]byte(strconv.AppendQuoteRuneToASCII(a0, a1)))
}

func direct_strconv_AppendQuoteRuneToGraphic(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := int32(args[1].Int())
	return value.MakeBytes([]byte(strconv.AppendQuoteRuneToGraphic(a0, a1)))
}

func direct_strconv_AppendQuoteToASCII(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := args[1].String()
	return value.MakeBytes([]byte(strconv.AppendQuoteToASCII(a0, a1)))
}

func direct_strconv_AppendQuoteToGraphic(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := args[1].String()
	return value.MakeBytes([]byte(strconv.AppendQuoteToGraphic(a0, a1)))
}

func direct_strconv_AppendUint(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		return (args[0]).Interface().([]byte)
	}()
	a1 := args[1].Uint()
	a2 := int(args[2].Int())
	return value.MakeBytes([]byte(strconv.AppendUint(a0, a1, a2)))
}

func direct_strconv_Atoi(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := strconv.Atoi(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_strconv_CanBackquote(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(strconv.CanBackquote(a0))
}

func direct_strconv_FormatBool(args []value.Value) value.Value {
	a0 := args[0].Bool()
	return value.MakeString(string(strconv.FormatBool(a0)))
}

func direct_strconv_FormatComplex(args []value.Value) value.Value {
	a0 := args[0].Complex()
	a1 := byte(args[1].Uint())
	a2 := int(args[2].Int())
	a3 := int(args[3].Int())
	return value.MakeString(string(strconv.FormatComplex(a0, a1, a2, a3)))
}

func direct_strconv_FormatFloat(args []value.Value) value.Value {
	a0 := args[0].Float()
	a1 := byte(args[1].Uint())
	a2 := int(args[2].Int())
	a3 := int(args[3].Int())
	return value.MakeString(string(strconv.FormatFloat(a0, a1, a2, a3)))
}

func direct_strconv_FormatInt(args []value.Value) value.Value {
	a0 := args[0].Int()
	a1 := int(args[1].Int())
	return value.MakeString(string(strconv.FormatInt(a0, a1)))
}

func direct_strconv_FormatUint(args []value.Value) value.Value {
	a0 := args[0].Uint()
	a1 := int(args[1].Int())
	return value.MakeString(string(strconv.FormatUint(a0, a1)))
}

func direct_strconv_IsGraphic(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeBool(strconv.IsGraphic(a0))
}

func direct_strconv_IsPrint(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeBool(strconv.IsPrint(a0))
}

func direct_strconv_Itoa(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	return value.MakeString(string(strconv.Itoa(a0)))
}

func direct_strconv_ParseBool(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := strconv.ParseBool(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBool(r0), value.FromInterface(r1)})
}

func direct_strconv_ParseComplex(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	r0, r1 := strconv.ParseComplex(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_strconv_ParseFloat(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	r0, r1 := strconv.ParseFloat(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeFloat(float64(r0)), value.FromInterface(r1)})
}

func direct_strconv_ParseInt(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	a2 := int(args[2].Int())
	r0, r1 := strconv.ParseInt(a0, a1, a2)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.FromInterface(r1)})
}

func direct_strconv_ParseUint(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	a2 := int(args[2].Int())
	r0, r1 := strconv.ParseUint(a0, a1, a2)
	return value.MakeValueSlice([]value.Value{value.MakeUint(uint64(r0)), value.FromInterface(r1)})
}

func direct_strconv_Quote(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strconv.Quote(a0)))
}

func direct_strconv_QuoteRune(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeString(string(strconv.QuoteRune(a0)))
}

func direct_strconv_QuoteRuneToASCII(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeString(string(strconv.QuoteRuneToASCII(a0)))
}

func direct_strconv_QuoteRuneToGraphic(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeString(string(strconv.QuoteRuneToGraphic(a0)))
}

func direct_strconv_QuoteToASCII(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strconv.QuoteToASCII(a0)))
}

func direct_strconv_QuoteToGraphic(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strconv.QuoteToGraphic(a0)))
}

func direct_strconv_QuotedPrefix(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := strconv.QuotedPrefix(a0)
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_strconv_Unquote(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := strconv.Unquote(a0)
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_strconv_UnquoteChar(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := byte(args[1].Uint())
	r0, r1, r2, r3 := strconv.UnquoteChar(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeInt(int64(r0)), value.MakeBool(r1), value.MakeString(string(r2)), value.FromInterface(r3)})
}

func direct_method_strconv_NumError_Error(args []value.Value) value.Value {
	recv := args[0].Interface().(*strconv.NumError)
	return value.MakeString(string(recv.Error()))
}

func direct_method_strconv_NumError_Unwrap(args []value.Value) value.Value {
	recv := args[0].Interface().(*strconv.NumError)
	return value.FromInterface(recv.Unwrap())
}
