// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"reflect"
	"strings"

	"git.woa.com/youngjin/gig/importer"
	"git.woa.com/youngjin/gig/value"
)

func init() {
	pkg := importer.RegisterPackage("strings", "strings")

	// Functions
	pkg.AddFunction("Clone", strings.Clone, "", direct_strings_Clone)
	pkg.AddFunction("Compare", strings.Compare, "", direct_strings_Compare)
	pkg.AddFunction("Contains", strings.Contains, "", direct_strings_Contains)
	pkg.AddFunction("ContainsAny", strings.ContainsAny, "", direct_strings_ContainsAny)
	pkg.AddFunction("ContainsFunc", strings.ContainsFunc, "", nil)
	pkg.AddFunction("ContainsRune", strings.ContainsRune, "", direct_strings_ContainsRune)
	pkg.AddFunction("Count", strings.Count, "", direct_strings_Count)
	pkg.AddFunction("Cut", strings.Cut, "", direct_strings_Cut)
	pkg.AddFunction("CutPrefix", strings.CutPrefix, "", direct_strings_CutPrefix)
	pkg.AddFunction("CutSuffix", strings.CutSuffix, "", direct_strings_CutSuffix)
	pkg.AddFunction("EqualFold", strings.EqualFold, "", direct_strings_EqualFold)
	pkg.AddFunction("Fields", strings.Fields, "", direct_strings_Fields)
	pkg.AddFunction("FieldsFunc", strings.FieldsFunc, "", nil)
	pkg.AddFunction("HasPrefix", strings.HasPrefix, "", direct_strings_HasPrefix)
	pkg.AddFunction("HasSuffix", strings.HasSuffix, "", direct_strings_HasSuffix)
	pkg.AddFunction("Index", strings.Index, "", direct_strings_Index)
	pkg.AddFunction("IndexAny", strings.IndexAny, "", direct_strings_IndexAny)
	pkg.AddFunction("IndexByte", strings.IndexByte, "", direct_strings_IndexByte)
	pkg.AddFunction("IndexFunc", strings.IndexFunc, "", nil)
	pkg.AddFunction("IndexRune", strings.IndexRune, "", direct_strings_IndexRune)
	pkg.AddFunction("Join", strings.Join, "", direct_strings_Join)
	pkg.AddFunction("LastIndex", strings.LastIndex, "", direct_strings_LastIndex)
	pkg.AddFunction("LastIndexAny", strings.LastIndexAny, "", direct_strings_LastIndexAny)
	pkg.AddFunction("LastIndexByte", strings.LastIndexByte, "", direct_strings_LastIndexByte)
	pkg.AddFunction("LastIndexFunc", strings.LastIndexFunc, "", nil)
	pkg.AddFunction("Map", strings.Map, "", nil)
	pkg.AddFunction("NewReader", strings.NewReader, "", direct_strings_NewReader)
	pkg.AddFunction("NewReplacer", strings.NewReplacer, "", direct_strings_NewReplacer)
	pkg.AddFunction("Repeat", strings.Repeat, "", direct_strings_Repeat)
	pkg.AddFunction("Replace", strings.Replace, "", direct_strings_Replace)
	pkg.AddFunction("ReplaceAll", strings.ReplaceAll, "", direct_strings_ReplaceAll)
	pkg.AddFunction("Split", strings.Split, "", direct_strings_Split)
	pkg.AddFunction("SplitAfter", strings.SplitAfter, "", direct_strings_SplitAfter)
	pkg.AddFunction("SplitAfterN", strings.SplitAfterN, "", direct_strings_SplitAfterN)
	pkg.AddFunction("SplitN", strings.SplitN, "", direct_strings_SplitN)
	pkg.AddFunction("Title", strings.Title, "", direct_strings_Title)
	pkg.AddFunction("ToLower", strings.ToLower, "", direct_strings_ToLower)
	pkg.AddFunction("ToLowerSpecial", strings.ToLowerSpecial, "", nil)
	pkg.AddFunction("ToTitle", strings.ToTitle, "", direct_strings_ToTitle)
	pkg.AddFunction("ToTitleSpecial", strings.ToTitleSpecial, "", nil)
	pkg.AddFunction("ToUpper", strings.ToUpper, "", direct_strings_ToUpper)
	pkg.AddFunction("ToUpperSpecial", strings.ToUpperSpecial, "", nil)
	pkg.AddFunction("ToValidUTF8", strings.ToValidUTF8, "", direct_strings_ToValidUTF8)
	pkg.AddFunction("Trim", strings.Trim, "", direct_strings_Trim)
	pkg.AddFunction("TrimFunc", strings.TrimFunc, "", nil)
	pkg.AddFunction("TrimLeft", strings.TrimLeft, "", direct_strings_TrimLeft)
	pkg.AddFunction("TrimLeftFunc", strings.TrimLeftFunc, "", nil)
	pkg.AddFunction("TrimPrefix", strings.TrimPrefix, "", direct_strings_TrimPrefix)
	pkg.AddFunction("TrimRight", strings.TrimRight, "", direct_strings_TrimRight)
	pkg.AddFunction("TrimRightFunc", strings.TrimRightFunc, "", nil)
	pkg.AddFunction("TrimSpace", strings.TrimSpace, "", direct_strings_TrimSpace)
	pkg.AddFunction("TrimSuffix", strings.TrimSuffix, "", direct_strings_TrimSuffix)

	// Types
	pkg.AddType("Builder", reflect.TypeOf(strings.Builder{}), "")
	pkg.AddType("Reader", reflect.TypeOf(strings.Reader{}), "")
	pkg.AddType("Replacer", reflect.TypeOf(strings.Replacer{}), "")

}

func direct_strings_Clone(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strings.Clone(a0)))
}

func direct_strings_Compare(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeInt(int64(strings.Compare(a0, a1)))
}

func direct_strings_Contains(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(strings.Contains(a0, a1))
}

func direct_strings_ContainsAny(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(strings.ContainsAny(a0, a1))
}

func direct_strings_ContainsRune(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int32(args[1].Int())
	return value.MakeBool(strings.ContainsRune(a0, a1))
}

func direct_strings_Count(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeInt(int64(strings.Count(a0, a1)))
}

func direct_strings_Cut(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	r0, r1, r2 := strings.Cut(a0, a1)
	return value.FromInterface([]interface{}{r0, r1, r2})
}

func direct_strings_CutPrefix(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	r0, r1 := strings.CutPrefix(a0, a1)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_strings_CutSuffix(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	r0, r1 := strings.CutSuffix(a0, a1)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_strings_EqualFold(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(strings.EqualFold(a0, a1))
}

func direct_strings_Fields(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(strings.Fields(a0))
}

func direct_strings_HasPrefix(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(strings.HasPrefix(a0, a1))
}

func direct_strings_HasSuffix(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(strings.HasSuffix(a0, a1))
}

func direct_strings_Index(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeInt(int64(strings.Index(a0, a1)))
}

func direct_strings_IndexAny(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeInt(int64(strings.IndexAny(a0, a1)))
}

func direct_strings_IndexByte(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := byte(args[1].Uint())
	return value.MakeInt(int64(strings.IndexByte(a0, a1)))
}

func direct_strings_IndexRune(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int32(args[1].Int())
	return value.MakeInt(int64(strings.IndexRune(a0, a1)))
}

func direct_strings_Join(args []value.Value) value.Value {
	a0 := args[0].Interface().([]string)
	a1 := args[1].String()
	return value.MakeString(string(strings.Join(a0, a1)))
}

func direct_strings_LastIndex(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeInt(int64(strings.LastIndex(a0, a1)))
}

func direct_strings_LastIndexAny(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeInt(int64(strings.LastIndexAny(a0, a1)))
}

func direct_strings_LastIndexByte(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := byte(args[1].Uint())
	return value.MakeInt(int64(strings.LastIndexByte(a0, a1)))
}

func direct_strings_NewReader(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(strings.NewReader(a0))
}

func direct_strings_NewReplacer(args []value.Value) value.Value {
	varArgs := make([]string, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].String()
	}
	return value.FromInterface(strings.NewReplacer(varArgs...))
}

func direct_strings_Repeat(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	return value.MakeString(string(strings.Repeat(a0, a1)))
}

func direct_strings_Replace(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	a2 := args[2].String()
	a3 := int(args[3].Int())
	return value.MakeString(string(strings.Replace(a0, a1, a2, a3)))
}

func direct_strings_ReplaceAll(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	a2 := args[2].String()
	return value.MakeString(string(strings.ReplaceAll(a0, a1, a2)))
}

func direct_strings_Split(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.FromInterface(strings.Split(a0, a1))
}

func direct_strings_SplitAfter(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.FromInterface(strings.SplitAfter(a0, a1))
}

func direct_strings_SplitAfterN(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	a2 := int(args[2].Int())
	return value.FromInterface(strings.SplitAfterN(a0, a1, a2))
}

func direct_strings_SplitN(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	a2 := int(args[2].Int())
	return value.FromInterface(strings.SplitN(a0, a1, a2))
}

func direct_strings_Title(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strings.Title(a0)))
}

func direct_strings_ToLower(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strings.ToLower(a0)))
}

func direct_strings_ToTitle(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strings.ToTitle(a0)))
}

func direct_strings_ToUpper(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strings.ToUpper(a0)))
}

func direct_strings_ToValidUTF8(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(strings.ToValidUTF8(a0, a1)))
}

func direct_strings_Trim(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(strings.Trim(a0, a1)))
}

func direct_strings_TrimLeft(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(strings.TrimLeft(a0, a1)))
}

func direct_strings_TrimPrefix(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(strings.TrimPrefix(a0, a1)))
}

func direct_strings_TrimRight(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(strings.TrimRight(a0, a1)))
}

func direct_strings_TrimSpace(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(strings.TrimSpace(a0)))
}

func direct_strings_TrimSuffix(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(strings.TrimSuffix(a0, a1)))
}
