// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	"reflect"
	text_template "text/template"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("text/template", "template")

	// Functions
	pkg.AddFunction("HTMLEscape", text_template.HTMLEscape, "")
	pkg.AddFunction("HTMLEscapeString", text_template.HTMLEscapeString, "")
	pkg.AddFunction("HTMLEscaper", text_template.HTMLEscaper, "")
	pkg.AddFunction("IsTrue", text_template.IsTrue, "")
	pkg.AddFunction("JSEscape", text_template.JSEscape, "")
	pkg.AddFunction("JSEscapeString", text_template.JSEscapeString, "")
	pkg.AddFunction("JSEscaper", text_template.JSEscaper, "")
	pkg.AddFunction("Must", text_template.Must, "")
	pkg.AddFunction("New", text_template.New, "")
	pkg.AddFunction("ParseFS", text_template.ParseFS, "")
	pkg.AddFunction("ParseFiles", text_template.ParseFiles, "")
	pkg.AddFunction("ParseGlob", text_template.ParseGlob, "")
	pkg.AddFunction("URLQueryEscaper", text_template.URLQueryEscaper, "")

	// Types
	pkg.AddType("ExecError", reflect.TypeOf(text_template.ExecError{}), "")
	pkg.AddType("FuncMap", reflect.TypeOf((*text_template.FuncMap)(nil)).Elem(), "")
	pkg.AddType("Template", reflect.TypeOf(text_template.Template{}), "")

}
