// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	unicode_utf16 "unicode/utf16"

	"github.com/t04dJ14n9/gig/importer"
)

func init() {
	pkg := importer.RegisterPackage("unicode/utf16", "utf16")

	// Functions
	pkg.AddFunction("AppendRune", unicode_utf16.AppendRune, "")
	pkg.AddFunction("Decode", unicode_utf16.Decode, "")
	pkg.AddFunction("DecodeRune", unicode_utf16.DecodeRune, "")
	pkg.AddFunction("Encode", unicode_utf16.Encode, "")
	pkg.AddFunction("EncodeRune", unicode_utf16.EncodeRune, "")
	pkg.AddFunction("IsSurrogate", unicode_utf16.IsSurrogate, "")
	pkg.AddFunction("RuneLen", unicode_utf16.RuneLen, "")

}
