// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	dario_cat_mergo "dario.cat/mergo"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("dario.cat/mergo", "mergo")

	// Functions
	pkg.AddFunction("Map", dario_cat_mergo.Map, "", direct_dario_cat_mergo_Map)
	pkg.AddFunction("MapWithOverwrite", dario_cat_mergo.MapWithOverwrite, "", direct_dario_cat_mergo_MapWithOverwrite)
	pkg.AddFunction("Merge", dario_cat_mergo.Merge, "", direct_dario_cat_mergo_Merge)
	pkg.AddFunction("MergeWithOverwrite", dario_cat_mergo.MergeWithOverwrite, "", direct_dario_cat_mergo_MergeWithOverwrite)
	pkg.AddFunction("WithAppendSlice", dario_cat_mergo.WithAppendSlice, "", direct_dario_cat_mergo_WithAppendSlice)
	pkg.AddFunction("WithOverride", dario_cat_mergo.WithOverride, "", direct_dario_cat_mergo_WithOverride)
	pkg.AddFunction("WithOverrideEmptySlice", dario_cat_mergo.WithOverrideEmptySlice, "", direct_dario_cat_mergo_WithOverrideEmptySlice)
	pkg.AddFunction("WithOverwriteWithEmptyValue", dario_cat_mergo.WithOverwriteWithEmptyValue, "", direct_dario_cat_mergo_WithOverwriteWithEmptyValue)
	pkg.AddFunction("WithSliceDeepCopy", dario_cat_mergo.WithSliceDeepCopy, "", direct_dario_cat_mergo_WithSliceDeepCopy)
	pkg.AddFunction("WithTransformers", dario_cat_mergo.WithTransformers, "", direct_dario_cat_mergo_WithTransformers)
	pkg.AddFunction("WithTypeCheck", dario_cat_mergo.WithTypeCheck, "", direct_dario_cat_mergo_WithTypeCheck)
	pkg.AddFunction("WithoutDereference", dario_cat_mergo.WithoutDereference, "", direct_dario_cat_mergo_WithoutDereference)

	// Variables
	pkg.AddVariable("ErrDifferentArgumentsTypes", &dario_cat_mergo.ErrDifferentArgumentsTypes, "")
	pkg.AddVariable("ErrExpectedMapAsDestination", &dario_cat_mergo.ErrExpectedMapAsDestination, "")
	pkg.AddVariable("ErrExpectedStructAsDestination", &dario_cat_mergo.ErrExpectedStructAsDestination, "")
	pkg.AddVariable("ErrNilArguments", &dario_cat_mergo.ErrNilArguments, "")
	pkg.AddVariable("ErrNonPointerArgument", &dario_cat_mergo.ErrNonPointerArgument, "")
	pkg.AddVariable("ErrNotSupported", &dario_cat_mergo.ErrNotSupported, "")

	// Types
	pkg.AddType("Config", reflect.TypeOf(dario_cat_mergo.Config{}), "")
	pkg.AddType("Transformers", reflect.TypeOf((*dario_cat_mergo.Transformers)(nil)).Elem(), "")

}

func direct_dario_cat_mergo_Map(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	varArgs := make([]func(*dario_cat_mergo.Config), 0, len(args)-2)
	for i := 2; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(func(*dario_cat_mergo.Config)))
		}
	}
	return value.FromInterface(dario_cat_mergo.Map(a0, a1, varArgs...))
}

func direct_dario_cat_mergo_MapWithOverwrite(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	varArgs := make([]func(*dario_cat_mergo.Config), 0, len(args)-2)
	for i := 2; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(func(*dario_cat_mergo.Config)))
		}
	}
	return value.FromInterface(dario_cat_mergo.MapWithOverwrite(a0, a1, varArgs...))
}

func direct_dario_cat_mergo_Merge(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	varArgs := make([]func(*dario_cat_mergo.Config), 0, len(args)-2)
	for i := 2; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(func(*dario_cat_mergo.Config)))
		}
	}
	return value.FromInterface(dario_cat_mergo.Merge(a0, a1, varArgs...))
}

func direct_dario_cat_mergo_MergeWithOverwrite(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	varArgs := make([]func(*dario_cat_mergo.Config), 0, len(args)-2)
	for i := 2; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(func(*dario_cat_mergo.Config)))
		}
	}
	return value.FromInterface(dario_cat_mergo.MergeWithOverwrite(a0, a1, varArgs...))
}

func direct_dario_cat_mergo_WithAppendSlice(args []value.Value) value.Value {
	a0 := args[0].Interface().(*dario_cat_mergo.Config)
	dario_cat_mergo.WithAppendSlice(a0)
	return value.MakeNil()
}

func direct_dario_cat_mergo_WithOverride(args []value.Value) value.Value {
	a0 := args[0].Interface().(*dario_cat_mergo.Config)
	dario_cat_mergo.WithOverride(a0)
	return value.MakeNil()
}

func direct_dario_cat_mergo_WithOverrideEmptySlice(args []value.Value) value.Value {
	a0 := args[0].Interface().(*dario_cat_mergo.Config)
	dario_cat_mergo.WithOverrideEmptySlice(a0)
	return value.MakeNil()
}

func direct_dario_cat_mergo_WithOverwriteWithEmptyValue(args []value.Value) value.Value {
	a0 := args[0].Interface().(*dario_cat_mergo.Config)
	dario_cat_mergo.WithOverwriteWithEmptyValue(a0)
	return value.MakeNil()
}

func direct_dario_cat_mergo_WithSliceDeepCopy(args []value.Value) value.Value {
	a0 := args[0].Interface().(*dario_cat_mergo.Config)
	dario_cat_mergo.WithSliceDeepCopy(a0)
	return value.MakeNil()
}

func direct_dario_cat_mergo_WithTransformers(args []value.Value) value.Value {
	a0 := args[0].Interface().(dario_cat_mergo.Transformers)
	return value.FromInterface(dario_cat_mergo.WithTransformers(a0))
}

func direct_dario_cat_mergo_WithTypeCheck(args []value.Value) value.Value {
	a0 := args[0].Interface().(*dario_cat_mergo.Config)
	dario_cat_mergo.WithTypeCheck(a0)
	return value.MakeNil()
}

func direct_dario_cat_mergo_WithoutDereference(args []value.Value) value.Value {
	a0 := args[0].Interface().(*dario_cat_mergo.Config)
	dario_cat_mergo.WithoutDereference(a0)
	return value.MakeNil()
}
