// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	github_com_mattn_go_runewidth "github.com/mattn/go-runewidth"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("github.com/mattn/go-runewidth", "runewidth")

	// Functions
	pkg.AddFunction("FillLeft", github_com_mattn_go_runewidth.FillLeft, "", direct_github_com_mattn_go_runewidth_FillLeft)
	pkg.AddFunction("FillRight", github_com_mattn_go_runewidth.FillRight, "", direct_github_com_mattn_go_runewidth_FillRight)
	pkg.AddFunction("IsAmbiguousWidth", github_com_mattn_go_runewidth.IsAmbiguousWidth, "", direct_github_com_mattn_go_runewidth_IsAmbiguousWidth)
	pkg.AddFunction("IsEastAsian", github_com_mattn_go_runewidth.IsEastAsian, "", direct_github_com_mattn_go_runewidth_IsEastAsian)
	pkg.AddFunction("IsNeutralWidth", github_com_mattn_go_runewidth.IsNeutralWidth, "", direct_github_com_mattn_go_runewidth_IsNeutralWidth)
	pkg.AddFunction("NewCondition", github_com_mattn_go_runewidth.NewCondition, "", direct_github_com_mattn_go_runewidth_NewCondition)
	pkg.AddFunction("RuneWidth", github_com_mattn_go_runewidth.RuneWidth, "", direct_github_com_mattn_go_runewidth_RuneWidth)
	pkg.AddFunction("StringWidth", github_com_mattn_go_runewidth.StringWidth, "", direct_github_com_mattn_go_runewidth_StringWidth)
	pkg.AddFunction("Truncate", github_com_mattn_go_runewidth.Truncate, "", direct_github_com_mattn_go_runewidth_Truncate)
	pkg.AddFunction("Wrap", github_com_mattn_go_runewidth.Wrap, "", direct_github_com_mattn_go_runewidth_Wrap)

	// Variables
	pkg.AddVariable("DefaultCondition", &github_com_mattn_go_runewidth.DefaultCondition, "")
	pkg.AddVariable("EastAsianWidth", &github_com_mattn_go_runewidth.EastAsianWidth, "")

	// Types
	pkg.AddType("Condition", reflect.TypeOf(github_com_mattn_go_runewidth.Condition{}), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("Condition", "FillLeft", direct_method_github_com_mattn_go_runewidth_Condition_FillLeft)
	pkg.AddMethodDirectCall("Condition", "FillRight", direct_method_github_com_mattn_go_runewidth_Condition_FillRight)
	pkg.AddMethodDirectCall("Condition", "RuneWidth", direct_method_github_com_mattn_go_runewidth_Condition_RuneWidth)
	pkg.AddMethodDirectCall("Condition", "StringWidth", direct_method_github_com_mattn_go_runewidth_Condition_StringWidth)
	pkg.AddMethodDirectCall("Condition", "Truncate", direct_method_github_com_mattn_go_runewidth_Condition_Truncate)
	pkg.AddMethodDirectCall("Condition", "Wrap", direct_method_github_com_mattn_go_runewidth_Condition_Wrap)

}

func direct_github_com_mattn_go_runewidth_FillLeft(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	return value.MakeString(string(github_com_mattn_go_runewidth.FillLeft(a0, a1)))
}

func direct_github_com_mattn_go_runewidth_FillRight(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	return value.MakeString(string(github_com_mattn_go_runewidth.FillRight(a0, a1)))
}

func direct_github_com_mattn_go_runewidth_IsAmbiguousWidth(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeBool(github_com_mattn_go_runewidth.IsAmbiguousWidth(a0))
}

func direct_github_com_mattn_go_runewidth_IsEastAsian(args []value.Value) value.Value {
	return value.MakeBool(github_com_mattn_go_runewidth.IsEastAsian())
}

func direct_github_com_mattn_go_runewidth_IsNeutralWidth(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeBool(github_com_mattn_go_runewidth.IsNeutralWidth(a0))
}

func direct_github_com_mattn_go_runewidth_NewCondition(args []value.Value) value.Value {
	return value.FromInterface(github_com_mattn_go_runewidth.NewCondition())
}

func direct_github_com_mattn_go_runewidth_RuneWidth(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.MakeInt(int64(github_com_mattn_go_runewidth.RuneWidth(a0)))
}

func direct_github_com_mattn_go_runewidth_StringWidth(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeInt(int64(github_com_mattn_go_runewidth.StringWidth(a0)))
}

func direct_github_com_mattn_go_runewidth_Truncate(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	a2 := args[2].String()
	return value.MakeString(string(github_com_mattn_go_runewidth.Truncate(a0, a1, a2)))
}

func direct_github_com_mattn_go_runewidth_Wrap(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	return value.MakeString(string(github_com_mattn_go_runewidth.Wrap(a0, a1)))
}

func direct_method_github_com_mattn_go_runewidth_Condition_FillLeft(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mattn_go_runewidth.Condition)
	a0 := args[1].String()
	a1 := int(args[2].Int())
	return value.MakeString(string(recv.FillLeft(a0, a1)))
}

func direct_method_github_com_mattn_go_runewidth_Condition_FillRight(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mattn_go_runewidth.Condition)
	a0 := args[1].String()
	a1 := int(args[2].Int())
	return value.MakeString(string(recv.FillRight(a0, a1)))
}

func direct_method_github_com_mattn_go_runewidth_Condition_RuneWidth(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mattn_go_runewidth.Condition)
	a0 := int32(args[1].Int())
	return value.MakeInt(int64(recv.RuneWidth(a0)))
}

func direct_method_github_com_mattn_go_runewidth_Condition_StringWidth(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mattn_go_runewidth.Condition)
	a0 := args[1].String()
	return value.MakeInt(int64(recv.StringWidth(a0)))
}

func direct_method_github_com_mattn_go_runewidth_Condition_Truncate(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mattn_go_runewidth.Condition)
	a0 := args[1].String()
	a1 := int(args[2].Int())
	a2 := args[3].String()
	return value.MakeString(string(recv.Truncate(a0, a1, a2)))
}

func direct_method_github_com_mattn_go_runewidth_Condition_Wrap(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mattn_go_runewidth.Condition)
	a0 := args[1].String()
	a1 := int(args[2].Int())
	return value.MakeString(string(recv.Wrap(a0, a1)))
}
