// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	github_com_shopspring_decimal "github.com/shopspring/decimal"
	math_big "math/big"
	"reflect"
	regexp "regexp"

	"git.woa.com/youngjin/gig/importer"
	"git.woa.com/youngjin/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("github.com/shopspring/decimal", "decimal")

	// Functions
	pkg.AddFunction("Avg", github_com_shopspring_decimal.Avg, "", direct_github_com_shopspring_decimal_Avg)
	pkg.AddFunction("Max", github_com_shopspring_decimal.Max, "", direct_github_com_shopspring_decimal_Max)
	pkg.AddFunction("Min", github_com_shopspring_decimal.Min, "", direct_github_com_shopspring_decimal_Min)
	pkg.AddFunction("New", github_com_shopspring_decimal.New, "", direct_github_com_shopspring_decimal_New)
	pkg.AddFunction("NewFromBigInt", github_com_shopspring_decimal.NewFromBigInt, "", direct_github_com_shopspring_decimal_NewFromBigInt)
	pkg.AddFunction("NewFromBigRat", github_com_shopspring_decimal.NewFromBigRat, "", direct_github_com_shopspring_decimal_NewFromBigRat)
	pkg.AddFunction("NewFromFloat", github_com_shopspring_decimal.NewFromFloat, "", direct_github_com_shopspring_decimal_NewFromFloat)
	pkg.AddFunction("NewFromFloat32", github_com_shopspring_decimal.NewFromFloat32, "", direct_github_com_shopspring_decimal_NewFromFloat32)
	pkg.AddFunction("NewFromFloatWithExponent", github_com_shopspring_decimal.NewFromFloatWithExponent, "", direct_github_com_shopspring_decimal_NewFromFloatWithExponent)
	pkg.AddFunction("NewFromFormattedString", github_com_shopspring_decimal.NewFromFormattedString, "", direct_github_com_shopspring_decimal_NewFromFormattedString)
	pkg.AddFunction("NewFromInt", github_com_shopspring_decimal.NewFromInt, "", direct_github_com_shopspring_decimal_NewFromInt)
	pkg.AddFunction("NewFromInt32", github_com_shopspring_decimal.NewFromInt32, "", direct_github_com_shopspring_decimal_NewFromInt32)
	pkg.AddFunction("NewFromString", github_com_shopspring_decimal.NewFromString, "", direct_github_com_shopspring_decimal_NewFromString)
	pkg.AddFunction("NewFromUint64", github_com_shopspring_decimal.NewFromUint64, "", direct_github_com_shopspring_decimal_NewFromUint64)
	pkg.AddFunction("NewNullDecimal", github_com_shopspring_decimal.NewNullDecimal, "", direct_github_com_shopspring_decimal_NewNullDecimal)
	pkg.AddFunction("RequireFromString", github_com_shopspring_decimal.RequireFromString, "", direct_github_com_shopspring_decimal_RequireFromString)
	pkg.AddFunction("RescalePair", github_com_shopspring_decimal.RescalePair, "", direct_github_com_shopspring_decimal_RescalePair)
	pkg.AddFunction("Sum", github_com_shopspring_decimal.Sum, "", direct_github_com_shopspring_decimal_Sum)

	// Variables
	pkg.AddVariable("DivisionPrecision", &github_com_shopspring_decimal.DivisionPrecision, "")
	pkg.AddVariable("ExpMaxIterations", &github_com_shopspring_decimal.ExpMaxIterations, "")
	pkg.AddVariable("MarshalJSONWithoutQuotes", &github_com_shopspring_decimal.MarshalJSONWithoutQuotes, "")
	pkg.AddVariable("PowPrecisionNegativeExponent", &github_com_shopspring_decimal.PowPrecisionNegativeExponent, "")
	pkg.AddVariable("Zero", &github_com_shopspring_decimal.Zero, "")

	// Types
	pkg.AddType("Decimal", reflect.TypeOf(github_com_shopspring_decimal.Decimal{}), "")
	pkg.AddType("NullDecimal", reflect.TypeOf(github_com_shopspring_decimal.NullDecimal{}), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("Decimal", "Abs", direct_method_github_com_shopspring_decimal_Decimal_Abs)
	pkg.AddMethodDirectCall("Decimal", "Add", direct_method_github_com_shopspring_decimal_Decimal_Add)
	pkg.AddMethodDirectCall("Decimal", "Atan", direct_method_github_com_shopspring_decimal_Decimal_Atan)
	pkg.AddMethodDirectCall("Decimal", "BigFloat", direct_method_github_com_shopspring_decimal_Decimal_BigFloat)
	pkg.AddMethodDirectCall("Decimal", "BigInt", direct_method_github_com_shopspring_decimal_Decimal_BigInt)
	pkg.AddMethodDirectCall("Decimal", "Ceil", direct_method_github_com_shopspring_decimal_Decimal_Ceil)
	pkg.AddMethodDirectCall("Decimal", "Cmp", direct_method_github_com_shopspring_decimal_Decimal_Cmp)
	pkg.AddMethodDirectCall("Decimal", "Coefficient", direct_method_github_com_shopspring_decimal_Decimal_Coefficient)
	pkg.AddMethodDirectCall("Decimal", "CoefficientInt64", direct_method_github_com_shopspring_decimal_Decimal_CoefficientInt64)
	pkg.AddMethodDirectCall("Decimal", "Compare", direct_method_github_com_shopspring_decimal_Decimal_Compare)
	pkg.AddMethodDirectCall("Decimal", "Copy", direct_method_github_com_shopspring_decimal_Decimal_Copy)
	pkg.AddMethodDirectCall("Decimal", "Cos", direct_method_github_com_shopspring_decimal_Decimal_Cos)
	pkg.AddMethodDirectCall("Decimal", "Div", direct_method_github_com_shopspring_decimal_Decimal_Div)
	pkg.AddMethodDirectCall("Decimal", "DivRound", direct_method_github_com_shopspring_decimal_Decimal_DivRound)
	pkg.AddMethodDirectCall("Decimal", "Equal", direct_method_github_com_shopspring_decimal_Decimal_Equal)
	pkg.AddMethodDirectCall("Decimal", "Equals", direct_method_github_com_shopspring_decimal_Decimal_Equals)
	pkg.AddMethodDirectCall("Decimal", "ExpHullAbrham", direct_method_github_com_shopspring_decimal_Decimal_ExpHullAbrham)
	pkg.AddMethodDirectCall("Decimal", "ExpTaylor", direct_method_github_com_shopspring_decimal_Decimal_ExpTaylor)
	pkg.AddMethodDirectCall("Decimal", "Exponent", direct_method_github_com_shopspring_decimal_Decimal_Exponent)
	pkg.AddMethodDirectCall("Decimal", "Float64", direct_method_github_com_shopspring_decimal_Decimal_Float64)
	pkg.AddMethodDirectCall("Decimal", "Floor", direct_method_github_com_shopspring_decimal_Decimal_Floor)
	pkg.AddMethodDirectCall("Decimal", "GobEncode", direct_method_github_com_shopspring_decimal_Decimal_GobEncode)
	pkg.AddMethodDirectCall("Decimal", "GreaterThan", direct_method_github_com_shopspring_decimal_Decimal_GreaterThan)
	pkg.AddMethodDirectCall("Decimal", "GreaterThanOrEqual", direct_method_github_com_shopspring_decimal_Decimal_GreaterThanOrEqual)
	pkg.AddMethodDirectCall("Decimal", "InexactFloat64", direct_method_github_com_shopspring_decimal_Decimal_InexactFloat64)
	pkg.AddMethodDirectCall("Decimal", "IntPart", direct_method_github_com_shopspring_decimal_Decimal_IntPart)
	pkg.AddMethodDirectCall("Decimal", "IsInteger", direct_method_github_com_shopspring_decimal_Decimal_IsInteger)
	pkg.AddMethodDirectCall("Decimal", "IsNegative", direct_method_github_com_shopspring_decimal_Decimal_IsNegative)
	pkg.AddMethodDirectCall("Decimal", "IsPositive", direct_method_github_com_shopspring_decimal_Decimal_IsPositive)
	pkg.AddMethodDirectCall("Decimal", "IsZero", direct_method_github_com_shopspring_decimal_Decimal_IsZero)
	pkg.AddMethodDirectCall("Decimal", "LessThan", direct_method_github_com_shopspring_decimal_Decimal_LessThan)
	pkg.AddMethodDirectCall("Decimal", "LessThanOrEqual", direct_method_github_com_shopspring_decimal_Decimal_LessThanOrEqual)
	pkg.AddMethodDirectCall("Decimal", "Ln", direct_method_github_com_shopspring_decimal_Decimal_Ln)
	pkg.AddMethodDirectCall("Decimal", "MarshalBinary", direct_method_github_com_shopspring_decimal_Decimal_MarshalBinary)
	pkg.AddMethodDirectCall("Decimal", "MarshalJSON", direct_method_github_com_shopspring_decimal_Decimal_MarshalJSON)
	pkg.AddMethodDirectCall("Decimal", "MarshalText", direct_method_github_com_shopspring_decimal_Decimal_MarshalText)
	pkg.AddMethodDirectCall("Decimal", "Mod", direct_method_github_com_shopspring_decimal_Decimal_Mod)
	pkg.AddMethodDirectCall("Decimal", "Mul", direct_method_github_com_shopspring_decimal_Decimal_Mul)
	pkg.AddMethodDirectCall("Decimal", "Neg", direct_method_github_com_shopspring_decimal_Decimal_Neg)
	pkg.AddMethodDirectCall("Decimal", "NumDigits", direct_method_github_com_shopspring_decimal_Decimal_NumDigits)
	pkg.AddMethodDirectCall("Decimal", "Pow", direct_method_github_com_shopspring_decimal_Decimal_Pow)
	pkg.AddMethodDirectCall("Decimal", "PowBigInt", direct_method_github_com_shopspring_decimal_Decimal_PowBigInt)
	pkg.AddMethodDirectCall("Decimal", "PowInt32", direct_method_github_com_shopspring_decimal_Decimal_PowInt32)
	pkg.AddMethodDirectCall("Decimal", "PowWithPrecision", direct_method_github_com_shopspring_decimal_Decimal_PowWithPrecision)
	pkg.AddMethodDirectCall("Decimal", "QuoRem", direct_method_github_com_shopspring_decimal_Decimal_QuoRem)
	pkg.AddMethodDirectCall("Decimal", "Rat", direct_method_github_com_shopspring_decimal_Decimal_Rat)
	pkg.AddMethodDirectCall("Decimal", "Round", direct_method_github_com_shopspring_decimal_Decimal_Round)
	pkg.AddMethodDirectCall("Decimal", "RoundBank", direct_method_github_com_shopspring_decimal_Decimal_RoundBank)
	pkg.AddMethodDirectCall("Decimal", "RoundCash", direct_method_github_com_shopspring_decimal_Decimal_RoundCash)
	pkg.AddMethodDirectCall("Decimal", "RoundCeil", direct_method_github_com_shopspring_decimal_Decimal_RoundCeil)
	pkg.AddMethodDirectCall("Decimal", "RoundDown", direct_method_github_com_shopspring_decimal_Decimal_RoundDown)
	pkg.AddMethodDirectCall("Decimal", "RoundFloor", direct_method_github_com_shopspring_decimal_Decimal_RoundFloor)
	pkg.AddMethodDirectCall("Decimal", "RoundUp", direct_method_github_com_shopspring_decimal_Decimal_RoundUp)
	pkg.AddMethodDirectCall("Decimal", "Shift", direct_method_github_com_shopspring_decimal_Decimal_Shift)
	pkg.AddMethodDirectCall("Decimal", "Sign", direct_method_github_com_shopspring_decimal_Decimal_Sign)
	pkg.AddMethodDirectCall("Decimal", "Sin", direct_method_github_com_shopspring_decimal_Decimal_Sin)
	pkg.AddMethodDirectCall("Decimal", "String", direct_method_github_com_shopspring_decimal_Decimal_String)
	pkg.AddMethodDirectCall("Decimal", "StringFixed", direct_method_github_com_shopspring_decimal_Decimal_StringFixed)
	pkg.AddMethodDirectCall("Decimal", "StringFixedBank", direct_method_github_com_shopspring_decimal_Decimal_StringFixedBank)
	pkg.AddMethodDirectCall("Decimal", "StringFixedCash", direct_method_github_com_shopspring_decimal_Decimal_StringFixedCash)
	pkg.AddMethodDirectCall("Decimal", "StringScaled", direct_method_github_com_shopspring_decimal_Decimal_StringScaled)
	pkg.AddMethodDirectCall("Decimal", "Sub", direct_method_github_com_shopspring_decimal_Decimal_Sub)
	pkg.AddMethodDirectCall("Decimal", "Tan", direct_method_github_com_shopspring_decimal_Decimal_Tan)
	pkg.AddMethodDirectCall("Decimal", "Truncate", direct_method_github_com_shopspring_decimal_Decimal_Truncate)
	pkg.AddMethodDirectCall("Decimal", "Value", direct_method_github_com_shopspring_decimal_Decimal_Value)
	pkg.AddMethodDirectCall("Decimal", "GobDecode", direct_method_github_com_shopspring_decimal_Decimal_GobDecode)
	pkg.AddMethodDirectCall("Decimal", "Scan", direct_method_github_com_shopspring_decimal_Decimal_Scan)
	pkg.AddMethodDirectCall("Decimal", "UnmarshalBinary", direct_method_github_com_shopspring_decimal_Decimal_UnmarshalBinary)
	pkg.AddMethodDirectCall("Decimal", "UnmarshalJSON", direct_method_github_com_shopspring_decimal_Decimal_UnmarshalJSON)
	pkg.AddMethodDirectCall("Decimal", "UnmarshalText", direct_method_github_com_shopspring_decimal_Decimal_UnmarshalText)
	pkg.AddMethodDirectCall("NullDecimal", "MarshalJSON", direct_method_github_com_shopspring_decimal_NullDecimal_MarshalJSON)
	pkg.AddMethodDirectCall("NullDecimal", "MarshalText", direct_method_github_com_shopspring_decimal_NullDecimal_MarshalText)
	pkg.AddMethodDirectCall("NullDecimal", "Value", direct_method_github_com_shopspring_decimal_NullDecimal_Value)
	pkg.AddMethodDirectCall("NullDecimal", "Scan", direct_method_github_com_shopspring_decimal_NullDecimal_Scan)
	pkg.AddMethodDirectCall("NullDecimal", "UnmarshalJSON", direct_method_github_com_shopspring_decimal_NullDecimal_UnmarshalJSON)
	pkg.AddMethodDirectCall("NullDecimal", "UnmarshalText", direct_method_github_com_shopspring_decimal_NullDecimal_UnmarshalText)

}

func direct_github_com_shopspring_decimal_Avg(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	varArgs := make([]github_com_shopspring_decimal.Decimal, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface().(github_com_shopspring_decimal.Decimal)
	}
	return value.FromInterface(github_com_shopspring_decimal.Avg(a0, varArgs...))
}

func direct_github_com_shopspring_decimal_Max(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	varArgs := make([]github_com_shopspring_decimal.Decimal, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface().(github_com_shopspring_decimal.Decimal)
	}
	return value.FromInterface(github_com_shopspring_decimal.Max(a0, varArgs...))
}

func direct_github_com_shopspring_decimal_Min(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	varArgs := make([]github_com_shopspring_decimal.Decimal, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface().(github_com_shopspring_decimal.Decimal)
	}
	return value.FromInterface(github_com_shopspring_decimal.Min(a0, varArgs...))
}

func direct_github_com_shopspring_decimal_New(args []value.Value) value.Value {
	a0 := args[0].Int()
	a1 := int32(args[1].Int())
	return value.FromInterface(github_com_shopspring_decimal.New(a0, a1))
}

func direct_github_com_shopspring_decimal_NewFromBigInt(args []value.Value) value.Value {
	a0 := args[0].Interface().(*math_big.Int)
	a1 := int32(args[1].Int())
	return value.FromInterface(github_com_shopspring_decimal.NewFromBigInt(a0, a1))
}

func direct_github_com_shopspring_decimal_NewFromBigRat(args []value.Value) value.Value {
	a0 := args[0].Interface().(*math_big.Rat)
	a1 := int32(args[1].Int())
	return value.FromInterface(github_com_shopspring_decimal.NewFromBigRat(a0, a1))
}

func direct_github_com_shopspring_decimal_NewFromFloat(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.FromInterface(github_com_shopspring_decimal.NewFromFloat(a0))
}

func direct_github_com_shopspring_decimal_NewFromFloat32(args []value.Value) value.Value {
	a0 := float32(args[0].Float())
	return value.FromInterface(github_com_shopspring_decimal.NewFromFloat32(a0))
}

func direct_github_com_shopspring_decimal_NewFromFloatWithExponent(args []value.Value) value.Value {
	a0 := args[0].Float()
	a1 := int32(args[1].Int())
	return value.FromInterface(github_com_shopspring_decimal.NewFromFloatWithExponent(a0, a1))
}

func direct_github_com_shopspring_decimal_NewFromFormattedString(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].Interface().(*regexp.Regexp)
	r0, r1 := github_com_shopspring_decimal.NewFromFormattedString(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_shopspring_decimal_NewFromInt(args []value.Value) value.Value {
	a0 := args[0].Int()
	return value.FromInterface(github_com_shopspring_decimal.NewFromInt(a0))
}

func direct_github_com_shopspring_decimal_NewFromInt32(args []value.Value) value.Value {
	a0 := int32(args[0].Int())
	return value.FromInterface(github_com_shopspring_decimal.NewFromInt32(a0))
}

func direct_github_com_shopspring_decimal_NewFromString(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := github_com_shopspring_decimal.NewFromString(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_shopspring_decimal_NewFromUint64(args []value.Value) value.Value {
	a0 := args[0].Uint()
	return value.FromInterface(github_com_shopspring_decimal.NewFromUint64(a0))
}

func direct_github_com_shopspring_decimal_NewNullDecimal(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(github_com_shopspring_decimal.NewNullDecimal(a0))
}

func direct_github_com_shopspring_decimal_RequireFromString(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(github_com_shopspring_decimal.RequireFromString(a0))
}

func direct_github_com_shopspring_decimal_RescalePair(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a1 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	r0, r1 := github_com_shopspring_decimal.RescalePair(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_shopspring_decimal_Sum(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	varArgs := make([]github_com_shopspring_decimal.Decimal, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface().(github_com_shopspring_decimal.Decimal)
	}
	return value.FromInterface(github_com_shopspring_decimal.Sum(a0, varArgs...))
}

func direct_method_github_com_shopspring_decimal_Decimal_Abs(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Abs())
}

func direct_method_github_com_shopspring_decimal_Decimal_Add(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Add(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Atan(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Atan())
}

func direct_method_github_com_shopspring_decimal_Decimal_BigFloat(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.BigFloat())
}

func direct_method_github_com_shopspring_decimal_Decimal_BigInt(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.BigInt())
}

func direct_method_github_com_shopspring_decimal_Decimal_Ceil(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Ceil())
}

func direct_method_github_com_shopspring_decimal_Decimal_Cmp(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeInt(int64(recv.Cmp(a0)))
}

func direct_method_github_com_shopspring_decimal_Decimal_Coefficient(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Coefficient())
}

func direct_method_github_com_shopspring_decimal_Decimal_CoefficientInt64(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeInt64(recv.CoefficientInt64())
}

func direct_method_github_com_shopspring_decimal_Decimal_Compare(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeInt(int64(recv.Compare(a0)))
}

func direct_method_github_com_shopspring_decimal_Decimal_Copy(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Copy())
}

func direct_method_github_com_shopspring_decimal_Decimal_Cos(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Cos())
}

func direct_method_github_com_shopspring_decimal_Decimal_Div(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Div(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_DivRound(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	a1 := int32(args[2].Int())
	return value.FromInterface(recv.DivRound(a0, a1))
}

func direct_method_github_com_shopspring_decimal_Decimal_Equal(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.Equal(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Equals(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.Equals(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_ExpHullAbrham(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := uint32(args[1].Uint())
	r0, r1 := recv.ExpHullAbrham(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_ExpTaylor(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	r0, r1 := recv.ExpTaylor(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_Exponent(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeInt(int64(recv.Exponent()))
}

func direct_method_github_com_shopspring_decimal_Decimal_Float64(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	r0, r1 := recv.Float64()
	return value.MakeValueSlice([]value.Value{value.MakeFloat(float64(r0)), value.MakeBool(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_Floor(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Floor())
}

func direct_method_github_com_shopspring_decimal_Decimal_GobEncode(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	r0, r1 := recv.GobEncode()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_GreaterThan(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.GreaterThan(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_GreaterThanOrEqual(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.GreaterThanOrEqual(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_InexactFloat64(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeFloat(float64(recv.InexactFloat64()))
}

func direct_method_github_com_shopspring_decimal_Decimal_IntPart(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeInt64(recv.IntPart())
}

func direct_method_github_com_shopspring_decimal_Decimal_IsInteger(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.IsInteger())
}

func direct_method_github_com_shopspring_decimal_Decimal_IsNegative(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.IsNegative())
}

func direct_method_github_com_shopspring_decimal_Decimal_IsPositive(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.IsPositive())
}

func direct_method_github_com_shopspring_decimal_Decimal_IsZero(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.IsZero())
}

func direct_method_github_com_shopspring_decimal_Decimal_LessThan(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.LessThan(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_LessThanOrEqual(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeBool(recv.LessThanOrEqual(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Ln(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	r0, r1 := recv.Ln(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_MarshalBinary(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	r0, r1 := recv.MarshalBinary()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_MarshalJSON(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	r0, r1 := recv.MarshalJSON()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_MarshalText(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	r0, r1 := recv.MarshalText()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_Mod(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Mod(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Mul(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Mul(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Neg(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Neg())
}

func direct_method_github_com_shopspring_decimal_Decimal_NumDigits(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeInt(int64(recv.NumDigits()))
}

func direct_method_github_com_shopspring_decimal_Decimal_Pow(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Pow(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_PowBigInt(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(*math_big.Int)
	r0, r1 := recv.PowBigInt(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_PowInt32(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	r0, r1 := recv.PowInt32(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_PowWithPrecision(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	a1 := int32(args[2].Int())
	r0, r1 := recv.PowWithPrecision(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_QuoRem(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	a1 := int32(args[2].Int())
	r0, r1 := recv.QuoRem(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_Rat(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Rat())
}

func direct_method_github_com_shopspring_decimal_Decimal_Round(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.FromInterface(recv.Round(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_RoundBank(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.FromInterface(recv.RoundBank(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_RoundCash(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := byte(args[1].Uint())
	return value.FromInterface(recv.RoundCash(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_RoundCeil(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.FromInterface(recv.RoundCeil(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_RoundDown(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.FromInterface(recv.RoundDown(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_RoundFloor(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.FromInterface(recv.RoundFloor(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_RoundUp(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.FromInterface(recv.RoundUp(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Shift(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.FromInterface(recv.Shift(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Sign(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeInt(int64(recv.Sign()))
}

func direct_method_github_com_shopspring_decimal_Decimal_Sin(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Sin())
}

func direct_method_github_com_shopspring_decimal_Decimal_String(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.MakeString(string(recv.String()))
}

func direct_method_github_com_shopspring_decimal_Decimal_StringFixed(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.MakeString(string(recv.StringFixed(a0)))
}

func direct_method_github_com_shopspring_decimal_Decimal_StringFixedBank(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.MakeString(string(recv.StringFixedBank(a0)))
}

func direct_method_github_com_shopspring_decimal_Decimal_StringFixedCash(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := byte(args[1].Uint())
	return value.MakeString(string(recv.StringFixedCash(a0)))
}

func direct_method_github_com_shopspring_decimal_Decimal_StringScaled(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.MakeString(string(recv.StringScaled(a0)))
}

func direct_method_github_com_shopspring_decimal_Decimal_Sub(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Sub(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Tan(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	return value.FromInterface(recv.Tan())
}

func direct_method_github_com_shopspring_decimal_Decimal_Truncate(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	a0 := int32(args[1].Int())
	return value.FromInterface(recv.Truncate(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Value(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.Decimal)
	r0, r1 := recv.Value()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_Decimal_GobDecode(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_shopspring_decimal.Decimal)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.FromInterface(recv.GobDecode(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_Scan(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_shopspring_decimal.Decimal)
	a0 := args[1].Interface()
	return value.FromInterface(recv.Scan(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_UnmarshalBinary(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_shopspring_decimal.Decimal)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.FromInterface(recv.UnmarshalBinary(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_UnmarshalJSON(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_shopspring_decimal.Decimal)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.FromInterface(recv.UnmarshalJSON(a0))
}

func direct_method_github_com_shopspring_decimal_Decimal_UnmarshalText(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_shopspring_decimal.Decimal)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.FromInterface(recv.UnmarshalText(a0))
}

func direct_method_github_com_shopspring_decimal_NullDecimal_MarshalJSON(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.NullDecimal)
	r0, r1 := recv.MarshalJSON()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_NullDecimal_MarshalText(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.NullDecimal)
	r0, r1 := recv.MarshalText()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_NullDecimal_Value(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_shopspring_decimal.NullDecimal)
	r0, r1 := recv.Value()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_shopspring_decimal_NullDecimal_Scan(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_shopspring_decimal.NullDecimal)
	a0 := args[1].Interface()
	return value.FromInterface(recv.Scan(a0))
}

func direct_method_github_com_shopspring_decimal_NullDecimal_UnmarshalJSON(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_shopspring_decimal.NullDecimal)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.FromInterface(recv.UnmarshalJSON(a0))
}

func direct_method_github_com_shopspring_decimal_NullDecimal_UnmarshalText(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_shopspring_decimal.NullDecimal)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.FromInterface(recv.UnmarshalText(a0))
}
