// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	github_com_kballard_go_shellquote "github.com/kballard/go-shellquote"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("github.com/kballard/go-shellquote", "shellquote")

	// Functions
	pkg.AddFunction("Join", github_com_kballard_go_shellquote.Join, "", direct_github_com_kballard_go_shellquote_Join)
	pkg.AddFunction("Split", github_com_kballard_go_shellquote.Split, "", direct_github_com_kballard_go_shellquote_Split)

	// Variables
	pkg.AddVariable("UnterminatedDoubleQuoteError", &github_com_kballard_go_shellquote.UnterminatedDoubleQuoteError, "")
	pkg.AddVariable("UnterminatedEscapeError", &github_com_kballard_go_shellquote.UnterminatedEscapeError, "")
	pkg.AddVariable("UnterminatedSingleQuoteError", &github_com_kballard_go_shellquote.UnterminatedSingleQuoteError, "")

}

func direct_github_com_kballard_go_shellquote_Join(args []value.Value) value.Value {
	varArgs := make([]string, 0, len(args)-0)
	for i := 0; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeString(string(github_com_kballard_go_shellquote.Join(varArgs...)))
}

func direct_github_com_kballard_go_shellquote_Split(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := github_com_kballard_go_shellquote.Split(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}
