// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	github_com_mohae_deepcopy "github.com/mohae/deepcopy"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("github.com/mohae/deepcopy", "deepcopy")

	// Functions
	pkg.AddFunction("Copy", github_com_mohae_deepcopy.Copy, "", direct_github_com_mohae_deepcopy_Copy)
	pkg.AddFunction("Iface", github_com_mohae_deepcopy.Iface, "", direct_github_com_mohae_deepcopy_Iface)

	// Types
	pkg.AddType("Interface", reflect.TypeOf((*github_com_mohae_deepcopy.Interface)(nil)).Elem(), "")

}

func direct_github_com_mohae_deepcopy_Copy(args []value.Value) value.Value {
	a0 := args[0].Interface()
	return value.FromInterface(github_com_mohae_deepcopy.Copy(a0))
}

func direct_github_com_mohae_deepcopy_Iface(args []value.Value) value.Value {
	a0 := args[0].Interface()
	return value.FromInterface(github_com_mohae_deepcopy.Iface(a0))
}
