// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	github_com_gosimple_slug "github.com/gosimple/slug"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("github.com/gosimple/slug", "slug")

	// Functions
	pkg.AddFunction("IsSlug", github_com_gosimple_slug.IsSlug, "", direct_github_com_gosimple_slug_IsSlug)
	pkg.AddFunction("Make", github_com_gosimple_slug.Make, "", direct_github_com_gosimple_slug_Make)
	pkg.AddFunction("MakeLang", github_com_gosimple_slug.MakeLang, "", direct_github_com_gosimple_slug_MakeLang)
	pkg.AddFunction("Substitute", github_com_gosimple_slug.Substitute, "", direct_github_com_gosimple_slug_Substitute)
	pkg.AddFunction("SubstituteRune", github_com_gosimple_slug.SubstituteRune, "", direct_github_com_gosimple_slug_SubstituteRune)

	// Variables
	pkg.AddVariable("AppendTimestamp", &github_com_gosimple_slug.AppendTimestamp, "")
	pkg.AddVariable("CustomRuneSub", &github_com_gosimple_slug.CustomRuneSub, "")
	pkg.AddVariable("CustomSub", &github_com_gosimple_slug.CustomSub, "")
	pkg.AddVariable("DisableEndsTrim", &github_com_gosimple_slug.DisableEndsTrim, "")
	pkg.AddVariable("DisableMultipleDashTrim", &github_com_gosimple_slug.DisableMultipleDashTrim, "")
	pkg.AddVariable("EnableSmartTruncate", &github_com_gosimple_slug.EnableSmartTruncate, "")
	pkg.AddVariable("Lowercase", &github_com_gosimple_slug.Lowercase, "")
	pkg.AddVariable("MaxLength", &github_com_gosimple_slug.MaxLength, "")

}

func direct_github_com_gosimple_slug_IsSlug(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_gosimple_slug.IsSlug(a0))
}

func direct_github_com_gosimple_slug_Make(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(github_com_gosimple_slug.Make(a0)))
}

func direct_github_com_gosimple_slug_MakeLang(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(github_com_gosimple_slug.MakeLang(a0, a1)))
}

func direct_github_com_gosimple_slug_Substitute(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].Interface().(map[string]string)
	return value.MakeString(string(github_com_gosimple_slug.Substitute(a0, a1)))
}

func direct_github_com_gosimple_slug_SubstituteRune(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].Interface().(map[rune]string)
	return value.MakeString(string(github_com_gosimple_slug.SubstituteRune(a0, a1)))
}
