// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	github_com_mitchellh_mapstructure "github.com/mitchellh/mapstructure"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("github.com/mitchellh/mapstructure", "mapstructure")

	// Functions
	pkg.AddFunction("ComposeDecodeHookFunc", github_com_mitchellh_mapstructure.ComposeDecodeHookFunc, "", direct_github_com_mitchellh_mapstructure_ComposeDecodeHookFunc)
	pkg.AddFunction("Decode", github_com_mitchellh_mapstructure.Decode, "", direct_github_com_mitchellh_mapstructure_Decode)
	pkg.AddFunction("DecodeHookExec", github_com_mitchellh_mapstructure.DecodeHookExec, "", direct_github_com_mitchellh_mapstructure_DecodeHookExec)
	pkg.AddFunction("DecodeMetadata", github_com_mitchellh_mapstructure.DecodeMetadata, "", direct_github_com_mitchellh_mapstructure_DecodeMetadata)
	pkg.AddFunction("NewDecoder", github_com_mitchellh_mapstructure.NewDecoder, "", direct_github_com_mitchellh_mapstructure_NewDecoder)
	pkg.AddFunction("OrComposeDecodeHookFunc", github_com_mitchellh_mapstructure.OrComposeDecodeHookFunc, "", direct_github_com_mitchellh_mapstructure_OrComposeDecodeHookFunc)
	pkg.AddFunction("RecursiveStructToMapHookFunc", github_com_mitchellh_mapstructure.RecursiveStructToMapHookFunc, "", direct_github_com_mitchellh_mapstructure_RecursiveStructToMapHookFunc)
	pkg.AddFunction("StringToIPHookFunc", github_com_mitchellh_mapstructure.StringToIPHookFunc, "", direct_github_com_mitchellh_mapstructure_StringToIPHookFunc)
	pkg.AddFunction("StringToIPNetHookFunc", github_com_mitchellh_mapstructure.StringToIPNetHookFunc, "", direct_github_com_mitchellh_mapstructure_StringToIPNetHookFunc)
	pkg.AddFunction("StringToSliceHookFunc", github_com_mitchellh_mapstructure.StringToSliceHookFunc, "", direct_github_com_mitchellh_mapstructure_StringToSliceHookFunc)
	pkg.AddFunction("StringToTimeDurationHookFunc", github_com_mitchellh_mapstructure.StringToTimeDurationHookFunc, "", direct_github_com_mitchellh_mapstructure_StringToTimeDurationHookFunc)
	pkg.AddFunction("StringToTimeHookFunc", github_com_mitchellh_mapstructure.StringToTimeHookFunc, "", direct_github_com_mitchellh_mapstructure_StringToTimeHookFunc)
	pkg.AddFunction("TextUnmarshallerHookFunc", github_com_mitchellh_mapstructure.TextUnmarshallerHookFunc, "", direct_github_com_mitchellh_mapstructure_TextUnmarshallerHookFunc)
	pkg.AddFunction("WeakDecode", github_com_mitchellh_mapstructure.WeakDecode, "", direct_github_com_mitchellh_mapstructure_WeakDecode)
	pkg.AddFunction("WeakDecodeMetadata", github_com_mitchellh_mapstructure.WeakDecodeMetadata, "", direct_github_com_mitchellh_mapstructure_WeakDecodeMetadata)
	pkg.AddFunction("WeaklyTypedHook", github_com_mitchellh_mapstructure.WeaklyTypedHook, "", direct_github_com_mitchellh_mapstructure_WeaklyTypedHook)

	// Types
	pkg.AddType("DecodeHookFunc", reflect.TypeOf((*github_com_mitchellh_mapstructure.DecodeHookFunc)(nil)).Elem(), "")
	pkg.AddType("DecodeHookFuncKind", reflect.TypeOf((*github_com_mitchellh_mapstructure.DecodeHookFuncKind)(nil)).Elem(), "")
	pkg.AddType("DecodeHookFuncType", reflect.TypeOf((*github_com_mitchellh_mapstructure.DecodeHookFuncType)(nil)).Elem(), "")
	pkg.AddType("DecodeHookFuncValue", reflect.TypeOf((*github_com_mitchellh_mapstructure.DecodeHookFuncValue)(nil)).Elem(), "")
	pkg.AddType("Decoder", reflect.TypeOf(github_com_mitchellh_mapstructure.Decoder{}), "")
	pkg.AddType("DecoderConfig", reflect.TypeOf(github_com_mitchellh_mapstructure.DecoderConfig{}), "")
	pkg.AddType("Error", reflect.TypeOf(github_com_mitchellh_mapstructure.Error{}), "")
	pkg.AddType("Metadata", reflect.TypeOf(github_com_mitchellh_mapstructure.Metadata{}), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("Decoder", "Decode", direct_method_github_com_mitchellh_mapstructure_Decoder_Decode)
	pkg.AddMethodDirectCall("Error", "Error", direct_method_github_com_mitchellh_mapstructure_Error_Error)
	pkg.AddMethodDirectCall("Error", "WrappedErrors", direct_method_github_com_mitchellh_mapstructure_Error_WrappedErrors)

}

func direct_github_com_mitchellh_mapstructure_ComposeDecodeHookFunc(args []value.Value) value.Value {
	varArgs := make([]github_com_mitchellh_mapstructure.DecodeHookFunc, 0, len(args)-0)
	for i := 0; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(github_com_mitchellh_mapstructure.DecodeHookFunc))
		}
	}
	return value.FromInterface(github_com_mitchellh_mapstructure.ComposeDecodeHookFunc(varArgs...))
}

func direct_github_com_mitchellh_mapstructure_Decode(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	return value.FromInterface(github_com_mitchellh_mapstructure.Decode(a0, a1))
}

func direct_github_com_mitchellh_mapstructure_DecodeHookExec(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_mitchellh_mapstructure.DecodeHookFunc)
	a1 := args[1].Interface().(reflect.Value)
	a2 := args[2].Interface().(reflect.Value)
	r0, r1 := github_com_mitchellh_mapstructure.DecodeHookExec(a0, a1, a2)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_mitchellh_mapstructure_DecodeMetadata(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	a2 := args[2].Interface().(*github_com_mitchellh_mapstructure.Metadata)
	return value.FromInterface(github_com_mitchellh_mapstructure.DecodeMetadata(a0, a1, a2))
}

func direct_github_com_mitchellh_mapstructure_NewDecoder(args []value.Value) value.Value {
	a0 := args[0].Interface().(*github_com_mitchellh_mapstructure.DecoderConfig)
	r0, r1 := github_com_mitchellh_mapstructure.NewDecoder(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_mitchellh_mapstructure_OrComposeDecodeHookFunc(args []value.Value) value.Value {
	varArgs := make([]github_com_mitchellh_mapstructure.DecodeHookFunc, 0, len(args)-0)
	for i := 0; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(github_com_mitchellh_mapstructure.DecodeHookFunc))
		}
	}
	return value.FromInterface(github_com_mitchellh_mapstructure.OrComposeDecodeHookFunc(varArgs...))
}

func direct_github_com_mitchellh_mapstructure_RecursiveStructToMapHookFunc(args []value.Value) value.Value {
	return value.FromInterface(github_com_mitchellh_mapstructure.RecursiveStructToMapHookFunc())
}

func direct_github_com_mitchellh_mapstructure_StringToIPHookFunc(args []value.Value) value.Value {
	return value.FromInterface(github_com_mitchellh_mapstructure.StringToIPHookFunc())
}

func direct_github_com_mitchellh_mapstructure_StringToIPNetHookFunc(args []value.Value) value.Value {
	return value.FromInterface(github_com_mitchellh_mapstructure.StringToIPNetHookFunc())
}

func direct_github_com_mitchellh_mapstructure_StringToSliceHookFunc(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(github_com_mitchellh_mapstructure.StringToSliceHookFunc(a0))
}

func direct_github_com_mitchellh_mapstructure_StringToTimeDurationHookFunc(args []value.Value) value.Value {
	return value.FromInterface(github_com_mitchellh_mapstructure.StringToTimeDurationHookFunc())
}

func direct_github_com_mitchellh_mapstructure_StringToTimeHookFunc(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(github_com_mitchellh_mapstructure.StringToTimeHookFunc(a0))
}

func direct_github_com_mitchellh_mapstructure_TextUnmarshallerHookFunc(args []value.Value) value.Value {
	return value.FromInterface(github_com_mitchellh_mapstructure.TextUnmarshallerHookFunc())
}

func direct_github_com_mitchellh_mapstructure_WeakDecode(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	return value.FromInterface(github_com_mitchellh_mapstructure.WeakDecode(a0, a1))
}

func direct_github_com_mitchellh_mapstructure_WeakDecodeMetadata(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	a2 := args[2].Interface().(*github_com_mitchellh_mapstructure.Metadata)
	return value.FromInterface(github_com_mitchellh_mapstructure.WeakDecodeMetadata(a0, a1, a2))
}

func direct_github_com_mitchellh_mapstructure_WeaklyTypedHook(args []value.Value) value.Value {
	a0 := reflect.Kind(uint(args[0].Uint()))
	a1 := reflect.Kind(uint(args[1].Uint()))
	a2 := args[2].Interface()
	r0, r1 := github_com_mitchellh_mapstructure.WeaklyTypedHook(a0, a1, a2)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_mitchellh_mapstructure_Decoder_Decode(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mitchellh_mapstructure.Decoder)
	a0 := args[1].Interface()
	return value.FromInterface(recv.Decode(a0))
}

func direct_method_github_com_mitchellh_mapstructure_Error_Error(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mitchellh_mapstructure.Error)
	return value.MakeString(string(recv.Error()))
}

func direct_method_github_com_mitchellh_mapstructure_Error_WrappedErrors(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_mitchellh_mapstructure.Error)
	return value.FromInterface(recv.WrappedErrors())
}
