// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	github_com_golang_jwt_jwt_v5 "github.com/golang-jwt/jwt/v5"
	"reflect"
	time "time"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("github.com/golang-jwt/jwt/v5", "jwt")

	// Functions
	pkg.AddFunction("GetAlgorithms", github_com_golang_jwt_jwt_v5.GetAlgorithms, "", direct_github_com_golang_jwt_jwt_v5_GetAlgorithms)
	pkg.AddFunction("GetSigningMethod", github_com_golang_jwt_jwt_v5.GetSigningMethod, "", direct_github_com_golang_jwt_jwt_v5_GetSigningMethod)
	pkg.AddFunction("New", github_com_golang_jwt_jwt_v5.New, "", direct_github_com_golang_jwt_jwt_v5_New)
	pkg.AddFunction("NewNumericDate", github_com_golang_jwt_jwt_v5.NewNumericDate, "", direct_github_com_golang_jwt_jwt_v5_NewNumericDate)
	pkg.AddFunction("NewParser", github_com_golang_jwt_jwt_v5.NewParser, "", direct_github_com_golang_jwt_jwt_v5_NewParser)
	pkg.AddFunction("NewValidator", github_com_golang_jwt_jwt_v5.NewValidator, "", direct_github_com_golang_jwt_jwt_v5_NewValidator)
	pkg.AddFunction("NewWithClaims", github_com_golang_jwt_jwt_v5.NewWithClaims, "", direct_github_com_golang_jwt_jwt_v5_NewWithClaims)
	pkg.AddFunction("Parse", github_com_golang_jwt_jwt_v5.Parse, "", direct_github_com_golang_jwt_jwt_v5_Parse)
	pkg.AddFunction("ParseECPrivateKeyFromPEM", github_com_golang_jwt_jwt_v5.ParseECPrivateKeyFromPEM, "", direct_github_com_golang_jwt_jwt_v5_ParseECPrivateKeyFromPEM)
	pkg.AddFunction("ParseECPublicKeyFromPEM", github_com_golang_jwt_jwt_v5.ParseECPublicKeyFromPEM, "", direct_github_com_golang_jwt_jwt_v5_ParseECPublicKeyFromPEM)
	pkg.AddFunction("ParseEdPrivateKeyFromPEM", github_com_golang_jwt_jwt_v5.ParseEdPrivateKeyFromPEM, "", direct_github_com_golang_jwt_jwt_v5_ParseEdPrivateKeyFromPEM)
	pkg.AddFunction("ParseEdPublicKeyFromPEM", github_com_golang_jwt_jwt_v5.ParseEdPublicKeyFromPEM, "", direct_github_com_golang_jwt_jwt_v5_ParseEdPublicKeyFromPEM)
	pkg.AddFunction("ParseRSAPrivateKeyFromPEM", github_com_golang_jwt_jwt_v5.ParseRSAPrivateKeyFromPEM, "", direct_github_com_golang_jwt_jwt_v5_ParseRSAPrivateKeyFromPEM)
	pkg.AddFunction("ParseRSAPrivateKeyFromPEMWithPassword", github_com_golang_jwt_jwt_v5.ParseRSAPrivateKeyFromPEMWithPassword, "", direct_github_com_golang_jwt_jwt_v5_ParseRSAPrivateKeyFromPEMWithPassword)
	pkg.AddFunction("ParseRSAPublicKeyFromPEM", github_com_golang_jwt_jwt_v5.ParseRSAPublicKeyFromPEM, "", direct_github_com_golang_jwt_jwt_v5_ParseRSAPublicKeyFromPEM)
	pkg.AddFunction("ParseWithClaims", github_com_golang_jwt_jwt_v5.ParseWithClaims, "", direct_github_com_golang_jwt_jwt_v5_ParseWithClaims)
	pkg.AddFunction("RegisterSigningMethod", github_com_golang_jwt_jwt_v5.RegisterSigningMethod, "", direct_github_com_golang_jwt_jwt_v5_RegisterSigningMethod)
	pkg.AddFunction("WithAudience", github_com_golang_jwt_jwt_v5.WithAudience, "", direct_github_com_golang_jwt_jwt_v5_WithAudience)
	pkg.AddFunction("WithExpirationRequired", github_com_golang_jwt_jwt_v5.WithExpirationRequired, "", direct_github_com_golang_jwt_jwt_v5_WithExpirationRequired)
	pkg.AddFunction("WithIssuedAt", github_com_golang_jwt_jwt_v5.WithIssuedAt, "", direct_github_com_golang_jwt_jwt_v5_WithIssuedAt)
	pkg.AddFunction("WithIssuer", github_com_golang_jwt_jwt_v5.WithIssuer, "", direct_github_com_golang_jwt_jwt_v5_WithIssuer)
	pkg.AddFunction("WithJSONNumber", github_com_golang_jwt_jwt_v5.WithJSONNumber, "", direct_github_com_golang_jwt_jwt_v5_WithJSONNumber)
	pkg.AddFunction("WithLeeway", github_com_golang_jwt_jwt_v5.WithLeeway, "", direct_github_com_golang_jwt_jwt_v5_WithLeeway)
	pkg.AddFunction("WithPaddingAllowed", github_com_golang_jwt_jwt_v5.WithPaddingAllowed, "", direct_github_com_golang_jwt_jwt_v5_WithPaddingAllowed)
	pkg.AddFunction("WithStrictDecoding", github_com_golang_jwt_jwt_v5.WithStrictDecoding, "", direct_github_com_golang_jwt_jwt_v5_WithStrictDecoding)
	pkg.AddFunction("WithSubject", github_com_golang_jwt_jwt_v5.WithSubject, "", direct_github_com_golang_jwt_jwt_v5_WithSubject)
	pkg.AddFunction("WithTimeFunc", github_com_golang_jwt_jwt_v5.WithTimeFunc, "", direct_github_com_golang_jwt_jwt_v5_WithTimeFunc)
	pkg.AddFunction("WithValidMethods", github_com_golang_jwt_jwt_v5.WithValidMethods, "", direct_github_com_golang_jwt_jwt_v5_WithValidMethods)
	pkg.AddFunction("WithoutClaimsValidation", github_com_golang_jwt_jwt_v5.WithoutClaimsValidation, "", direct_github_com_golang_jwt_jwt_v5_WithoutClaimsValidation)

	// Constants
	pkg.AddConstant("UnsafeAllowNoneSignatureType", github_com_golang_jwt_jwt_v5.UnsafeAllowNoneSignatureType, "")

	// Variables
	pkg.AddVariable("ErrECDSAVerification", &github_com_golang_jwt_jwt_v5.ErrECDSAVerification, "")
	pkg.AddVariable("ErrEd25519Verification", &github_com_golang_jwt_jwt_v5.ErrEd25519Verification, "")
	pkg.AddVariable("ErrHashUnavailable", &github_com_golang_jwt_jwt_v5.ErrHashUnavailable, "")
	pkg.AddVariable("ErrInvalidKey", &github_com_golang_jwt_jwt_v5.ErrInvalidKey, "")
	pkg.AddVariable("ErrInvalidKeyType", &github_com_golang_jwt_jwt_v5.ErrInvalidKeyType, "")
	pkg.AddVariable("ErrInvalidType", &github_com_golang_jwt_jwt_v5.ErrInvalidType, "")
	pkg.AddVariable("ErrKeyMustBePEMEncoded", &github_com_golang_jwt_jwt_v5.ErrKeyMustBePEMEncoded, "")
	pkg.AddVariable("ErrNotECPrivateKey", &github_com_golang_jwt_jwt_v5.ErrNotECPrivateKey, "")
	pkg.AddVariable("ErrNotECPublicKey", &github_com_golang_jwt_jwt_v5.ErrNotECPublicKey, "")
	pkg.AddVariable("ErrNotEdPrivateKey", &github_com_golang_jwt_jwt_v5.ErrNotEdPrivateKey, "")
	pkg.AddVariable("ErrNotEdPublicKey", &github_com_golang_jwt_jwt_v5.ErrNotEdPublicKey, "")
	pkg.AddVariable("ErrNotRSAPrivateKey", &github_com_golang_jwt_jwt_v5.ErrNotRSAPrivateKey, "")
	pkg.AddVariable("ErrNotRSAPublicKey", &github_com_golang_jwt_jwt_v5.ErrNotRSAPublicKey, "")
	pkg.AddVariable("ErrSignatureInvalid", &github_com_golang_jwt_jwt_v5.ErrSignatureInvalid, "")
	pkg.AddVariable("ErrTokenExpired", &github_com_golang_jwt_jwt_v5.ErrTokenExpired, "")
	pkg.AddVariable("ErrTokenInvalidAudience", &github_com_golang_jwt_jwt_v5.ErrTokenInvalidAudience, "")
	pkg.AddVariable("ErrTokenInvalidClaims", &github_com_golang_jwt_jwt_v5.ErrTokenInvalidClaims, "")
	pkg.AddVariable("ErrTokenInvalidId", &github_com_golang_jwt_jwt_v5.ErrTokenInvalidId, "")
	pkg.AddVariable("ErrTokenInvalidIssuer", &github_com_golang_jwt_jwt_v5.ErrTokenInvalidIssuer, "")
	pkg.AddVariable("ErrTokenInvalidSubject", &github_com_golang_jwt_jwt_v5.ErrTokenInvalidSubject, "")
	pkg.AddVariable("ErrTokenMalformed", &github_com_golang_jwt_jwt_v5.ErrTokenMalformed, "")
	pkg.AddVariable("ErrTokenNotValidYet", &github_com_golang_jwt_jwt_v5.ErrTokenNotValidYet, "")
	pkg.AddVariable("ErrTokenRequiredClaimMissing", &github_com_golang_jwt_jwt_v5.ErrTokenRequiredClaimMissing, "")
	pkg.AddVariable("ErrTokenSignatureInvalid", &github_com_golang_jwt_jwt_v5.ErrTokenSignatureInvalid, "")
	pkg.AddVariable("ErrTokenUnverifiable", &github_com_golang_jwt_jwt_v5.ErrTokenUnverifiable, "")
	pkg.AddVariable("ErrTokenUsedBeforeIssued", &github_com_golang_jwt_jwt_v5.ErrTokenUsedBeforeIssued, "")
	pkg.AddVariable("MarshalSingleStringAsArray", &github_com_golang_jwt_jwt_v5.MarshalSingleStringAsArray, "")
	pkg.AddVariable("NoneSignatureTypeDisallowedError", &github_com_golang_jwt_jwt_v5.NoneSignatureTypeDisallowedError, "")
	pkg.AddVariable("SigningMethodES256", &github_com_golang_jwt_jwt_v5.SigningMethodES256, "")
	pkg.AddVariable("SigningMethodES384", &github_com_golang_jwt_jwt_v5.SigningMethodES384, "")
	pkg.AddVariable("SigningMethodES512", &github_com_golang_jwt_jwt_v5.SigningMethodES512, "")
	pkg.AddVariable("SigningMethodEdDSA", &github_com_golang_jwt_jwt_v5.SigningMethodEdDSA, "")
	pkg.AddVariable("SigningMethodHS256", &github_com_golang_jwt_jwt_v5.SigningMethodHS256, "")
	pkg.AddVariable("SigningMethodHS384", &github_com_golang_jwt_jwt_v5.SigningMethodHS384, "")
	pkg.AddVariable("SigningMethodHS512", &github_com_golang_jwt_jwt_v5.SigningMethodHS512, "")
	pkg.AddVariable("SigningMethodNone", &github_com_golang_jwt_jwt_v5.SigningMethodNone, "")
	pkg.AddVariable("SigningMethodPS256", &github_com_golang_jwt_jwt_v5.SigningMethodPS256, "")
	pkg.AddVariable("SigningMethodPS384", &github_com_golang_jwt_jwt_v5.SigningMethodPS384, "")
	pkg.AddVariable("SigningMethodPS512", &github_com_golang_jwt_jwt_v5.SigningMethodPS512, "")
	pkg.AddVariable("SigningMethodRS256", &github_com_golang_jwt_jwt_v5.SigningMethodRS256, "")
	pkg.AddVariable("SigningMethodRS384", &github_com_golang_jwt_jwt_v5.SigningMethodRS384, "")
	pkg.AddVariable("SigningMethodRS512", &github_com_golang_jwt_jwt_v5.SigningMethodRS512, "")
	pkg.AddVariable("TimePrecision", &github_com_golang_jwt_jwt_v5.TimePrecision, "")

	// Types
	pkg.AddType("ClaimStrings", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.ClaimStrings)(nil)).Elem(), "")
	pkg.AddType("Claims", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.Claims)(nil)).Elem(), "")
	pkg.AddType("ClaimsValidator", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.ClaimsValidator)(nil)).Elem(), "")
	pkg.AddType("Keyfunc", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.Keyfunc)(nil)).Elem(), "")
	pkg.AddType("MapClaims", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.MapClaims)(nil)).Elem(), "")
	pkg.AddType("NumericDate", reflect.TypeOf(github_com_golang_jwt_jwt_v5.NumericDate{}), "")
	pkg.AddType("Parser", reflect.TypeOf(github_com_golang_jwt_jwt_v5.Parser{}), "")
	pkg.AddType("ParserOption", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.ParserOption)(nil)).Elem(), "")
	pkg.AddType("RegisteredClaims", reflect.TypeOf(github_com_golang_jwt_jwt_v5.RegisteredClaims{}), "")
	pkg.AddType("SigningMethod", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.SigningMethod)(nil)).Elem(), "")
	pkg.AddType("SigningMethodECDSA", reflect.TypeOf(github_com_golang_jwt_jwt_v5.SigningMethodECDSA{}), "")
	pkg.AddType("SigningMethodEd25519", reflect.TypeOf(github_com_golang_jwt_jwt_v5.SigningMethodEd25519{}), "")
	pkg.AddType("SigningMethodHMAC", reflect.TypeOf(github_com_golang_jwt_jwt_v5.SigningMethodHMAC{}), "")
	pkg.AddType("SigningMethodRSA", reflect.TypeOf(github_com_golang_jwt_jwt_v5.SigningMethodRSA{}), "")
	pkg.AddType("SigningMethodRSAPSS", reflect.TypeOf(github_com_golang_jwt_jwt_v5.SigningMethodRSAPSS{}), "")
	pkg.AddType("Token", reflect.TypeOf(github_com_golang_jwt_jwt_v5.Token{}), "")
	pkg.AddType("TokenOption", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.TokenOption)(nil)).Elem(), "")
	pkg.AddType("Validator", reflect.TypeOf(github_com_golang_jwt_jwt_v5.Validator{}), "")
	pkg.AddType("VerificationKey", reflect.TypeOf((*github_com_golang_jwt_jwt_v5.VerificationKey)(nil)).Elem(), "")
	pkg.AddType("VerificationKeySet", reflect.TypeOf(github_com_golang_jwt_jwt_v5.VerificationKeySet{}), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("ClaimStrings", "MarshalJSON", direct_method_github_com_golang_jwt_jwt_v5_ClaimStrings_MarshalJSON)
	pkg.AddMethodDirectCall("ClaimStrings", "UnmarshalJSON", direct_method_github_com_golang_jwt_jwt_v5_ClaimStrings_UnmarshalJSON)
	pkg.AddMethodDirectCall("MapClaims", "GetAudience", direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetAudience)
	pkg.AddMethodDirectCall("MapClaims", "GetExpirationTime", direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetExpirationTime)
	pkg.AddMethodDirectCall("MapClaims", "GetIssuedAt", direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetIssuedAt)
	pkg.AddMethodDirectCall("MapClaims", "GetIssuer", direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetIssuer)
	pkg.AddMethodDirectCall("MapClaims", "GetNotBefore", direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetNotBefore)
	pkg.AddMethodDirectCall("MapClaims", "GetSubject", direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetSubject)
	pkg.AddMethodDirectCall("NumericDate", "MarshalJSON", direct_method_github_com_golang_jwt_jwt_v5_NumericDate_MarshalJSON)
	pkg.AddMethodDirectCall("NumericDate", "UnmarshalJSON", direct_method_github_com_golang_jwt_jwt_v5_NumericDate_UnmarshalJSON)
	pkg.AddMethodDirectCall("Parser", "DecodeSegment", direct_method_github_com_golang_jwt_jwt_v5_Parser_DecodeSegment)
	pkg.AddMethodDirectCall("Parser", "Parse", direct_method_github_com_golang_jwt_jwt_v5_Parser_Parse)
	pkg.AddMethodDirectCall("Parser", "ParseUnverified", direct_method_github_com_golang_jwt_jwt_v5_Parser_ParseUnverified)
	pkg.AddMethodDirectCall("Parser", "ParseWithClaims", direct_method_github_com_golang_jwt_jwt_v5_Parser_ParseWithClaims)
	pkg.AddMethodDirectCall("RegisteredClaims", "GetAudience", direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetAudience)
	pkg.AddMethodDirectCall("RegisteredClaims", "GetExpirationTime", direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetExpirationTime)
	pkg.AddMethodDirectCall("RegisteredClaims", "GetIssuedAt", direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetIssuedAt)
	pkg.AddMethodDirectCall("RegisteredClaims", "GetIssuer", direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetIssuer)
	pkg.AddMethodDirectCall("RegisteredClaims", "GetNotBefore", direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetNotBefore)
	pkg.AddMethodDirectCall("RegisteredClaims", "GetSubject", direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetSubject)
	pkg.AddMethodDirectCall("SigningMethodECDSA", "Alg", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodECDSA_Alg)
	pkg.AddMethodDirectCall("SigningMethodECDSA", "Sign", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodECDSA_Sign)
	pkg.AddMethodDirectCall("SigningMethodECDSA", "Verify", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodECDSA_Verify)
	pkg.AddMethodDirectCall("SigningMethodEd25519", "Alg", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodEd25519_Alg)
	pkg.AddMethodDirectCall("SigningMethodEd25519", "Sign", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodEd25519_Sign)
	pkg.AddMethodDirectCall("SigningMethodEd25519", "Verify", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodEd25519_Verify)
	pkg.AddMethodDirectCall("SigningMethodHMAC", "Alg", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodHMAC_Alg)
	pkg.AddMethodDirectCall("SigningMethodHMAC", "Sign", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodHMAC_Sign)
	pkg.AddMethodDirectCall("SigningMethodHMAC", "Verify", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodHMAC_Verify)
	pkg.AddMethodDirectCall("SigningMethodRSA", "Alg", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSA_Alg)
	pkg.AddMethodDirectCall("SigningMethodRSA", "Sign", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSA_Sign)
	pkg.AddMethodDirectCall("SigningMethodRSA", "Verify", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSA_Verify)
	pkg.AddMethodDirectCall("SigningMethodRSAPSS", "Sign", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSAPSS_Sign)
	pkg.AddMethodDirectCall("SigningMethodRSAPSS", "Verify", direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSAPSS_Verify)
	pkg.AddMethodDirectCall("Token", "EncodeSegment", direct_method_github_com_golang_jwt_jwt_v5_Token_EncodeSegment)
	pkg.AddMethodDirectCall("Token", "SignedString", direct_method_github_com_golang_jwt_jwt_v5_Token_SignedString)
	pkg.AddMethodDirectCall("Token", "SigningString", direct_method_github_com_golang_jwt_jwt_v5_Token_SigningString)
	pkg.AddMethodDirectCall("Validator", "Validate", direct_method_github_com_golang_jwt_jwt_v5_Validator_Validate)

}

func direct_github_com_golang_jwt_jwt_v5_GetAlgorithms(args []value.Value) value.Value {
	return value.FromInterface(github_com_golang_jwt_jwt_v5.GetAlgorithms())
}

func direct_github_com_golang_jwt_jwt_v5_GetSigningMethod(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(github_com_golang_jwt_jwt_v5.GetSigningMethod(a0))
}

func direct_github_com_golang_jwt_jwt_v5_New(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_golang_jwt_jwt_v5.SigningMethod)
	varArgs := make([]github_com_golang_jwt_jwt_v5.TokenOption, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(github_com_golang_jwt_jwt_v5.TokenOption))
		}
	}
	return value.FromInterface(github_com_golang_jwt_jwt_v5.New(a0, varArgs...))
}

func direct_github_com_golang_jwt_jwt_v5_NewNumericDate(args []value.Value) value.Value {
	a0 := args[0].Interface().(time.Time)
	return value.FromInterface(github_com_golang_jwt_jwt_v5.NewNumericDate(a0))
}

func direct_github_com_golang_jwt_jwt_v5_NewParser(args []value.Value) value.Value {
	varArgs := make([]github_com_golang_jwt_jwt_v5.ParserOption, 0, len(args)-0)
	for i := 0; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(github_com_golang_jwt_jwt_v5.ParserOption))
		}
	}
	return value.FromInterface(github_com_golang_jwt_jwt_v5.NewParser(varArgs...))
}

func direct_github_com_golang_jwt_jwt_v5_NewValidator(args []value.Value) value.Value {
	varArgs := make([]github_com_golang_jwt_jwt_v5.ParserOption, 0, len(args)-0)
	for i := 0; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(github_com_golang_jwt_jwt_v5.ParserOption))
		}
	}
	return value.FromInterface(github_com_golang_jwt_jwt_v5.NewValidator(varArgs...))
}

func direct_github_com_golang_jwt_jwt_v5_NewWithClaims(args []value.Value) value.Value {
	a0 := args[0].Interface().(github_com_golang_jwt_jwt_v5.SigningMethod)
	a1 := args[1].Interface().(github_com_golang_jwt_jwt_v5.Claims)
	varArgs := make([]github_com_golang_jwt_jwt_v5.TokenOption, 0, len(args)-2)
	for i := 2; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(github_com_golang_jwt_jwt_v5.TokenOption))
		}
	}
	return value.FromInterface(github_com_golang_jwt_jwt_v5.NewWithClaims(a0, a1, varArgs...))
}

func direct_github_com_golang_jwt_jwt_v5_Parse(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].Interface().(github_com_golang_jwt_jwt_v5.Keyfunc)
	varArgs := make([]github_com_golang_jwt_jwt_v5.ParserOption, 0, len(args)-2)
	for i := 2; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(github_com_golang_jwt_jwt_v5.ParserOption))
		}
	}
	r0, r1 := github_com_golang_jwt_jwt_v5.Parse(a0, a1, varArgs...)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_ParseECPrivateKeyFromPEM(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := github_com_golang_jwt_jwt_v5.ParseECPrivateKeyFromPEM(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_ParseECPublicKeyFromPEM(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := github_com_golang_jwt_jwt_v5.ParseECPublicKeyFromPEM(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_ParseEdPrivateKeyFromPEM(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := github_com_golang_jwt_jwt_v5.ParseEdPrivateKeyFromPEM(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_ParseEdPublicKeyFromPEM(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := github_com_golang_jwt_jwt_v5.ParseEdPublicKeyFromPEM(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_ParseRSAPrivateKeyFromPEM(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := github_com_golang_jwt_jwt_v5.ParseRSAPrivateKeyFromPEM(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_ParseRSAPrivateKeyFromPEMWithPassword(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a1 := args[1].String()
	r0, r1 := github_com_golang_jwt_jwt_v5.ParseRSAPrivateKeyFromPEMWithPassword(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_ParseRSAPublicKeyFromPEM(args []value.Value) value.Value {
	a0 := func() []byte {
		if b, ok := (args[0]).Bytes(); ok {
			return b
		}
		v := (args[0]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	r0, r1 := github_com_golang_jwt_jwt_v5.ParseRSAPublicKeyFromPEM(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_ParseWithClaims(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].Interface().(github_com_golang_jwt_jwt_v5.Claims)
	a2 := args[2].Interface().(github_com_golang_jwt_jwt_v5.Keyfunc)
	varArgs := make([]github_com_golang_jwt_jwt_v5.ParserOption, 0, len(args)-3)
	for i := 3; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(github_com_golang_jwt_jwt_v5.ParserOption))
		}
	}
	r0, r1 := github_com_golang_jwt_jwt_v5.ParseWithClaims(a0, a1, a2, varArgs...)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_golang_jwt_jwt_v5_RegisterSigningMethod(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].Interface().(func() github_com_golang_jwt_jwt_v5.SigningMethod)
	github_com_golang_jwt_jwt_v5.RegisterSigningMethod(a0, a1)
	return value.MakeNil()
}

func direct_github_com_golang_jwt_jwt_v5_WithAudience(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithAudience(a0))
}

func direct_github_com_golang_jwt_jwt_v5_WithExpirationRequired(args []value.Value) value.Value {
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithExpirationRequired())
}

func direct_github_com_golang_jwt_jwt_v5_WithIssuedAt(args []value.Value) value.Value {
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithIssuedAt())
}

func direct_github_com_golang_jwt_jwt_v5_WithIssuer(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithIssuer(a0))
}

func direct_github_com_golang_jwt_jwt_v5_WithJSONNumber(args []value.Value) value.Value {
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithJSONNumber())
}

func direct_github_com_golang_jwt_jwt_v5_WithLeeway(args []value.Value) value.Value {
	a0 := time.Duration(args[0].Int())
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithLeeway(a0))
}

func direct_github_com_golang_jwt_jwt_v5_WithPaddingAllowed(args []value.Value) value.Value {
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithPaddingAllowed())
}

func direct_github_com_golang_jwt_jwt_v5_WithStrictDecoding(args []value.Value) value.Value {
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithStrictDecoding())
}

func direct_github_com_golang_jwt_jwt_v5_WithSubject(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithSubject(a0))
}

func direct_github_com_golang_jwt_jwt_v5_WithTimeFunc(args []value.Value) value.Value {
	a0 := args[0].Interface().(func() time.Time)
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithTimeFunc(a0))
}

func direct_github_com_golang_jwt_jwt_v5_WithValidMethods(args []value.Value) value.Value {
	a0 := args[0].Interface().([]string)
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithValidMethods(a0))
}

func direct_github_com_golang_jwt_jwt_v5_WithoutClaimsValidation(args []value.Value) value.Value {
	return value.FromInterface(github_com_golang_jwt_jwt_v5.WithoutClaimsValidation())
}

func direct_method_github_com_golang_jwt_jwt_v5_ClaimStrings_MarshalJSON(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.ClaimStrings)
	r0, r1 := recv.MarshalJSON()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_ClaimStrings_UnmarshalJSON(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.ClaimStrings)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.FromInterface(recv.UnmarshalJSON(a0))
}

func direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetAudience(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.MapClaims)
	r0, r1 := recv.GetAudience()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetExpirationTime(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.MapClaims)
	r0, r1 := recv.GetExpirationTime()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetIssuedAt(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.MapClaims)
	r0, r1 := recv.GetIssuedAt()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetIssuer(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.MapClaims)
	r0, r1 := recv.GetIssuer()
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetNotBefore(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.MapClaims)
	r0, r1 := recv.GetNotBefore()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_MapClaims_GetSubject(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.MapClaims)
	r0, r1 := recv.GetSubject()
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_NumericDate_MarshalJSON(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.NumericDate)
	r0, r1 := recv.MarshalJSON()
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_NumericDate_UnmarshalJSON(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.NumericDate)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.FromInterface(recv.UnmarshalJSON(a0))
}

func direct_method_github_com_golang_jwt_jwt_v5_Parser_DecodeSegment(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.Parser)
	a0 := args[1].String()
	r0, r1 := recv.DecodeSegment(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_Parser_Parse(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.Parser)
	a0 := args[1].String()
	a1 := args[2].Interface().(github_com_golang_jwt_jwt_v5.Keyfunc)
	r0, r1 := recv.Parse(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_Parser_ParseUnverified(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.Parser)
	a0 := args[1].String()
	a1 := args[2].Interface().(github_com_golang_jwt_jwt_v5.Claims)
	r0, r1, r2 := recv.ParseUnverified(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1), value.FromInterface(r2)})
}

func direct_method_github_com_golang_jwt_jwt_v5_Parser_ParseWithClaims(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.Parser)
	a0 := args[1].String()
	a1 := args[2].Interface().(github_com_golang_jwt_jwt_v5.Claims)
	a2 := args[3].Interface().(github_com_golang_jwt_jwt_v5.Keyfunc)
	r0, r1 := recv.ParseWithClaims(a0, a1, a2)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetAudience(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.RegisteredClaims)
	r0, r1 := recv.GetAudience()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetExpirationTime(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.RegisteredClaims)
	r0, r1 := recv.GetExpirationTime()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetIssuedAt(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.RegisteredClaims)
	r0, r1 := recv.GetIssuedAt()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetIssuer(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.RegisteredClaims)
	r0, r1 := recv.GetIssuer()
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetNotBefore(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.RegisteredClaims)
	r0, r1 := recv.GetNotBefore()
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_RegisteredClaims_GetSubject(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_golang_jwt_jwt_v5.RegisteredClaims)
	r0, r1 := recv.GetSubject()
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodECDSA_Alg(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodECDSA)
	return value.MakeString(string(recv.Alg()))
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodECDSA_Sign(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodECDSA)
	a0 := args[1].String()
	a1 := args[2].Interface()
	r0, r1 := recv.Sign(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodECDSA_Verify(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodECDSA)
	a0 := args[1].String()
	a1 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a2 := args[3].Interface()
	return value.FromInterface(recv.Verify(a0, a1, a2))
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodEd25519_Alg(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodEd25519)
	return value.MakeString(string(recv.Alg()))
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodEd25519_Sign(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodEd25519)
	a0 := args[1].String()
	a1 := args[2].Interface()
	r0, r1 := recv.Sign(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodEd25519_Verify(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodEd25519)
	a0 := args[1].String()
	a1 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a2 := args[3].Interface()
	return value.FromInterface(recv.Verify(a0, a1, a2))
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodHMAC_Alg(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodHMAC)
	return value.MakeString(string(recv.Alg()))
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodHMAC_Sign(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodHMAC)
	a0 := args[1].String()
	a1 := args[2].Interface()
	r0, r1 := recv.Sign(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodHMAC_Verify(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodHMAC)
	a0 := args[1].String()
	a1 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a2 := args[3].Interface()
	return value.FromInterface(recv.Verify(a0, a1, a2))
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSA_Alg(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodRSA)
	return value.MakeString(string(recv.Alg()))
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSA_Sign(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodRSA)
	a0 := args[1].String()
	a1 := args[2].Interface()
	r0, r1 := recv.Sign(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSA_Verify(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodRSA)
	a0 := args[1].String()
	a1 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a2 := args[3].Interface()
	return value.FromInterface(recv.Verify(a0, a1, a2))
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSAPSS_Sign(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodRSAPSS)
	a0 := args[1].String()
	a1 := args[2].Interface()
	r0, r1 := recv.Sign(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeBytes([]byte(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_SigningMethodRSAPSS_Verify(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.SigningMethodRSAPSS)
	a0 := args[1].String()
	a1 := func() []byte {
		if b, ok := (args[2]).Bytes(); ok {
			return b
		}
		v := (args[2]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	a2 := args[3].Interface()
	return value.FromInterface(recv.Verify(a0, a1, a2))
}

func direct_method_github_com_golang_jwt_jwt_v5_Token_EncodeSegment(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.Token)
	a0 := func() []byte {
		if b, ok := (args[1]).Bytes(); ok {
			return b
		}
		v := (args[1]).Interface()
		if v == nil {
			return nil
		}
		return v.([]byte)
	}()
	return value.MakeString(string(recv.EncodeSegment(a0)))
}

func direct_method_github_com_golang_jwt_jwt_v5_Token_SignedString(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.Token)
	a0 := args[1].Interface()
	r0, r1 := recv.SignedString(a0)
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_Token_SigningString(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.Token)
	r0, r1 := recv.SigningString()
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_method_github_com_golang_jwt_jwt_v5_Validator_Validate(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_golang_jwt_jwt_v5.Validator)
	a0 := args[1].Interface().(github_com_golang_jwt_jwt_v5.Claims)
	return value.FromInterface(recv.Validate(a0))
}
