// Code generated by gig/gentool. DO NOT EDIT.
package packages

import (
	github_com_asaskevich_govalidator "github.com/asaskevich/govalidator"
	"reflect"

	"github.com/t04dJ14n9/gig/importer"
	"github.com/t04dJ14n9/gig/model/value"
)

func init() {
	pkg := importer.RegisterPackage("github.com/asaskevich/govalidator", "govalidator")

	// Functions
	pkg.AddFunction("Abs", github_com_asaskevich_govalidator.Abs, "", direct_github_com_asaskevich_govalidator_Abs)
	pkg.AddFunction("BlackList", github_com_asaskevich_govalidator.BlackList, "", direct_github_com_asaskevich_govalidator_BlackList)
	pkg.AddFunction("ByteLength", github_com_asaskevich_govalidator.ByteLength, "", direct_github_com_asaskevich_govalidator_ByteLength)
	pkg.AddFunction("CamelCaseToUnderscore", github_com_asaskevich_govalidator.CamelCaseToUnderscore, "", direct_github_com_asaskevich_govalidator_CamelCaseToUnderscore)
	pkg.AddFunction("Contains", github_com_asaskevich_govalidator.Contains, "", direct_github_com_asaskevich_govalidator_Contains)
	pkg.AddFunction("Count", github_com_asaskevich_govalidator.Count, "", nil)
	pkg.AddFunction("Each", github_com_asaskevich_govalidator.Each, "", nil)
	pkg.AddFunction("ErrorByField", github_com_asaskevich_govalidator.ErrorByField, "", direct_github_com_asaskevich_govalidator_ErrorByField)
	pkg.AddFunction("ErrorsByField", github_com_asaskevich_govalidator.ErrorsByField, "", direct_github_com_asaskevich_govalidator_ErrorsByField)
	pkg.AddFunction("Every", github_com_asaskevich_govalidator.Every, "", nil)
	pkg.AddFunction("Filter", github_com_asaskevich_govalidator.Filter, "", nil)
	pkg.AddFunction("Find", github_com_asaskevich_govalidator.Find, "", nil)
	pkg.AddFunction("GetLine", github_com_asaskevich_govalidator.GetLine, "", direct_github_com_asaskevich_govalidator_GetLine)
	pkg.AddFunction("GetLines", github_com_asaskevich_govalidator.GetLines, "", direct_github_com_asaskevich_govalidator_GetLines)
	pkg.AddFunction("HasLowerCase", github_com_asaskevich_govalidator.HasLowerCase, "", direct_github_com_asaskevich_govalidator_HasLowerCase)
	pkg.AddFunction("HasUpperCase", github_com_asaskevich_govalidator.HasUpperCase, "", direct_github_com_asaskevich_govalidator_HasUpperCase)
	pkg.AddFunction("HasWhitespace", github_com_asaskevich_govalidator.HasWhitespace, "", direct_github_com_asaskevich_govalidator_HasWhitespace)
	pkg.AddFunction("HasWhitespaceOnly", github_com_asaskevich_govalidator.HasWhitespaceOnly, "", direct_github_com_asaskevich_govalidator_HasWhitespaceOnly)
	pkg.AddFunction("InRange", github_com_asaskevich_govalidator.InRange, "", direct_github_com_asaskevich_govalidator_InRange)
	pkg.AddFunction("InRangeFloat32", github_com_asaskevich_govalidator.InRangeFloat32, "", direct_github_com_asaskevich_govalidator_InRangeFloat32)
	pkg.AddFunction("InRangeFloat64", github_com_asaskevich_govalidator.InRangeFloat64, "", direct_github_com_asaskevich_govalidator_InRangeFloat64)
	pkg.AddFunction("InRangeInt", github_com_asaskevich_govalidator.InRangeInt, "", direct_github_com_asaskevich_govalidator_InRangeInt)
	pkg.AddFunction("IsASCII", github_com_asaskevich_govalidator.IsASCII, "", direct_github_com_asaskevich_govalidator_IsASCII)
	pkg.AddFunction("IsAlpha", github_com_asaskevich_govalidator.IsAlpha, "", direct_github_com_asaskevich_govalidator_IsAlpha)
	pkg.AddFunction("IsAlphanumeric", github_com_asaskevich_govalidator.IsAlphanumeric, "", direct_github_com_asaskevich_govalidator_IsAlphanumeric)
	pkg.AddFunction("IsBase64", github_com_asaskevich_govalidator.IsBase64, "", direct_github_com_asaskevich_govalidator_IsBase64)
	pkg.AddFunction("IsByteLength", github_com_asaskevich_govalidator.IsByteLength, "", direct_github_com_asaskevich_govalidator_IsByteLength)
	pkg.AddFunction("IsCIDR", github_com_asaskevich_govalidator.IsCIDR, "", direct_github_com_asaskevich_govalidator_IsCIDR)
	pkg.AddFunction("IsCRC32", github_com_asaskevich_govalidator.IsCRC32, "", direct_github_com_asaskevich_govalidator_IsCRC32)
	pkg.AddFunction("IsCRC32b", github_com_asaskevich_govalidator.IsCRC32b, "", direct_github_com_asaskevich_govalidator_IsCRC32b)
	pkg.AddFunction("IsCreditCard", github_com_asaskevich_govalidator.IsCreditCard, "", direct_github_com_asaskevich_govalidator_IsCreditCard)
	pkg.AddFunction("IsDNSName", github_com_asaskevich_govalidator.IsDNSName, "", direct_github_com_asaskevich_govalidator_IsDNSName)
	pkg.AddFunction("IsDataURI", github_com_asaskevich_govalidator.IsDataURI, "", direct_github_com_asaskevich_govalidator_IsDataURI)
	pkg.AddFunction("IsDialString", github_com_asaskevich_govalidator.IsDialString, "", direct_github_com_asaskevich_govalidator_IsDialString)
	pkg.AddFunction("IsDivisibleBy", github_com_asaskevich_govalidator.IsDivisibleBy, "", direct_github_com_asaskevich_govalidator_IsDivisibleBy)
	pkg.AddFunction("IsE164", github_com_asaskevich_govalidator.IsE164, "", direct_github_com_asaskevich_govalidator_IsE164)
	pkg.AddFunction("IsEmail", github_com_asaskevich_govalidator.IsEmail, "", direct_github_com_asaskevich_govalidator_IsEmail)
	pkg.AddFunction("IsExistingEmail", github_com_asaskevich_govalidator.IsExistingEmail, "", direct_github_com_asaskevich_govalidator_IsExistingEmail)
	pkg.AddFunction("IsFilePath", github_com_asaskevich_govalidator.IsFilePath, "", direct_github_com_asaskevich_govalidator_IsFilePath)
	pkg.AddFunction("IsFloat", github_com_asaskevich_govalidator.IsFloat, "", direct_github_com_asaskevich_govalidator_IsFloat)
	pkg.AddFunction("IsFullWidth", github_com_asaskevich_govalidator.IsFullWidth, "", direct_github_com_asaskevich_govalidator_IsFullWidth)
	pkg.AddFunction("IsHalfWidth", github_com_asaskevich_govalidator.IsHalfWidth, "", direct_github_com_asaskevich_govalidator_IsHalfWidth)
	pkg.AddFunction("IsHash", github_com_asaskevich_govalidator.IsHash, "", direct_github_com_asaskevich_govalidator_IsHash)
	pkg.AddFunction("IsHexadecimal", github_com_asaskevich_govalidator.IsHexadecimal, "", direct_github_com_asaskevich_govalidator_IsHexadecimal)
	pkg.AddFunction("IsHexcolor", github_com_asaskevich_govalidator.IsHexcolor, "", direct_github_com_asaskevich_govalidator_IsHexcolor)
	pkg.AddFunction("IsHost", github_com_asaskevich_govalidator.IsHost, "", direct_github_com_asaskevich_govalidator_IsHost)
	pkg.AddFunction("IsIMEI", github_com_asaskevich_govalidator.IsIMEI, "", direct_github_com_asaskevich_govalidator_IsIMEI)
	pkg.AddFunction("IsIMSI", github_com_asaskevich_govalidator.IsIMSI, "", direct_github_com_asaskevich_govalidator_IsIMSI)
	pkg.AddFunction("IsIP", github_com_asaskevich_govalidator.IsIP, "", direct_github_com_asaskevich_govalidator_IsIP)
	pkg.AddFunction("IsIPv4", github_com_asaskevich_govalidator.IsIPv4, "", direct_github_com_asaskevich_govalidator_IsIPv4)
	pkg.AddFunction("IsIPv6", github_com_asaskevich_govalidator.IsIPv6, "", direct_github_com_asaskevich_govalidator_IsIPv6)
	pkg.AddFunction("IsISBN", github_com_asaskevich_govalidator.IsISBN, "", direct_github_com_asaskevich_govalidator_IsISBN)
	pkg.AddFunction("IsISBN10", github_com_asaskevich_govalidator.IsISBN10, "", direct_github_com_asaskevich_govalidator_IsISBN10)
	pkg.AddFunction("IsISBN13", github_com_asaskevich_govalidator.IsISBN13, "", direct_github_com_asaskevich_govalidator_IsISBN13)
	pkg.AddFunction("IsISO3166Alpha2", github_com_asaskevich_govalidator.IsISO3166Alpha2, "", direct_github_com_asaskevich_govalidator_IsISO3166Alpha2)
	pkg.AddFunction("IsISO3166Alpha3", github_com_asaskevich_govalidator.IsISO3166Alpha3, "", direct_github_com_asaskevich_govalidator_IsISO3166Alpha3)
	pkg.AddFunction("IsISO4217", github_com_asaskevich_govalidator.IsISO4217, "", direct_github_com_asaskevich_govalidator_IsISO4217)
	pkg.AddFunction("IsISO693Alpha2", github_com_asaskevich_govalidator.IsISO693Alpha2, "", direct_github_com_asaskevich_govalidator_IsISO693Alpha2)
	pkg.AddFunction("IsISO693Alpha3b", github_com_asaskevich_govalidator.IsISO693Alpha3b, "", direct_github_com_asaskevich_govalidator_IsISO693Alpha3b)
	pkg.AddFunction("IsIn", github_com_asaskevich_govalidator.IsIn, "", direct_github_com_asaskevich_govalidator_IsIn)
	pkg.AddFunction("IsInRaw", github_com_asaskevich_govalidator.IsInRaw, "", direct_github_com_asaskevich_govalidator_IsInRaw)
	pkg.AddFunction("IsInt", github_com_asaskevich_govalidator.IsInt, "", direct_github_com_asaskevich_govalidator_IsInt)
	pkg.AddFunction("IsJSON", github_com_asaskevich_govalidator.IsJSON, "", direct_github_com_asaskevich_govalidator_IsJSON)
	pkg.AddFunction("IsLatitude", github_com_asaskevich_govalidator.IsLatitude, "", direct_github_com_asaskevich_govalidator_IsLatitude)
	pkg.AddFunction("IsLongitude", github_com_asaskevich_govalidator.IsLongitude, "", direct_github_com_asaskevich_govalidator_IsLongitude)
	pkg.AddFunction("IsLowerCase", github_com_asaskevich_govalidator.IsLowerCase, "", direct_github_com_asaskevich_govalidator_IsLowerCase)
	pkg.AddFunction("IsMAC", github_com_asaskevich_govalidator.IsMAC, "", direct_github_com_asaskevich_govalidator_IsMAC)
	pkg.AddFunction("IsMD4", github_com_asaskevich_govalidator.IsMD4, "", direct_github_com_asaskevich_govalidator_IsMD4)
	pkg.AddFunction("IsMD5", github_com_asaskevich_govalidator.IsMD5, "", direct_github_com_asaskevich_govalidator_IsMD5)
	pkg.AddFunction("IsMagnetURI", github_com_asaskevich_govalidator.IsMagnetURI, "", direct_github_com_asaskevich_govalidator_IsMagnetURI)
	pkg.AddFunction("IsMongoID", github_com_asaskevich_govalidator.IsMongoID, "", direct_github_com_asaskevich_govalidator_IsMongoID)
	pkg.AddFunction("IsMultibyte", github_com_asaskevich_govalidator.IsMultibyte, "", direct_github_com_asaskevich_govalidator_IsMultibyte)
	pkg.AddFunction("IsNatural", github_com_asaskevich_govalidator.IsNatural, "", direct_github_com_asaskevich_govalidator_IsNatural)
	pkg.AddFunction("IsNegative", github_com_asaskevich_govalidator.IsNegative, "", direct_github_com_asaskevich_govalidator_IsNegative)
	pkg.AddFunction("IsNonNegative", github_com_asaskevich_govalidator.IsNonNegative, "", direct_github_com_asaskevich_govalidator_IsNonNegative)
	pkg.AddFunction("IsNonPositive", github_com_asaskevich_govalidator.IsNonPositive, "", direct_github_com_asaskevich_govalidator_IsNonPositive)
	pkg.AddFunction("IsNotNull", github_com_asaskevich_govalidator.IsNotNull, "", direct_github_com_asaskevich_govalidator_IsNotNull)
	pkg.AddFunction("IsNull", github_com_asaskevich_govalidator.IsNull, "", direct_github_com_asaskevich_govalidator_IsNull)
	pkg.AddFunction("IsNumeric", github_com_asaskevich_govalidator.IsNumeric, "", direct_github_com_asaskevich_govalidator_IsNumeric)
	pkg.AddFunction("IsPort", github_com_asaskevich_govalidator.IsPort, "", direct_github_com_asaskevich_govalidator_IsPort)
	pkg.AddFunction("IsPositive", github_com_asaskevich_govalidator.IsPositive, "", direct_github_com_asaskevich_govalidator_IsPositive)
	pkg.AddFunction("IsPrintableASCII", github_com_asaskevich_govalidator.IsPrintableASCII, "", direct_github_com_asaskevich_govalidator_IsPrintableASCII)
	pkg.AddFunction("IsRFC3339", github_com_asaskevich_govalidator.IsRFC3339, "", direct_github_com_asaskevich_govalidator_IsRFC3339)
	pkg.AddFunction("IsRFC3339WithoutZone", github_com_asaskevich_govalidator.IsRFC3339WithoutZone, "", direct_github_com_asaskevich_govalidator_IsRFC3339WithoutZone)
	pkg.AddFunction("IsRGBcolor", github_com_asaskevich_govalidator.IsRGBcolor, "", direct_github_com_asaskevich_govalidator_IsRGBcolor)
	pkg.AddFunction("IsRegex", github_com_asaskevich_govalidator.IsRegex, "", direct_github_com_asaskevich_govalidator_IsRegex)
	pkg.AddFunction("IsRequestURI", github_com_asaskevich_govalidator.IsRequestURI, "", direct_github_com_asaskevich_govalidator_IsRequestURI)
	pkg.AddFunction("IsRequestURL", github_com_asaskevich_govalidator.IsRequestURL, "", direct_github_com_asaskevich_govalidator_IsRequestURL)
	pkg.AddFunction("IsRipeMD128", github_com_asaskevich_govalidator.IsRipeMD128, "", direct_github_com_asaskevich_govalidator_IsRipeMD128)
	pkg.AddFunction("IsRipeMD160", github_com_asaskevich_govalidator.IsRipeMD160, "", direct_github_com_asaskevich_govalidator_IsRipeMD160)
	pkg.AddFunction("IsRsaPub", github_com_asaskevich_govalidator.IsRsaPub, "", direct_github_com_asaskevich_govalidator_IsRsaPub)
	pkg.AddFunction("IsRsaPublicKey", github_com_asaskevich_govalidator.IsRsaPublicKey, "", direct_github_com_asaskevich_govalidator_IsRsaPublicKey)
	pkg.AddFunction("IsSHA1", github_com_asaskevich_govalidator.IsSHA1, "", direct_github_com_asaskevich_govalidator_IsSHA1)
	pkg.AddFunction("IsSHA256", github_com_asaskevich_govalidator.IsSHA256, "", direct_github_com_asaskevich_govalidator_IsSHA256)
	pkg.AddFunction("IsSHA3224", github_com_asaskevich_govalidator.IsSHA3224, "", direct_github_com_asaskevich_govalidator_IsSHA3224)
	pkg.AddFunction("IsSHA3256", github_com_asaskevich_govalidator.IsSHA3256, "", direct_github_com_asaskevich_govalidator_IsSHA3256)
	pkg.AddFunction("IsSHA3384", github_com_asaskevich_govalidator.IsSHA3384, "", direct_github_com_asaskevich_govalidator_IsSHA3384)
	pkg.AddFunction("IsSHA3512", github_com_asaskevich_govalidator.IsSHA3512, "", direct_github_com_asaskevich_govalidator_IsSHA3512)
	pkg.AddFunction("IsSHA384", github_com_asaskevich_govalidator.IsSHA384, "", direct_github_com_asaskevich_govalidator_IsSHA384)
	pkg.AddFunction("IsSHA512", github_com_asaskevich_govalidator.IsSHA512, "", direct_github_com_asaskevich_govalidator_IsSHA512)
	pkg.AddFunction("IsSSN", github_com_asaskevich_govalidator.IsSSN, "", direct_github_com_asaskevich_govalidator_IsSSN)
	pkg.AddFunction("IsSemver", github_com_asaskevich_govalidator.IsSemver, "", direct_github_com_asaskevich_govalidator_IsSemver)
	pkg.AddFunction("IsTiger128", github_com_asaskevich_govalidator.IsTiger128, "", direct_github_com_asaskevich_govalidator_IsTiger128)
	pkg.AddFunction("IsTiger160", github_com_asaskevich_govalidator.IsTiger160, "", direct_github_com_asaskevich_govalidator_IsTiger160)
	pkg.AddFunction("IsTiger192", github_com_asaskevich_govalidator.IsTiger192, "", direct_github_com_asaskevich_govalidator_IsTiger192)
	pkg.AddFunction("IsTime", github_com_asaskevich_govalidator.IsTime, "", direct_github_com_asaskevich_govalidator_IsTime)
	pkg.AddFunction("IsType", github_com_asaskevich_govalidator.IsType, "", direct_github_com_asaskevich_govalidator_IsType)
	pkg.AddFunction("IsULID", github_com_asaskevich_govalidator.IsULID, "", direct_github_com_asaskevich_govalidator_IsULID)
	pkg.AddFunction("IsURL", github_com_asaskevich_govalidator.IsURL, "", direct_github_com_asaskevich_govalidator_IsURL)
	pkg.AddFunction("IsUTFDigit", github_com_asaskevich_govalidator.IsUTFDigit, "", direct_github_com_asaskevich_govalidator_IsUTFDigit)
	pkg.AddFunction("IsUTFLetter", github_com_asaskevich_govalidator.IsUTFLetter, "", direct_github_com_asaskevich_govalidator_IsUTFLetter)
	pkg.AddFunction("IsUTFLetterNumeric", github_com_asaskevich_govalidator.IsUTFLetterNumeric, "", direct_github_com_asaskevich_govalidator_IsUTFLetterNumeric)
	pkg.AddFunction("IsUTFNumeric", github_com_asaskevich_govalidator.IsUTFNumeric, "", direct_github_com_asaskevich_govalidator_IsUTFNumeric)
	pkg.AddFunction("IsUUID", github_com_asaskevich_govalidator.IsUUID, "", direct_github_com_asaskevich_govalidator_IsUUID)
	pkg.AddFunction("IsUUIDv3", github_com_asaskevich_govalidator.IsUUIDv3, "", direct_github_com_asaskevich_govalidator_IsUUIDv3)
	pkg.AddFunction("IsUUIDv4", github_com_asaskevich_govalidator.IsUUIDv4, "", direct_github_com_asaskevich_govalidator_IsUUIDv4)
	pkg.AddFunction("IsUUIDv5", github_com_asaskevich_govalidator.IsUUIDv5, "", direct_github_com_asaskevich_govalidator_IsUUIDv5)
	pkg.AddFunction("IsUnixFilePath", github_com_asaskevich_govalidator.IsUnixFilePath, "", direct_github_com_asaskevich_govalidator_IsUnixFilePath)
	pkg.AddFunction("IsUnixTime", github_com_asaskevich_govalidator.IsUnixTime, "", direct_github_com_asaskevich_govalidator_IsUnixTime)
	pkg.AddFunction("IsUpperCase", github_com_asaskevich_govalidator.IsUpperCase, "", direct_github_com_asaskevich_govalidator_IsUpperCase)
	pkg.AddFunction("IsVariableWidth", github_com_asaskevich_govalidator.IsVariableWidth, "", direct_github_com_asaskevich_govalidator_IsVariableWidth)
	pkg.AddFunction("IsWhole", github_com_asaskevich_govalidator.IsWhole, "", direct_github_com_asaskevich_govalidator_IsWhole)
	pkg.AddFunction("IsWinFilePath", github_com_asaskevich_govalidator.IsWinFilePath, "", direct_github_com_asaskevich_govalidator_IsWinFilePath)
	pkg.AddFunction("LeftTrim", github_com_asaskevich_govalidator.LeftTrim, "", direct_github_com_asaskevich_govalidator_LeftTrim)
	pkg.AddFunction("Map", github_com_asaskevich_govalidator.Map, "", nil)
	pkg.AddFunction("Matches", github_com_asaskevich_govalidator.Matches, "", direct_github_com_asaskevich_govalidator_Matches)
	pkg.AddFunction("MaxStringLength", github_com_asaskevich_govalidator.MaxStringLength, "", direct_github_com_asaskevich_govalidator_MaxStringLength)
	pkg.AddFunction("MinStringLength", github_com_asaskevich_govalidator.MinStringLength, "", direct_github_com_asaskevich_govalidator_MinStringLength)
	pkg.AddFunction("NormalizeEmail", github_com_asaskevich_govalidator.NormalizeEmail, "", direct_github_com_asaskevich_govalidator_NormalizeEmail)
	pkg.AddFunction("PadBoth", github_com_asaskevich_govalidator.PadBoth, "", direct_github_com_asaskevich_govalidator_PadBoth)
	pkg.AddFunction("PadLeft", github_com_asaskevich_govalidator.PadLeft, "", direct_github_com_asaskevich_govalidator_PadLeft)
	pkg.AddFunction("PadRight", github_com_asaskevich_govalidator.PadRight, "", direct_github_com_asaskevich_govalidator_PadRight)
	pkg.AddFunction("Range", github_com_asaskevich_govalidator.Range, "", direct_github_com_asaskevich_govalidator_Range)
	pkg.AddFunction("Reduce", github_com_asaskevich_govalidator.Reduce, "", nil)
	pkg.AddFunction("RemoveTags", github_com_asaskevich_govalidator.RemoveTags, "", direct_github_com_asaskevich_govalidator_RemoveTags)
	pkg.AddFunction("ReplacePattern", github_com_asaskevich_govalidator.ReplacePattern, "", direct_github_com_asaskevich_govalidator_ReplacePattern)
	pkg.AddFunction("Reverse", github_com_asaskevich_govalidator.Reverse, "", direct_github_com_asaskevich_govalidator_Reverse)
	pkg.AddFunction("RightTrim", github_com_asaskevich_govalidator.RightTrim, "", direct_github_com_asaskevich_govalidator_RightTrim)
	pkg.AddFunction("RuneLength", github_com_asaskevich_govalidator.RuneLength, "", direct_github_com_asaskevich_govalidator_RuneLength)
	pkg.AddFunction("SafeFileName", github_com_asaskevich_govalidator.SafeFileName, "", direct_github_com_asaskevich_govalidator_SafeFileName)
	pkg.AddFunction("SetFieldsRequiredByDefault", github_com_asaskevich_govalidator.SetFieldsRequiredByDefault, "", direct_github_com_asaskevich_govalidator_SetFieldsRequiredByDefault)
	pkg.AddFunction("SetNilPtrAllowedByRequired", github_com_asaskevich_govalidator.SetNilPtrAllowedByRequired, "", direct_github_com_asaskevich_govalidator_SetNilPtrAllowedByRequired)
	pkg.AddFunction("Sign", github_com_asaskevich_govalidator.Sign, "", direct_github_com_asaskevich_govalidator_Sign)
	pkg.AddFunction("Some", github_com_asaskevich_govalidator.Some, "", nil)
	pkg.AddFunction("StringLength", github_com_asaskevich_govalidator.StringLength, "", direct_github_com_asaskevich_govalidator_StringLength)
	pkg.AddFunction("StringMatches", github_com_asaskevich_govalidator.StringMatches, "", direct_github_com_asaskevich_govalidator_StringMatches)
	pkg.AddFunction("StripLow", github_com_asaskevich_govalidator.StripLow, "", direct_github_com_asaskevich_govalidator_StripLow)
	pkg.AddFunction("ToBoolean", github_com_asaskevich_govalidator.ToBoolean, "", direct_github_com_asaskevich_govalidator_ToBoolean)
	pkg.AddFunction("ToFloat", github_com_asaskevich_govalidator.ToFloat, "", direct_github_com_asaskevich_govalidator_ToFloat)
	pkg.AddFunction("ToInt", github_com_asaskevich_govalidator.ToInt, "", direct_github_com_asaskevich_govalidator_ToInt)
	pkg.AddFunction("ToJSON", github_com_asaskevich_govalidator.ToJSON, "", direct_github_com_asaskevich_govalidator_ToJSON)
	pkg.AddFunction("ToString", github_com_asaskevich_govalidator.ToString, "", direct_github_com_asaskevich_govalidator_ToString)
	pkg.AddFunction("Trim", github_com_asaskevich_govalidator.Trim, "", direct_github_com_asaskevich_govalidator_Trim)
	pkg.AddFunction("Truncate", github_com_asaskevich_govalidator.Truncate, "", direct_github_com_asaskevich_govalidator_Truncate)
	pkg.AddFunction("TruncatingErrorf", github_com_asaskevich_govalidator.TruncatingErrorf, "", direct_github_com_asaskevich_govalidator_TruncatingErrorf)
	pkg.AddFunction("UnderscoreToCamelCase", github_com_asaskevich_govalidator.UnderscoreToCamelCase, "", direct_github_com_asaskevich_govalidator_UnderscoreToCamelCase)
	pkg.AddFunction("ValidateArray", github_com_asaskevich_govalidator.ValidateArray, "", nil)
	pkg.AddFunction("ValidateMap", github_com_asaskevich_govalidator.ValidateMap, "", direct_github_com_asaskevich_govalidator_ValidateMap)
	pkg.AddFunction("ValidateMapAsync", github_com_asaskevich_govalidator.ValidateMapAsync, "", direct_github_com_asaskevich_govalidator_ValidateMapAsync)
	pkg.AddFunction("ValidateStruct", github_com_asaskevich_govalidator.ValidateStruct, "", direct_github_com_asaskevich_govalidator_ValidateStruct)
	pkg.AddFunction("ValidateStructAsync", github_com_asaskevich_govalidator.ValidateStructAsync, "", direct_github_com_asaskevich_govalidator_ValidateStructAsync)
	pkg.AddFunction("WhiteList", github_com_asaskevich_govalidator.WhiteList, "", direct_github_com_asaskevich_govalidator_WhiteList)

	// Constants
	pkg.AddConstant("ASCII", github_com_asaskevich_govalidator.ASCII, "")
	pkg.AddConstant("Alpha", github_com_asaskevich_govalidator.Alpha, "")
	pkg.AddConstant("Alphanumeric", github_com_asaskevich_govalidator.Alphanumeric, "")
	pkg.AddConstant("Base64", github_com_asaskevich_govalidator.Base64, "")
	pkg.AddConstant("CreditCard", github_com_asaskevich_govalidator.CreditCard, "")
	pkg.AddConstant("DNSName", github_com_asaskevich_govalidator.DNSName, "")
	pkg.AddConstant("DataURI", github_com_asaskevich_govalidator.DataURI, "")
	pkg.AddConstant("E164", github_com_asaskevich_govalidator.E164, "")
	pkg.AddConstant("Email", github_com_asaskevich_govalidator.Email, "")
	pkg.AddConstant("Float", github_com_asaskevich_govalidator.Float, "")
	pkg.AddConstant("FullWidth", github_com_asaskevich_govalidator.FullWidth, "")
	pkg.AddConstant("HalfWidth", github_com_asaskevich_govalidator.HalfWidth, "")
	pkg.AddConstant("Hexadecimal", github_com_asaskevich_govalidator.Hexadecimal, "")
	pkg.AddConstant("Hexcolor", github_com_asaskevich_govalidator.Hexcolor, "")
	pkg.AddConstant("IMEI", github_com_asaskevich_govalidator.IMEI, "")
	pkg.AddConstant("IMSI", github_com_asaskevich_govalidator.IMSI, "")
	pkg.AddConstant("IP", github_com_asaskevich_govalidator.IP, "")
	pkg.AddConstant("ISBN10", github_com_asaskevich_govalidator.ISBN10, "")
	pkg.AddConstant("ISBN13", github_com_asaskevich_govalidator.ISBN13, "")
	pkg.AddConstant("Int", github_com_asaskevich_govalidator.Int, "")
	pkg.AddConstant("Latitude", github_com_asaskevich_govalidator.Latitude, "")
	pkg.AddConstant("Longitude", github_com_asaskevich_govalidator.Longitude, "")
	pkg.AddConstant("MagnetURI", github_com_asaskevich_govalidator.MagnetURI, "")
	pkg.AddConstant("Multibyte", github_com_asaskevich_govalidator.Multibyte, "")
	pkg.AddConstant("Numeric", github_com_asaskevich_govalidator.Numeric, "")
	pkg.AddConstant("PrintableASCII", github_com_asaskevich_govalidator.PrintableASCII, "")
	pkg.AddConstant("RGBcolor", github_com_asaskevich_govalidator.RGBcolor, "")
	pkg.AddConstant("SSN", github_com_asaskevich_govalidator.SSN, "")
	pkg.AddConstant("Semver", github_com_asaskevich_govalidator.Semver, "")
	pkg.AddConstant("URL", github_com_asaskevich_govalidator.URL, "")
	pkg.AddConstant("URLIP", github_com_asaskevich_govalidator.URLIP, "")
	pkg.AddConstant("URLPath", github_com_asaskevich_govalidator.URLPath, "")
	pkg.AddConstant("URLPort", github_com_asaskevich_govalidator.URLPort, "")
	pkg.AddConstant("URLSchema", github_com_asaskevich_govalidator.URLSchema, "")
	pkg.AddConstant("URLSubdomain", github_com_asaskevich_govalidator.URLSubdomain, "")
	pkg.AddConstant("URLUsername", github_com_asaskevich_govalidator.URLUsername, "")
	pkg.AddConstant("UUID", github_com_asaskevich_govalidator.UUID, "")
	pkg.AddConstant("UUID3", github_com_asaskevich_govalidator.UUID3, "")
	pkg.AddConstant("UUID4", github_com_asaskevich_govalidator.UUID4, "")
	pkg.AddConstant("UUID5", github_com_asaskevich_govalidator.UUID5, "")
	pkg.AddConstant("Unix", github_com_asaskevich_govalidator.Unix, "")
	pkg.AddConstant("UnixARPath", github_com_asaskevich_govalidator.UnixARPath, "")
	pkg.AddConstant("UnixPath", github_com_asaskevich_govalidator.UnixPath, "")
	pkg.AddConstant("Unknown", github_com_asaskevich_govalidator.Unknown, "")
	pkg.AddConstant("Win", github_com_asaskevich_govalidator.Win, "")
	pkg.AddConstant("WinARPath", github_com_asaskevich_govalidator.WinARPath, "")
	pkg.AddConstant("WinPath", github_com_asaskevich_govalidator.WinPath, "")

	// Variables
	pkg.AddVariable("CustomTypeTagMap", &github_com_asaskevich_govalidator.CustomTypeTagMap, "")
	pkg.AddVariable("Escape", &github_com_asaskevich_govalidator.Escape, "")
	pkg.AddVariable("ISO3166List", &github_com_asaskevich_govalidator.ISO3166List, "")
	pkg.AddVariable("ISO4217List", &github_com_asaskevich_govalidator.ISO4217List, "")
	pkg.AddVariable("ISO693List", &github_com_asaskevich_govalidator.ISO693List, "")
	pkg.AddVariable("InterfaceParamTagMap", &github_com_asaskevich_govalidator.InterfaceParamTagMap, "")
	pkg.AddVariable("InterfaceParamTagRegexMap", &github_com_asaskevich_govalidator.InterfaceParamTagRegexMap, "")
	pkg.AddVariable("ParamTagMap", &github_com_asaskevich_govalidator.ParamTagMap, "")
	pkg.AddVariable("ParamTagRegexMap", &github_com_asaskevich_govalidator.ParamTagRegexMap, "")
	pkg.AddVariable("TagMap", &github_com_asaskevich_govalidator.TagMap, "")

	// Types
	pkg.AddType("ConditionIterator", reflect.TypeOf((*github_com_asaskevich_govalidator.ConditionIterator)(nil)).Elem(), "")
	pkg.AddType("CustomTypeValidator", reflect.TypeOf((*github_com_asaskevich_govalidator.CustomTypeValidator)(nil)).Elem(), "")
	pkg.AddType("Error", reflect.TypeOf(github_com_asaskevich_govalidator.Error{}), "")
	pkg.AddType("Errors", reflect.TypeOf((*github_com_asaskevich_govalidator.Errors)(nil)).Elem(), "")
	pkg.AddType("ISO3166Entry", reflect.TypeOf(github_com_asaskevich_govalidator.ISO3166Entry{}), "")
	pkg.AddType("ISO693Entry", reflect.TypeOf(github_com_asaskevich_govalidator.ISO693Entry{}), "")
	pkg.AddType("InterfaceParamValidator", reflect.TypeOf((*github_com_asaskevich_govalidator.InterfaceParamValidator)(nil)).Elem(), "")
	pkg.AddType("Iterator", reflect.TypeOf((*github_com_asaskevich_govalidator.Iterator)(nil)).Elem(), "")
	pkg.AddType("ParamValidator", reflect.TypeOf((*github_com_asaskevich_govalidator.ParamValidator)(nil)).Elem(), "")
	pkg.AddType("ReduceIterator", reflect.TypeOf((*github_com_asaskevich_govalidator.ReduceIterator)(nil)).Elem(), "")
	pkg.AddType("ResultIterator", reflect.TypeOf((*github_com_asaskevich_govalidator.ResultIterator)(nil)).Elem(), "")
	pkg.AddType("UnsupportedTypeError", reflect.TypeOf(github_com_asaskevich_govalidator.UnsupportedTypeError{}), "")
	pkg.AddType("Validator", reflect.TypeOf((*github_com_asaskevich_govalidator.Validator)(nil)).Elem(), "")

	// Method DirectCalls
	pkg.AddMethodDirectCall("Error", "Error", direct_method_github_com_asaskevich_govalidator_Error_Error)
	pkg.AddMethodDirectCall("Errors", "Error", direct_method_github_com_asaskevich_govalidator_Errors_Error)
	pkg.AddMethodDirectCall("Errors", "Errors", direct_method_github_com_asaskevich_govalidator_Errors_Errors)
	pkg.AddMethodDirectCall("UnsupportedTypeError", "Error", direct_method_github_com_asaskevich_govalidator_UnsupportedTypeError_Error)

}

func direct_github_com_asaskevich_govalidator_Abs(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.MakeFloat(float64(github_com_asaskevich_govalidator.Abs(a0)))
}

func direct_github_com_asaskevich_govalidator_BlackList(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.BlackList(a0, a1)))
}

func direct_github_com_asaskevich_govalidator_ByteLength(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.ByteLength(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_CamelCaseToUnderscore(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.CamelCaseToUnderscore(a0)))
}

func direct_github_com_asaskevich_govalidator_Contains(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(github_com_asaskevich_govalidator.Contains(a0, a1))
}

func direct_github_com_asaskevich_govalidator_ErrorByField(args []value.Value) value.Value {
	a0 := value.ErrorValue(args[0])
	a1 := args[1].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.ErrorByField(a0, a1)))
}

func direct_github_com_asaskevich_govalidator_ErrorsByField(args []value.Value) value.Value {
	a0 := value.ErrorValue(args[0])
	return value.FromInterface(github_com_asaskevich_govalidator.ErrorsByField(a0))
}

func direct_github_com_asaskevich_govalidator_GetLine(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	r0, r1 := github_com_asaskevich_govalidator.GetLine(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_GetLines(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(github_com_asaskevich_govalidator.GetLines(a0))
}

func direct_github_com_asaskevich_govalidator_HasLowerCase(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.HasLowerCase(a0))
}

func direct_github_com_asaskevich_govalidator_HasUpperCase(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.HasUpperCase(a0))
}

func direct_github_com_asaskevich_govalidator_HasWhitespace(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.HasWhitespace(a0))
}

func direct_github_com_asaskevich_govalidator_HasWhitespaceOnly(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.HasWhitespaceOnly(a0))
}

func direct_github_com_asaskevich_govalidator_InRange(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	a2 := args[2].Interface()
	return value.MakeBool(github_com_asaskevich_govalidator.InRange(a0, a1, a2))
}

func direct_github_com_asaskevich_govalidator_InRangeFloat32(args []value.Value) value.Value {
	a0 := float32(args[0].Float())
	a1 := float32(args[1].Float())
	a2 := float32(args[2].Float())
	return value.MakeBool(github_com_asaskevich_govalidator.InRangeFloat32(a0, a1, a2))
}

func direct_github_com_asaskevich_govalidator_InRangeFloat64(args []value.Value) value.Value {
	a0 := args[0].Float()
	a1 := args[1].Float()
	a2 := args[2].Float()
	return value.MakeBool(github_com_asaskevich_govalidator.InRangeFloat64(a0, a1, a2))
}

func direct_github_com_asaskevich_govalidator_InRangeInt(args []value.Value) value.Value {
	a0 := args[0].Interface()
	a1 := args[1].Interface()
	a2 := args[2].Interface()
	return value.MakeBool(github_com_asaskevich_govalidator.InRangeInt(a0, a1, a2))
}

func direct_github_com_asaskevich_govalidator_IsASCII(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsASCII(a0))
}

func direct_github_com_asaskevich_govalidator_IsAlpha(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsAlpha(a0))
}

func direct_github_com_asaskevich_govalidator_IsAlphanumeric(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsAlphanumeric(a0))
}

func direct_github_com_asaskevich_govalidator_IsBase64(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsBase64(a0))
}

func direct_github_com_asaskevich_govalidator_IsByteLength(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	a2 := int(args[2].Int())
	return value.MakeBool(github_com_asaskevich_govalidator.IsByteLength(a0, a1, a2))
}

func direct_github_com_asaskevich_govalidator_IsCIDR(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsCIDR(a0))
}

func direct_github_com_asaskevich_govalidator_IsCRC32(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsCRC32(a0))
}

func direct_github_com_asaskevich_govalidator_IsCRC32b(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsCRC32b(a0))
}

func direct_github_com_asaskevich_govalidator_IsCreditCard(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsCreditCard(a0))
}

func direct_github_com_asaskevich_govalidator_IsDNSName(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsDNSName(a0))
}

func direct_github_com_asaskevich_govalidator_IsDataURI(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsDataURI(a0))
}

func direct_github_com_asaskevich_govalidator_IsDialString(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsDialString(a0))
}

func direct_github_com_asaskevich_govalidator_IsDivisibleBy(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsDivisibleBy(a0, a1))
}

func direct_github_com_asaskevich_govalidator_IsE164(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsE164(a0))
}

func direct_github_com_asaskevich_govalidator_IsEmail(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsEmail(a0))
}

func direct_github_com_asaskevich_govalidator_IsExistingEmail(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsExistingEmail(a0))
}

func direct_github_com_asaskevich_govalidator_IsFilePath(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := github_com_asaskevich_govalidator.IsFilePath(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBool(r0), value.MakeInt(int64(r1))})
}

func direct_github_com_asaskevich_govalidator_IsFloat(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsFloat(a0))
}

func direct_github_com_asaskevich_govalidator_IsFullWidth(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsFullWidth(a0))
}

func direct_github_com_asaskevich_govalidator_IsHalfWidth(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsHalfWidth(a0))
}

func direct_github_com_asaskevich_govalidator_IsHash(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsHash(a0, a1))
}

func direct_github_com_asaskevich_govalidator_IsHexadecimal(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsHexadecimal(a0))
}

func direct_github_com_asaskevich_govalidator_IsHexcolor(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsHexcolor(a0))
}

func direct_github_com_asaskevich_govalidator_IsHost(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsHost(a0))
}

func direct_github_com_asaskevich_govalidator_IsIMEI(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsIMEI(a0))
}

func direct_github_com_asaskevich_govalidator_IsIMSI(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsIMSI(a0))
}

func direct_github_com_asaskevich_govalidator_IsIP(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsIP(a0))
}

func direct_github_com_asaskevich_govalidator_IsIPv4(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsIPv4(a0))
}

func direct_github_com_asaskevich_govalidator_IsIPv6(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsIPv6(a0))
}

func direct_github_com_asaskevich_govalidator_IsISBN(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	return value.MakeBool(github_com_asaskevich_govalidator.IsISBN(a0, a1))
}

func direct_github_com_asaskevich_govalidator_IsISBN10(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsISBN10(a0))
}

func direct_github_com_asaskevich_govalidator_IsISBN13(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsISBN13(a0))
}

func direct_github_com_asaskevich_govalidator_IsISO3166Alpha2(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsISO3166Alpha2(a0))
}

func direct_github_com_asaskevich_govalidator_IsISO3166Alpha3(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsISO3166Alpha3(a0))
}

func direct_github_com_asaskevich_govalidator_IsISO4217(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsISO4217(a0))
}

func direct_github_com_asaskevich_govalidator_IsISO693Alpha2(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsISO693Alpha2(a0))
}

func direct_github_com_asaskevich_govalidator_IsISO693Alpha3b(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsISO693Alpha3b(a0))
}

func direct_github_com_asaskevich_govalidator_IsIn(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.IsIn(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_IsInRaw(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.IsInRaw(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_IsInt(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsInt(a0))
}

func direct_github_com_asaskevich_govalidator_IsJSON(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsJSON(a0))
}

func direct_github_com_asaskevich_govalidator_IsLatitude(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsLatitude(a0))
}

func direct_github_com_asaskevich_govalidator_IsLongitude(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsLongitude(a0))
}

func direct_github_com_asaskevich_govalidator_IsLowerCase(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsLowerCase(a0))
}

func direct_github_com_asaskevich_govalidator_IsMAC(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsMAC(a0))
}

func direct_github_com_asaskevich_govalidator_IsMD4(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsMD4(a0))
}

func direct_github_com_asaskevich_govalidator_IsMD5(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsMD5(a0))
}

func direct_github_com_asaskevich_govalidator_IsMagnetURI(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsMagnetURI(a0))
}

func direct_github_com_asaskevich_govalidator_IsMongoID(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsMongoID(a0))
}

func direct_github_com_asaskevich_govalidator_IsMultibyte(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsMultibyte(a0))
}

func direct_github_com_asaskevich_govalidator_IsNatural(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.MakeBool(github_com_asaskevich_govalidator.IsNatural(a0))
}

func direct_github_com_asaskevich_govalidator_IsNegative(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.MakeBool(github_com_asaskevich_govalidator.IsNegative(a0))
}

func direct_github_com_asaskevich_govalidator_IsNonNegative(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.MakeBool(github_com_asaskevich_govalidator.IsNonNegative(a0))
}

func direct_github_com_asaskevich_govalidator_IsNonPositive(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.MakeBool(github_com_asaskevich_govalidator.IsNonPositive(a0))
}

func direct_github_com_asaskevich_govalidator_IsNotNull(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsNotNull(a0))
}

func direct_github_com_asaskevich_govalidator_IsNull(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsNull(a0))
}

func direct_github_com_asaskevich_govalidator_IsNumeric(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsNumeric(a0))
}

func direct_github_com_asaskevich_govalidator_IsPort(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsPort(a0))
}

func direct_github_com_asaskevich_govalidator_IsPositive(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.MakeBool(github_com_asaskevich_govalidator.IsPositive(a0))
}

func direct_github_com_asaskevich_govalidator_IsPrintableASCII(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsPrintableASCII(a0))
}

func direct_github_com_asaskevich_govalidator_IsRFC3339(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsRFC3339(a0))
}

func direct_github_com_asaskevich_govalidator_IsRFC3339WithoutZone(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsRFC3339WithoutZone(a0))
}

func direct_github_com_asaskevich_govalidator_IsRGBcolor(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsRGBcolor(a0))
}

func direct_github_com_asaskevich_govalidator_IsRegex(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsRegex(a0))
}

func direct_github_com_asaskevich_govalidator_IsRequestURI(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsRequestURI(a0))
}

func direct_github_com_asaskevich_govalidator_IsRequestURL(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsRequestURL(a0))
}

func direct_github_com_asaskevich_govalidator_IsRipeMD128(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsRipeMD128(a0))
}

func direct_github_com_asaskevich_govalidator_IsRipeMD160(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsRipeMD160(a0))
}

func direct_github_com_asaskevich_govalidator_IsRsaPub(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.IsRsaPub(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_IsRsaPublicKey(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	return value.MakeBool(github_com_asaskevich_govalidator.IsRsaPublicKey(a0, a1))
}

func direct_github_com_asaskevich_govalidator_IsSHA1(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSHA1(a0))
}

func direct_github_com_asaskevich_govalidator_IsSHA256(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSHA256(a0))
}

func direct_github_com_asaskevich_govalidator_IsSHA3224(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSHA3224(a0))
}

func direct_github_com_asaskevich_govalidator_IsSHA3256(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSHA3256(a0))
}

func direct_github_com_asaskevich_govalidator_IsSHA3384(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSHA3384(a0))
}

func direct_github_com_asaskevich_govalidator_IsSHA3512(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSHA3512(a0))
}

func direct_github_com_asaskevich_govalidator_IsSHA384(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSHA384(a0))
}

func direct_github_com_asaskevich_govalidator_IsSHA512(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSHA512(a0))
}

func direct_github_com_asaskevich_govalidator_IsSSN(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSSN(a0))
}

func direct_github_com_asaskevich_govalidator_IsSemver(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsSemver(a0))
}

func direct_github_com_asaskevich_govalidator_IsTiger128(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsTiger128(a0))
}

func direct_github_com_asaskevich_govalidator_IsTiger160(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsTiger160(a0))
}

func direct_github_com_asaskevich_govalidator_IsTiger192(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsTiger192(a0))
}

func direct_github_com_asaskevich_govalidator_IsTime(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsTime(a0, a1))
}

func direct_github_com_asaskevich_govalidator_IsType(args []value.Value) value.Value {
	a0 := args[0].Interface()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.IsType(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_IsULID(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsULID(a0))
}

func direct_github_com_asaskevich_govalidator_IsURL(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsURL(a0))
}

func direct_github_com_asaskevich_govalidator_IsUTFDigit(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUTFDigit(a0))
}

func direct_github_com_asaskevich_govalidator_IsUTFLetter(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUTFLetter(a0))
}

func direct_github_com_asaskevich_govalidator_IsUTFLetterNumeric(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUTFLetterNumeric(a0))
}

func direct_github_com_asaskevich_govalidator_IsUTFNumeric(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUTFNumeric(a0))
}

func direct_github_com_asaskevich_govalidator_IsUUID(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUUID(a0))
}

func direct_github_com_asaskevich_govalidator_IsUUIDv3(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUUIDv3(a0))
}

func direct_github_com_asaskevich_govalidator_IsUUIDv4(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUUIDv4(a0))
}

func direct_github_com_asaskevich_govalidator_IsUUIDv5(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUUIDv5(a0))
}

func direct_github_com_asaskevich_govalidator_IsUnixFilePath(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUnixFilePath(a0))
}

func direct_github_com_asaskevich_govalidator_IsUnixTime(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUnixTime(a0))
}

func direct_github_com_asaskevich_govalidator_IsUpperCase(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsUpperCase(a0))
}

func direct_github_com_asaskevich_govalidator_IsVariableWidth(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsVariableWidth(a0))
}

func direct_github_com_asaskevich_govalidator_IsWhole(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.MakeBool(github_com_asaskevich_govalidator.IsWhole(a0))
}

func direct_github_com_asaskevich_govalidator_IsWinFilePath(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(github_com_asaskevich_govalidator.IsWinFilePath(a0))
}

func direct_github_com_asaskevich_govalidator_LeftTrim(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.LeftTrim(a0, a1)))
}

func direct_github_com_asaskevich_govalidator_Matches(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(github_com_asaskevich_govalidator.Matches(a0, a1))
}

func direct_github_com_asaskevich_govalidator_MaxStringLength(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.MaxStringLength(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_MinStringLength(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.MinStringLength(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_NormalizeEmail(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := github_com_asaskevich_govalidator.NormalizeEmail(a0)
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_PadBoth(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	a2 := int(args[2].Int())
	return value.MakeString(string(github_com_asaskevich_govalidator.PadBoth(a0, a1, a2)))
}

func direct_github_com_asaskevich_govalidator_PadLeft(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	a2 := int(args[2].Int())
	return value.MakeString(string(github_com_asaskevich_govalidator.PadLeft(a0, a1, a2)))
}

func direct_github_com_asaskevich_govalidator_PadRight(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	a2 := int(args[2].Int())
	return value.MakeString(string(github_com_asaskevich_govalidator.PadRight(a0, a1, a2)))
}

func direct_github_com_asaskevich_govalidator_Range(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.Range(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_RemoveTags(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.RemoveTags(a0)))
}

func direct_github_com_asaskevich_govalidator_ReplacePattern(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	a2 := args[2].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.ReplacePattern(a0, a1, a2)))
}

func direct_github_com_asaskevich_govalidator_Reverse(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.Reverse(a0)))
}

func direct_github_com_asaskevich_govalidator_RightTrim(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.RightTrim(a0, a1)))
}

func direct_github_com_asaskevich_govalidator_RuneLength(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.RuneLength(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_SafeFileName(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.SafeFileName(a0)))
}

func direct_github_com_asaskevich_govalidator_SetFieldsRequiredByDefault(args []value.Value) value.Value {
	a0 := args[0].Bool()
	github_com_asaskevich_govalidator.SetFieldsRequiredByDefault(a0)
	return value.MakeNil()
}

func direct_github_com_asaskevich_govalidator_SetNilPtrAllowedByRequired(args []value.Value) value.Value {
	a0 := args[0].Bool()
	github_com_asaskevich_govalidator.SetNilPtrAllowedByRequired(a0)
	return value.MakeNil()
}

func direct_github_com_asaskevich_govalidator_Sign(args []value.Value) value.Value {
	a0 := args[0].Float()
	return value.MakeFloat(float64(github_com_asaskevich_govalidator.Sign(a0)))
}

func direct_github_com_asaskevich_govalidator_StringLength(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.StringLength(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_StringMatches(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]string, 0, len(args)-1)
	for i := 1; i < len(args); i++ {
		if v := args[i].Interface(); v != nil {
			varArgs = append(varArgs, v.(string))
		}
	}
	return value.MakeBool(github_com_asaskevich_govalidator.StringMatches(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_StripLow(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].Bool()
	return value.MakeString(string(github_com_asaskevich_govalidator.StripLow(a0, a1)))
}

func direct_github_com_asaskevich_govalidator_ToBoolean(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := github_com_asaskevich_govalidator.ToBoolean(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBool(r0), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_ToFloat(args []value.Value) value.Value {
	a0 := args[0].Interface()
	r0, r1 := github_com_asaskevich_govalidator.ToFloat(a0)
	return value.MakeValueSlice([]value.Value{value.MakeFloat(float64(r0)), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_ToInt(args []value.Value) value.Value {
	a0 := args[0].Interface()
	r0, r1 := github_com_asaskevich_govalidator.ToInt(a0)
	return value.MakeValueSlice([]value.Value{value.MakeInt64(r0), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_ToJSON(args []value.Value) value.Value {
	a0 := args[0].Interface()
	r0, r1 := github_com_asaskevich_govalidator.ToJSON(a0)
	return value.MakeValueSlice([]value.Value{value.MakeString(string(r0)), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_ToString(args []value.Value) value.Value {
	a0 := args[0].Interface()
	return value.MakeString(string(github_com_asaskevich_govalidator.ToString(a0)))
}

func direct_github_com_asaskevich_govalidator_Trim(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.Trim(a0, a1)))
}

func direct_github_com_asaskevich_govalidator_Truncate(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := int(args[1].Int())
	a2 := args[2].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.Truncate(a0, a1, a2)))
}

func direct_github_com_asaskevich_govalidator_TruncatingErrorf(args []value.Value) value.Value {
	a0 := args[0].String()
	varArgs := make([]interface{}, len(args)-1)
	for i := 1; i < len(args); i++ {
		varArgs[i-1] = args[i].Interface()
	}
	return value.FromInterface(github_com_asaskevich_govalidator.TruncatingErrorf(a0, varArgs...))
}

func direct_github_com_asaskevich_govalidator_UnderscoreToCamelCase(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.UnderscoreToCamelCase(a0)))
}

func direct_github_com_asaskevich_govalidator_ValidateMap(args []value.Value) value.Value {
	a0 := args[0].Interface().(map[string]interface{})
	a1 := args[1].Interface().(map[string]interface{})
	r0, r1 := github_com_asaskevich_govalidator.ValidateMap(a0, a1)
	return value.MakeValueSlice([]value.Value{value.MakeBool(r0), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_ValidateMapAsync(args []value.Value) value.Value {
	a0 := args[0].Interface().(map[string]interface{})
	a1 := args[1].Interface().(map[string]interface{})
	r0, r1 := github_com_asaskevich_govalidator.ValidateMapAsync(a0, a1)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_ValidateStruct(args []value.Value) value.Value {
	a0 := args[0].Interface()
	r0, r1 := github_com_asaskevich_govalidator.ValidateStruct(a0)
	return value.MakeValueSlice([]value.Value{value.MakeBool(r0), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_ValidateStructAsync(args []value.Value) value.Value {
	a0 := args[0].Interface()
	r0, r1 := github_com_asaskevich_govalidator.ValidateStructAsync(a0)
	return value.MakeValueSlice([]value.Value{value.FromInterface(r0), value.FromInterface(r1)})
}

func direct_github_com_asaskevich_govalidator_WhiteList(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeString(string(github_com_asaskevich_govalidator.WhiteList(a0, a1)))
}

func direct_method_github_com_asaskevich_govalidator_Error_Error(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_asaskevich_govalidator.Error)
	return value.MakeString(string(recv.Error()))
}

func direct_method_github_com_asaskevich_govalidator_Errors_Error(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_asaskevich_govalidator.Errors)
	return value.MakeString(string(recv.Error()))
}

func direct_method_github_com_asaskevich_govalidator_Errors_Errors(args []value.Value) value.Value {
	recv := args[0].Interface().(github_com_asaskevich_govalidator.Errors)
	return value.FromInterface(recv.Errors())
}

func direct_method_github_com_asaskevich_govalidator_UnsupportedTypeError_Error(args []value.Value) value.Value {
	recv := args[0].Interface().(*github_com_asaskevich_govalidator.UnsupportedTypeError)
	return value.MakeString(string(recv.Error()))
}
