// Code generated by gig/packages/tool. DO NOT EDIT.
package path_filepath

import (
	path_filepath "path/filepath"
	"reflect"

	"gig/importer"
	"gig/value"
)

func init() {
	pkg := importer.RegisterPackage("path/filepath", "filepath")

	// Functions
	pkg.AddFunction("Abs", path_filepath.Abs, "", direct_Abs)
	pkg.AddFunction("Base", path_filepath.Base, "", direct_Base)
	pkg.AddFunction("Clean", path_filepath.Clean, "", direct_Clean)
	pkg.AddFunction("Dir", path_filepath.Dir, "", direct_Dir)
	pkg.AddFunction("EvalSymlinks", path_filepath.EvalSymlinks, "", direct_EvalSymlinks)
	pkg.AddFunction("Ext", path_filepath.Ext, "", direct_Ext)
	pkg.AddFunction("FromSlash", path_filepath.FromSlash, "", direct_FromSlash)
	pkg.AddFunction("Glob", path_filepath.Glob, "", direct_Glob)
	pkg.AddFunction("HasPrefix", path_filepath.HasPrefix, "", direct_HasPrefix)
	pkg.AddFunction("IsAbs", path_filepath.IsAbs, "", direct_IsAbs)
	pkg.AddFunction("IsLocal", path_filepath.IsLocal, "", direct_IsLocal)
	pkg.AddFunction("Join", path_filepath.Join, "", direct_Join)
	pkg.AddFunction("Localize", path_filepath.Localize, "", direct_Localize)
	pkg.AddFunction("Match", path_filepath.Match, "", direct_Match)
	pkg.AddFunction("Rel", path_filepath.Rel, "", direct_Rel)
	pkg.AddFunction("Split", path_filepath.Split, "", direct_Split)
	pkg.AddFunction("SplitList", path_filepath.SplitList, "", direct_SplitList)
	pkg.AddFunction("ToSlash", path_filepath.ToSlash, "", direct_ToSlash)
	pkg.AddFunction("VolumeName", path_filepath.VolumeName, "", direct_VolumeName)
	pkg.AddFunction("Walk", path_filepath.Walk, "", nil)
	pkg.AddFunction("WalkDir", path_filepath.WalkDir, "", nil)

	// Constants
	pkg.AddConstant("ListSeparator", path_filepath.ListSeparator, "")
	pkg.AddConstant("Separator", path_filepath.Separator, "")

	// Variables
	pkg.AddVariable("ErrBadPattern", &path_filepath.ErrBadPattern, "")
	pkg.AddVariable("SkipAll", &path_filepath.SkipAll, "")
	pkg.AddVariable("SkipDir", &path_filepath.SkipDir, "")

	// Types
	pkg.AddType("WalkFunc", reflect.TypeOf((*path_filepath.WalkFunc)(nil)).Elem(), "")

}

func direct_Abs(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := path_filepath.Abs(a0)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Base(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path_filepath.Base(a0)))
}

func direct_Clean(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path_filepath.Clean(a0)))
}

func direct_Dir(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path_filepath.Dir(a0)))
}

func direct_EvalSymlinks(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := path_filepath.EvalSymlinks(a0)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Ext(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path_filepath.Ext(a0)))
}

func direct_FromSlash(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path_filepath.FromSlash(a0)))
}

func direct_Glob(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := path_filepath.Glob(a0)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_HasPrefix(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	return value.MakeBool(path_filepath.HasPrefix(a0, a1))
}

func direct_IsAbs(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(path_filepath.IsAbs(a0))
}

func direct_IsLocal(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeBool(path_filepath.IsLocal(a0))
}

func direct_Join(args []value.Value) value.Value {
	varArgs := make([]string, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].String()
	}
	return value.MakeString(string(path_filepath.Join(varArgs...)))
}

func direct_Localize(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := path_filepath.Localize(a0)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Match(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	r0, r1 := path_filepath.Match(a0, a1)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Rel(args []value.Value) value.Value {
	a0 := args[0].String()
	a1 := args[1].String()
	r0, r1 := path_filepath.Rel(a0, a1)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_Split(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := path_filepath.Split(a0)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_SplitList(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(path_filepath.SplitList(a0))
}

func direct_ToSlash(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path_filepath.ToSlash(a0)))
}

func direct_VolumeName(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(path_filepath.VolumeName(a0)))
}
