// Package bytecode defines the shared kernel types for the Gig interpreter.
//
// This package contains the bytecode instruction set, compiled program data
// structures, and dependency injection interfaces shared between the compiler
// and VM packages. It serves as the Shared Kernel in the DDD architecture,
// enabling the compiler and VM to be fully decoupled from each other.
//
// # Compilation Process
//
// The compiler translates Go SSA (Static Single Assignment) intermediate representation
// into a custom bytecode format that can be executed by the VM.
//
//  1. SSA Package Input - The compiler receives an SSA package from golang.org/x/tools/go/ssa
//  2. Function Collection - All functions (including nested/anonymous) are collected
//  3. Index Assignment - Each function is assigned a unique index for call instructions
//  4. Per-Function Compilation - Each function is compiled to bytecode:
//     - Symbol table construction for locals, parameters, and free variables
//     - Phi node slot allocation
//     - Basic block compilation in reverse postorder
//     - Jump target patching
//  5. Program Assembly - All compiled functions are combined into a Program
//
// # Bytecode Format
//
// Each instruction consists of:
//   - 1 byte opcode (see OpCode constants)
//   - 0-3 bytes of operands (see OperandWidths)
//
// Most instructions operate on a stack: pop operands, push result.
// Local variables are accessed by index into the frame's local array.
//
// Each OpCode constant below has its own comment describing the instruction's
// stack effect, operands, and current implementation status.
//
// # Example
//
// The Go function:
//
//	func add(a, b int) int {
//	    return a + b
//	}
//
// Compiles to approximately:
//
//	LOCAL 0      ; push local 0 (a)
//	LOCAL 1      ; push local 1 (b)
//	ADD          ; pop a, pop b, push a+b
//	RETURNVAL    ; return top of stack
package bytecode

// OpCode represents a single bytecode instruction.
// Each opcode may have 0-3 bytes of operands following it.
// See OperandWidths for the expected operand size for each opcode.
type OpCode byte

// Sentinel values shared between compiler and VM.
const (
	// SliceEndSentinel is emitted by the compiler as the "high" or "max" operand
	// of a slice expression when the user omits it (e.g., a[1:]). The VM
	// interprets this as "use the container's length."
	SliceEndSentinel = 0xFFFF

	// NoSourceLocal is emitted by the compiler as the source-local operand of
	// OpChangeType when the source value is not a local variable. The VM uses
	// it to skip the source-local update that shares backing arrays.
	NoSourceLocal = 0xFFFF
)

const (
	// ========================================
	// Stack Operations
	// ========================================

	// OpNop does nothing and advances to the next instruction.
	// It is useful as a patch target or placeholder in generated bytecode.
	OpNop OpCode = iota

	// OpPop discards the top operand stack value.
	// Stack: [... value] -> [...]
	OpPop

	// OpDup copies the top operand stack value without consuming it.
	// Stack: [... value] -> [... value value]
	OpDup

	// ========================================
	// Constants and Locals
	// ========================================

	// OpConst pushes a value from Program.Constants.
	// Operands: [const_idx:2]
	// Stack: [...] -> [... constant]
	OpConst

	// OpNil pushes Gig's nil value.
	// Stack: [...] -> [... nil]
	OpNil

	// OpTrue pushes the boolean literal true.
	// Stack: [...] -> [... true]
	OpTrue

	// OpFalse pushes the boolean literal false.
	// Stack: [...] -> [... false]
	OpFalse

	// OpLocal pushes frame.locals[local_idx].
	// Operands: [local_idx:2]
	// Stack: [...] -> [... local]
	OpLocal

	// OpSetLocal pops a value into frame.locals[local_idx].
	// Operands: [local_idx:2]
	// Stack: [... value] -> [...]
	OpSetLocal

	// OpGlobal pushes an addressable global slot reference.
	// Non-shared mode pushes *value.Value; shared mode pushes *GlobalRef so
	// OpDeref/OpSetDeref can read/write through the right synchronization path.
	// Operands: [global_idx:2]
	// Stack: [...] -> [... global_ref]
	OpGlobal

	// OpSetGlobal pops a value into the global slot.
	// Operands: [global_idx:2]
	// Stack: [... value] -> [...]
	OpSetGlobal

	// OpFree pushes a closure-captured variable from frame.freeVars.
	// Operands: [free_idx:1]
	// Stack: [...] -> [... captured_value]
	OpFree

	// OpSetFree pops a value into a closure-captured variable slot.
	// Operands: [free_idx:1]
	// Stack: [... value] -> [...]
	OpSetFree

	// ========================================
	// Arithmetic Operations
	// ========================================

	// OpAdd pops b and a, then pushes a+b.
	// Supports numeric addition and string concatenation.
	// Stack: [... a b] -> [... result]
	OpAdd

	// OpSub pops b and a, then pushes a-b.
	// Stack: [... a b] -> [... result]
	OpSub

	// OpMul pops b and a, then pushes a*b.
	// Stack: [... a b] -> [... result]
	OpMul

	// OpDiv pops b and a, then pushes a/b.
	// Stack: [... a b] -> [... result]
	OpDiv

	// OpMod pops b and a, then pushes a%b.
	// Stack: [... a b] -> [... result]
	OpMod

	// OpNeg pops a and pushes -a.
	// Stack: [... a] -> [... result]
	OpNeg

	// OpReal pops a complex value and pushes its real component.
	// Stack: [... complex] -> [... real]
	OpReal

	// OpImag pops a complex value and pushes its imaginary component.
	// Stack: [... complex] -> [... imag]
	OpImag

	// OpComplex pops imaginary and real components and pushes complex(real, imag).
	// Stack: [... real imag] -> [... complex]
	OpComplex

	// ========================================
	// Bitwise Operations
	// ========================================

	// OpAnd pops b and a, then pushes the integer bitwise result a&b.
	// Stack: [... a b] -> [... result]
	OpAnd

	// OpOr pops b and a, then pushes the integer bitwise result a|b.
	// Stack: [... a b] -> [... result]
	OpOr

	// OpXor pops b and a, then pushes the integer bitwise result a^b.
	// Stack: [... a b] -> [... result]
	OpXor

	// OpAndNot pops b and a, then pushes the integer bit-clear result a&^b.
	// Stack: [... a b] -> [... result]
	OpAndNot

	// OpLsh pops shift and value, then pushes value<<shift.
	// Stack: [... value shift] -> [... result]
	OpLsh

	// OpRsh pops shift and value, then pushes value>>shift.
	// Stack: [... value shift] -> [... result]
	OpRsh

	// ========================================
	// Comparison Operations
	// ========================================

	// OpEqual pops b and a, then pushes whether a == b.
	// Stack: [... a b] -> [... bool]
	OpEqual

	// OpNotEqual pops b and a, then pushes whether a != b.
	// Stack: [... a b] -> [... bool]
	OpNotEqual

	// OpLess pops b and a, then pushes whether a < b.
	// Stack: [... a b] -> [... bool]
	OpLess

	// OpLessEq pops b and a, then pushes whether a <= b.
	// Stack: [... a b] -> [... bool]
	OpLessEq

	// OpGreater pops b and a, then pushes whether a > b.
	// Stack: [... a b] -> [... bool]
	OpGreater

	// OpGreaterEq pops b and a, then pushes whether a >= b.
	// Stack: [... a b] -> [... bool]
	OpGreaterEq

	// ========================================
	// Logical Operations
	// ========================================

	// OpNot pops a bool and pushes its negation.
	// Stack: [... bool] -> [... !bool]
	OpNot

	// ========================================
	// Control Flow
	// ========================================

	// OpJump sets the current frame instruction pointer to offset.
	// Operands: [offset:2]
	// Stack: unchanged
	OpJump

	// OpJumpTrue pops a bool and jumps to offset when it is true.
	// Operands: [offset:2]
	// Stack: [... cond] -> [...]
	OpJumpTrue

	// OpJumpFalse pops a bool and jumps to offset when it is false.
	// Operands: [offset:2]
	// Stack: [... cond] -> [...]
	OpJumpFalse

	// OpCall enters a compiled Gig function frame.
	// Operands: [func_idx:2] [num_args:1]
	// Stack: [... args...] -> [... result]
	OpCall

	// OpReturn exits the current frame with nil as the function result.
	// Stack: caller receives [... nil]
	OpReturn

	// OpReturnVal pops one value and returns it to the caller frame.
	// Stack: [... result] -> caller receives [... result]
	OpReturnVal

	// ========================================
	// Container Operations
	// ========================================

	// OpMakeSlice creates a typed slice, using a native []int64 fast path for
	// int slices and reflection for other element types.
	// Stack: [... typeIdx len cap] -> [... slice]
	OpMakeSlice

	// OpMakeMap creates a typed map. The size value is currently accepted as a
	// stack operand but ignored by the reflective implementation.
	// Stack: [... typeIdx size] -> [... map]
	OpMakeMap

	// OpMakeChan creates a typed channel with the requested buffer size.
	// Stack: [... typeIdx size] -> [... chan]
	OpMakeChan

	// OpMakeInterface wraps a value in a Go interface while preserving
	// concrete type information needed by typed nil and interpreted named types.
	// Operands: [iface_type_idx:2] [concrete_type_idx:2]
	// Stack: [... value] -> [... interface_value]
	OpMakeInterface

	// OpMakeArray is a reserved array-construction opcode.
	// The current compiler does not emit it; arrays are normally created by SSA
	// allocation paths instead. Add a VM handler before emitting this opcode.
	// Operands: [type_idx:2]
	OpMakeArray

	// OpMakeStruct is a reserved struct-construction opcode.
	// The current compiler does not emit it; structs are normally represented by
	// reflect-backed allocation paths instead. Add a VM handler before emitting it.
	// Operands: [type_idx:2]
	OpMakeStruct

	// ========================================
	// Index Operations
	// ========================================

	// OpIndex reads container[key] for slices, arrays, maps, strings, bytes, and
	// reflect-backed containers.
	// Stack: [... container key] -> [... value]
	OpIndex

	// OpIndexOk reads container[key] and returns Go's comma-ok result.
	// It is primarily for maps, with limited reflect slice/array support.
	// Stack: [... container key] -> [... (value, ok) tuple]
	OpIndexOk

	// OpSetIndex assigns container[key] = value for slices, arrays, maps, and
	// reflect-backed containers.
	// Stack: [... container key value] -> [...]
	OpSetIndex

	// OpSlice evaluates container[low:high] or container[low:high:max].
	// SliceEndSentinel marks an omitted high or max bound.
	// Stack: [... container low high max] -> [... sliced]
	OpSlice

	// _ (placeholder: was OpSliceLen, removed as dead code - use OpLen instead)

	// ========================================
	// Map Operations
	// ========================================

	// OpMapIter is a reserved legacy map-iterator opcode.
	// The current compiler uses OpRange and OpRangeNext for all range loops.
	OpMapIter

	// OpMapIterNext is a reserved legacy map-iterator advance opcode.
	// The current compiler uses OpRangeNext instead.
	OpMapIterNext

	// ========================================
	// Struct Operations
	// ========================================

	// OpField reads a struct field by field index.
	// Operands: [field_idx:2]
	// Stack: [... struct] -> [... field_value]
	OpField

	// OpSetField assigns a struct field by field index.
	// Operands: [field_idx:2]
	// Stack: [... struct value] -> [...]
	OpSetField

	// ========================================
	// Pointer Operations
	// ========================================

	// OpAddr pushes an addressable reference to frame.locals[local_idx].
	// Taking a local address marks the frame as not poolable.
	// Operands: [local_idx:2]
	// Stack: [...] -> [... local_ref]
	OpAddr

	// OpFieldAddr pushes an addressable reference to a struct field.
	// Operands: [field_idx:2]
	// Stack: [... struct_ptr] -> [... field_ptr]
	OpFieldAddr

	// OpIndexAddr pushes an addressable reference to a slice or array element.
	// Native []int64 containers return an int pointer fast path; other containers
	// use reflection when possible.
	// Stack: [... container index] -> [... element_ptr]
	OpIndexAddr

	// OpDeref loads through an addressable reference produced by OpGlobal,
	// OpAddr, OpFieldAddr, OpIndexAddr, or reflect-backed pointer values.
	// Stack: [... ref] -> [... value]
	OpDeref

	// OpSetDeref stores value through an addressable reference.
	// Stack: [... ref value] -> [...]
	OpSetDeref

	// ========================================
	// Interface Operations
	// ========================================

	// OpAssert performs a type assertion against Program.Types[type_idx].
	// Operands: [type_idx:2]
	// Stack: [... interface] -> [... (value, ok) tuple]
	OpAssert

	// OpConvert converts the top stack value to Program.Types[type_idx].
	// It handles primitive conversions, string/byte/rune conversions, and
	// reflect-backed named external types.
	// Operands: [type_idx:2]
	// Stack: [... value] -> [... converted_value]
	OpConvert

	// OpChangeType performs a named-type conversion (ChangeType in SSA).
	// Unlike OpConvert, this also updates the source local variable so that
	// slice aliasing works correctly (e.g., sort.IntSlice(s) shares s's backing array).
	// Operands: [type_idx:2] [src_local:2]
	// Stack: [... value] -> [... converted_value]
	OpChangeType

	// ========================================
	// Function Operations
	// ========================================

	// OpClosure creates an interpreted closure and captures num_free stack values.
	// Operands: [func_idx:2] [num_free:1]
	// Stack: [... free_0 ... free_n] -> [... closure]
	OpClosure

	// OpMethod is a reserved method-value lookup opcode.
	// The current compiler routes method calls through external call metadata
	// instead; add a VM handler before emitting this opcode.
	// Operands: [method_idx:2]
	OpMethod

	// OpMethodCall is a reserved direct method-call opcode.
	// Current method dispatch uses OpCallExternal or compiled-function dispatch
	// from callExternal; add a VM handler before emitting this opcode.
	// Operands: [method_idx:2] [num_args:1]
	OpMethodCall

	// ========================================
	// Concurrency Operations
	// ========================================

	// OpGoCall starts a tracked goroutine running a compiled Gig function.
	// Operands: [func_idx:2, num_args:1]
	// Stack: [... args] -> [...]
	OpGoCall

	// OpGoCallIndirect starts a tracked goroutine running a closure value.
	// Operands: [num_args:1]
	// Stack: [... closure args...] -> [...]
	OpGoCallIndirect

	// OpSend sends a value on a channel, respecting VM context cancellation and
	// translating "send on closed channel" into a guest panic.
	// Stack: [... ch value] -> [...]
	OpSend

	// OpRecv receives one value from a channel.
	// Stack: [... ch] -> [... value]
	OpRecv

	// OpRecvOk receives one value from a channel and returns Go's comma-ok flag.
	// Stack: [... ch] -> [... (value, ok) tuple]
	OpRecvOk

	// OpTrySend is a reserved non-blocking send opcode.
	// Current non-blocking channel behavior is represented through OpSelect.
	OpTrySend

	// OpTryRecv is a reserved non-blocking receive opcode.
	// Current non-blocking channel behavior is represented through OpSelect.
	OpTryRecv

	// OpClose closes a channel.
	// Stack: [... ch] -> [...]
	OpClose

	// OpSelect performs a Go select using SelectMeta from Program.Constants.
	// Operands: [meta_idx:2]
	// Stack: [... case_operands] -> [... (chosen, recv_ok, recv_values...) tuple]
	OpSelect

	// ========================================
	// Defer/Recover
	// ========================================

	// OpDefer records a deferred call to a compiled Gig function.
	// Operands: [func_idx:2]
	// Stack: [... args...] -> [...]
	OpDefer

	// OpDeferIndirect records a deferred call to a closure or function value.
	// Operands: [num_args:2]
	// Stack: [... closure args...] -> [...]
	OpDeferIndirect

	// OpDeferExternal records a deferred call to an external Go function or method.
	// Operands: [func_idx:2, num_args:1]
	// Stack: [... args...] -> [...]
	OpDeferExternal

	// OpRunDefers executes all pending deferred calls synchronously.
	// This is used for named return values where defers may modify return values
	// before the function actually returns.
	OpRunDefers

	// OpRecover implements Go recover() using the VM's current panic state.
	// Stack: [...] -> [... recovered_value_or_nil]
	OpRecover

	// ========================================
	// Range Operations
	// ========================================

	// OpRange creates a VM iterator for range loops.
	// Stack: [... collection] -> [... iterator]
	OpRange

	// OpRangeNext advances a VM iterator and returns the SSA Next tuple.
	// Stack: [... iterator] -> [... (ok, key, value) tuple]
	OpRangeNext

	// ========================================
	// Builtin Functions
	// ========================================

	// OpLen implements len for strings, bytes, slices, arrays, maps, channels,
	// interfaces, and reflect-backed values.
	// Stack: [... value] -> [... len]
	OpLen

	// OpCap implements cap for slices, arrays, channels, bytes, and reflect-backed values.
	// Stack: [... value] -> [... cap]
	OpCap

	// OpAppend implements append for native int slices, byte slices, reflect slices,
	// nil slices, and spread slices packed by SSA.
	// Stack: [... slice elem] -> [... new_slice]
	OpAppend

	// OpCopy implements copy for bytes, native int slices, and reflect slices.
	// Stack: [... dst src] -> [... n]
	OpCopy

	// OpDelete implements delete(map, key); nil maps are a no-op.
	// Stack: [... map key] -> [...]
	OpDelete

	// OpPanic stores the popped value as the active guest panic.
	// Stack: [... message] -> [...]
	OpPanic

	// OpPrint pops count values and writes them with fmt.Print.
	// Operands: [count:1]
	// Stack: [... values...] -> [...]
	OpPrint

	// OpPrintln pops count values and writes them with fmt.Println.
	// Operands: [count:1]
	// Stack: [... values...] -> [...]
	OpPrintln

	// OpNew allocates a pointer to Program.Types[type_idx].
	// Function types allocate a *value.Value slot so closures can be stored.
	// Operands: [type_idx:2]
	// Stack: [...] -> [... ptr]
	OpNew

	// OpMake is a reserved generic make opcode.
	// The current compiler emits OpMakeSlice, OpMakeMap, or OpMakeChan instead;
	// add a VM case before emitting this opcode.
	// Operands: [type_idx:2] [size_idx:2]
	OpMake

	// ========================================
	// External Function Calls
	// ========================================

	// OpCallExternal calls a registered native Go function or method.
	// Direct wrappers may avoid reflection; fallback paths convert through reflect.
	// Operands: [func_idx:2] [num_args:1]
	// Stack: [... args...] -> [... result_or_tuple_or_nil]
	OpCallExternal

	// OpCallIndirect calls a function value, interpreted closure, or reflect-backed
	// Go function value.
	// Operands: [num_args:1]
	// Stack: [... func_value args...] -> [... result]
	OpCallIndirect

	// ========================================
	// Tuple/Multi-value Operations
	// ========================================

	// OpPack pops count values and stores them in order inside []value.Value.
	// Used to move multi-return values through one stack slot.
	// Operands: [count:2]
	// Stack: [... values...] -> [... []value.Value]
	OpPack

	// OpUnpack pops a tuple/slice value and pushes each element back to the stack.
	// Stack: [... tuple] -> [... elements...]
	OpUnpack

	// OpHalt aborts execution with a "halt" error for debugging.
	OpHalt

	// ========================================
	// Superinstructions (fused ops for hot loops)
	// ========================================

	// OpAddLocalLocal pushes locals[A]+locals[B] without separate OpLocal dispatches.
	// Operands: [local_a:2] [local_b:2]
	// Stack: [...] -> [... result]
	OpAddLocalLocal

	// OpSubLocalLocal pushes locals[A]-locals[B] without separate OpLocal dispatches.
	// Operands: [local_a:2] [local_b:2]
	// Stack: [...] -> [... result]
	OpSubLocalLocal

	// OpMulLocalLocal pushes locals[A]*locals[B] without separate OpLocal dispatches.
	// Operands: [local_a:2] [local_b:2]
	// Stack: [...] -> [... result]
	OpMulLocalLocal

	// OpAddLocalConst pushes locals[A]+constants[B].
	// Operands: [local_a:2] [const_b:2]
	// Stack: [...] -> [... result]
	OpAddLocalConst

	// OpSubLocalConst pushes locals[A]-constants[B].
	// Operands: [local_a:2] [const_b:2]
	// Stack: [...] -> [... result]
	OpSubLocalConst

	// OpLessLocalLocalJumpTrue jumps when locals[A] < locals[B].
	// This fuses OpLocal, OpLocal, OpLess, and OpJumpTrue without using the stack.
	// Operands: [local_a:2] [local_b:2] [offset:2]
	OpLessLocalLocalJumpTrue

	// OpLessLocalConstJumpTrue jumps when locals[A] < constants[B].
	// Operands: [local_a:2] [const_b:2] [offset:2]
	OpLessLocalConstJumpTrue

	// OpLessEqLocalConstJumpTrue jumps when locals[A] <= constants[B].
	// Operands: [local_a:2] [const_b:2] [offset:2]
	OpLessEqLocalConstJumpTrue

	// OpGreaterLocalLocalJumpTrue jumps when locals[A] > locals[B].
	// Operands: [local_a:2] [local_b:2] [offset:2]
	OpGreaterLocalLocalJumpTrue

	// OpLessLocalLocalJumpFalse jumps when locals[A] >= locals[B].
	// Operands: [local_a:2] [local_b:2] [offset:2]
	OpLessLocalLocalJumpFalse

	// OpLessLocalConstJumpFalse jumps when locals[A] >= constants[B].
	// Operands: [local_a:2] [const_b:2] [offset:2]
	OpLessLocalConstJumpFalse

	// OpLessEqLocalConstJumpFalse jumps when locals[A] > constants[B].
	// Operands: [local_a:2] [const_b:2] [offset:2]
	OpLessEqLocalConstJumpFalse

	// OpAddSetLocal pops b and a, then stores a+b into locals[A].
	// Operands: [local_a:2]
	// Stack: [... a b] -> [...]
	OpAddSetLocal

	// OpSubSetLocal pops b and a, then stores a-b into locals[A].
	// Operands: [local_a:2]
	// Stack: [... a b] -> [...]
	OpSubSetLocal

	// OpLocalLocalAddSetLocal stores locals[A]+locals[B] into locals[C].
	// Operands: [local_a:2] [local_b:2] [local_c:2]
	OpLocalLocalAddSetLocal

	// OpLocalConstAddSetLocal stores locals[A]+constants[B] into locals[C].
	// Operands: [local_a:2] [const_b:2] [local_c:2]
	OpLocalConstAddSetLocal

	// OpLocalConstSubSetLocal stores locals[A]-constants[B] into locals[C].
	// Operands: [local_a:2] [const_b:2] [local_c:2]
	OpLocalConstSubSetLocal

	// ========================================
	// Integer-specialized superinstructions
	// These operate on intLocals []int64 directly and mirror writes back to
	// frame.locals when later generic opcodes may observe the value.
	// Emitted by the peephole optimizer when compile-time type analysis confirms int types.
	// ========================================

	// OpIntLocalConstAddSetLocal stores intLocals[A]+intConsts[B] into local C.
	// Operands: [local_a:2] [const_b:2] [local_c:2]
	OpIntLocalConstAddSetLocal

	// OpIntLocalConstSubSetLocal stores intLocals[A]-intConsts[B] into local C.
	// Operands: [local_a:2] [const_b:2] [local_c:2]
	OpIntLocalConstSubSetLocal

	// OpIntLocalLocalAddSetLocal stores intLocals[A]+intLocals[B] into local C.
	// Operands: [local_a:2] [local_b:2] [local_c:2]
	OpIntLocalLocalAddSetLocal

	// OpIntLessLocalConstJumpFalse jumps when intLocals[A] >= intConsts[B].
	// Operands: [local_a:2] [const_b:2] [offset:2]
	OpIntLessLocalConstJumpFalse

	// OpIntLessEqLocalConstJumpTrue jumps when intLocals[A] <= intConsts[B].
	// Operands: [local_a:2] [const_b:2] [offset:2]
	OpIntLessEqLocalConstJumpTrue

	// OpIntLessEqLocalConstJumpFalse jumps when intLocals[A] > intConsts[B].
	// Operands: [local_a:2] [const_b:2] [offset:2]
	OpIntLessEqLocalConstJumpFalse

	// OpIntLessLocalLocalJumpFalse jumps when intLocals[A] >= intLocals[B].
	// Operands: [local_a:2] [local_b:2] [offset:2]
	OpIntLessLocalLocalJumpFalse

	// OpIntGreaterLocalLocalJumpTrue jumps when intLocals[A] > intLocals[B].
	// Operands: [local_a:2] [local_b:2] [offset:2]
	OpIntGreaterLocalLocalJumpTrue

	// OpIntSetLocal pops an int value into intLocals[idx] and frame.locals[idx].
	// Operands: [local_idx:2]
	// Stack: [... value] -> [...]
	OpIntSetLocal

	// OpIntLocal pushes intLocals[idx] as a Gig int value.
	// Operands: [local_idx:2]
	// Stack: [...] -> [... int]
	OpIntLocal

	// OpIntLessLocalConstJumpTrue jumps when intLocals[A] < intConsts[B].
	// Operands: [local_a:2] [const_b:2] [offset:2]
	OpIntLessLocalConstJumpTrue

	// OpIntLessLocalLocalJumpTrue jumps when intLocals[A] < intLocals[B].
	// Operands: [local_a:2] [local_b:2] [offset:2]
	OpIntLessLocalLocalJumpTrue

	// OpIntMoveLocal copies local src to local dst in both intLocals and frame.locals.
	// It eliminates the phi-move pattern OpIntLocal(src), OpIntSetLocal(dst).
	// Operands: [src:2] [dst:2]
	OpIntMoveLocal

	// OpIntSliceGet stores locals[slice_local][intLocals[index_local]] into dest.
	// It fuses slice index address, dereference, and int local store for []int64.
	// Operands: [slice_local:2] [index_local:2] [dest_local:2]
	OpIntSliceGet

	// OpIntSliceSet assigns locals[slice_local][intLocals[index_local]] = intLocals[val_local].
	// It fuses slice index address and dereference store for []int64.
	// Operands: [slice_local:2] [index_local:2] [val_local:2]
	OpIntSliceSet

	// OpIntSliceSetConst assigns locals[slice_local][intLocals[index_local]] = intConsts[const_val].
	// It is the constant-value version of OpIntSliceSet.
	// Operands: [slice_local:2] [index_local:2] [const_val:2]
	OpIntSliceSetConst

	// OpLocalLocalSubSetLocal stores locals[A]-locals[B] into locals[C].
	// This late-added general superinstruction keeps its numeric position for
	// bytecode compatibility with the instruction table.
	// Operands: [local_a:2] [local_b:2] [local_c:2]
	OpLocalLocalSubSetLocal

	// OpLocalLocalMulSetLocal stores locals[A]*locals[B] into locals[C].
	// This late-added general superinstruction keeps its numeric position for
	// bytecode compatibility with the instruction table.
	// Operands: [local_a:2] [local_b:2] [local_c:2]
	OpLocalLocalMulSetLocal

	// OpLocalConstMulSetLocal stores locals[A]*constants[B] into locals[C].
	// This late-added general superinstruction keeps its numeric position for
	// bytecode compatibility with the instruction table.
	// Operands: [local_a:2] [const_b:2] [local_c:2]
	OpLocalConstMulSetLocal

	// OpIntLocalLocalSubSetLocal stores intLocals[A]-intLocals[B] into local C.
	// Operands: [local_a:2] [local_b:2] [local_c:2]
	OpIntLocalLocalSubSetLocal

	// OpIntLocalLocalMulSetLocal stores intLocals[A]*intLocals[B] into local C.
	// Operands: [local_a:2] [local_b:2] [local_c:2]
	OpIntLocalLocalMulSetLocal

	// OpIntLocalConstMulSetLocal stores intLocals[A]*intConsts[B] into local C.
	// Operands: [local_a:2] [const_b:2] [local_c:2]
	OpIntLocalConstMulSetLocal
)

// operandWidthTable is a lookup table for opcode operand widths.
// Using a fixed-size array gives O(1) access with no hash overhead, unlike a map.
// Index is the opcode byte value; value is the total operand byte width.
var operandWidthTable = buildOperandWidthTable()

func buildOperandWidthTable() [256]int {
	var t [256]int

	t[OpConst] = 2
	t[OpLocal] = 2
	t[OpSetLocal] = 2
	t[OpGlobal] = 2
	t[OpSetGlobal] = 2
	t[OpFree] = 1
	t[OpSetFree] = 1
	t[OpJump] = 2
	t[OpJumpTrue] = 2
	t[OpJumpFalse] = 2
	t[OpCall] = 3 // func_idx(2) + num_args(1)
	t[OpMakeArray] = 2
	t[OpMakeStruct] = 2
	t[OpMakeInterface] = 4
	t[OpField] = 2
	t[OpSetField] = 2
	t[OpAddr] = 2
	t[OpFieldAddr] = 2
	t[OpAssert] = 2
	t[OpConvert] = 2
	t[OpChangeType] = 4
	t[OpClosure] = 3 // func_idx(2) + num_free(1)
	t[OpMethod] = 2
	t[OpMethodCall] = 3 // method_idx(2) + num_args(1)
	t[OpDefer] = 2
	t[OpDeferIndirect] = 2  // num_args(2)
	t[OpDeferExternal] = 3  // func_idx(2) + num_args(1)
	t[OpCallExternal] = 3   // func_idx(2) + num_args(1)
	t[OpCallIndirect] = 1   // num_args(1)
	t[OpGoCall] = 3         // func_idx(2) + num_args(1)
	t[OpGoCallIndirect] = 1 // num_args(1)
	t[OpSelect] = 2         // meta_idx(2)
	t[OpPack] = 2           // count(2)
	t[OpNew] = 2
	t[OpMake] = 4    // type_idx(2) + size_idx(2)
	t[OpPrint] = 1   // count(1)
	t[OpPrintln] = 1 // count(1)

	// Superinstruction operand widths
	t[OpAddLocalLocal] = 4             // local_a(2) + local_b(2)
	t[OpSubLocalLocal] = 4             // local_a(2) + local_b(2)
	t[OpMulLocalLocal] = 4             // local_a(2) + local_b(2)
	t[OpAddLocalConst] = 4             // local_a(2) + const_b(2)
	t[OpSubLocalConst] = 4             // local_a(2) + const_b(2)
	t[OpLessLocalLocalJumpTrue] = 6    // local_a(2) + local_b(2) + offset(2)
	t[OpLessLocalConstJumpTrue] = 6    // local_a(2) + const_b(2) + offset(2)
	t[OpLessEqLocalConstJumpTrue] = 6  // local_a(2) + const_b(2) + offset(2)
	t[OpGreaterLocalLocalJumpTrue] = 6 // local_a(2) + local_b(2) + offset(2)
	t[OpLessLocalLocalJumpFalse] = 6   // local_a(2) + local_b(2) + offset(2)
	t[OpLessLocalConstJumpFalse] = 6   // local_a(2) + const_b(2) + offset(2)
	t[OpLessEqLocalConstJumpFalse] = 6 // local_a(2) + const_b(2) + offset(2)
	t[OpAddSetLocal] = 2               // local_a(2)
	t[OpSubSetLocal] = 2               // local_a(2)
	t[OpLocalLocalAddSetLocal] = 6     // local_a(2) + local_b(2) + local_c(2)
	t[OpLocalConstAddSetLocal] = 6     // local_a(2) + const_b(2) + local_c(2)
	t[OpLocalConstSubSetLocal] = 6     // local_a(2) + const_b(2) + local_c(2)

	// Integer-specialized operand widths
	t[OpIntLocalConstAddSetLocal] = 6     // local_a(2) + const_b(2) + local_c(2)
	t[OpIntLocalConstSubSetLocal] = 6     // local_a(2) + const_b(2) + local_c(2)
	t[OpIntLocalLocalAddSetLocal] = 6     // local_a(2) + local_b(2) + local_c(2)
	t[OpIntLessLocalConstJumpFalse] = 6   // local_a(2) + const_b(2) + offset(2)
	t[OpIntLessEqLocalConstJumpTrue] = 6  // local_a(2) + const_b(2) + offset(2)
	t[OpIntLessEqLocalConstJumpFalse] = 6 // local_a(2) + const_b(2) + offset(2)
	t[OpIntLessLocalLocalJumpFalse] = 6   // local_a(2) + local_b(2) + offset(2)
	t[OpIntGreaterLocalLocalJumpTrue] = 6 // local_a(2) + local_b(2) + offset(2)
	t[OpIntSetLocal] = 2                  // local_idx(2)
	t[OpIntLocal] = 2                     // local_idx(2)
	t[OpIntLessLocalConstJumpTrue] = 6    // local_a(2) + const_b(2) + offset(2)
	t[OpIntLessLocalLocalJumpTrue] = 6    // local_a(2) + local_b(2) + offset(2)
	t[OpIntMoveLocal] = 4                 // src(2) + dst(2)
	t[OpIntSliceGet] = 6                  // slice_local(2) + index_local(2) + dest_local(2)
	t[OpIntSliceSet] = 6                  // slice_local(2) + index_local(2) + val_local(2)
	t[OpIntSliceSetConst] = 6             // slice_local(2) + index_local(2) + const_val(2)

	// New superinstruction operand widths
	t[OpLocalLocalSubSetLocal] = 6    // local_a(2) + local_b(2) + local_c(2)
	t[OpLocalLocalMulSetLocal] = 6    // local_a(2) + local_b(2) + local_c(2)
	t[OpLocalConstMulSetLocal] = 6    // local_a(2) + const_b(2) + local_c(2)
	t[OpIntLocalLocalSubSetLocal] = 6 // local_a(2) + local_b(2) + local_c(2)
	t[OpIntLocalLocalMulSetLocal] = 6 // local_a(2) + local_b(2) + local_c(2)
	t[OpIntLocalConstMulSetLocal] = 6 // local_a(2) + const_b(2) + local_c(2)

	return t
}

// unknownOpName is the string returned for unrecognized opcodes.
const unknownOpName = "UNKNOWN"

// opNameTable maps OpCode values to their string representations.
// Built at init time for O(1) lookup performance.
var opNameTable [256]string

func init() { //nolint:gochecknoinits,decorder // table init placed after var declarations for readability
	// Initialize all entries to "UNKNOWN"
	for i := range opNameTable {
		opNameTable[i] = unknownOpName
	}

	// Populate known opcodes
	opNameTable[OpAdd] = "ADD"
	opNameTable[OpAddLocalConst] = "ADDLOCALCONST"
	opNameTable[OpAddLocalLocal] = "ADDLOCALLOCAL"
	opNameTable[OpAddSetLocal] = "ADDSETLOCAL"
	opNameTable[OpAddr] = "ADDR"
	opNameTable[OpAnd] = "AND"
	opNameTable[OpAndNot] = "ANDNOT"
	opNameTable[OpAppend] = "APPEND"
	opNameTable[OpAssert] = "ASSERT"
	opNameTable[OpCall] = "CALL"
	opNameTable[OpCallExternal] = "CALLEXTERNAL"
	opNameTable[OpCallIndirect] = "CALLINDIRECT"
	opNameTable[OpCap] = "CAP"
	opNameTable[OpChangeType] = "CHANGETYPE"
	opNameTable[OpClose] = "CLOSE"
	opNameTable[OpClosure] = "CLOSURE"
	opNameTable[OpComplex] = "COMPLEX"
	opNameTable[OpConst] = "CONST"
	opNameTable[OpConvert] = "CONVERT"
	opNameTable[OpCopy] = "COPY"
	opNameTable[OpDefer] = "DEFER"
	opNameTable[OpDeferExternal] = "DEFEREXTERNAL"
	opNameTable[OpDeferIndirect] = "DEFERINDIRECT"
	opNameTable[OpDelete] = "DELETE"
	opNameTable[OpDeref] = "DEREF"
	opNameTable[OpDiv] = "DIV"
	opNameTable[OpDup] = "DUP"
	opNameTable[OpEqual] = "EQUAL"
	opNameTable[OpFalse] = "FALSE"
	opNameTable[OpField] = "FIELD"
	opNameTable[OpFieldAddr] = "FIELDADDR"
	opNameTable[OpFree] = "FREE"
	opNameTable[OpGlobal] = "GLOBAL"
	opNameTable[OpGoCall] = "GOCALL"
	opNameTable[OpGoCallIndirect] = "GOCALLINDIRECT"
	opNameTable[OpGreater] = "GREATER"
	opNameTable[OpGreaterEq] = "GREATEREQ"
	opNameTable[OpGreaterLocalLocalJumpTrue] = "GREATERLOCALLOCALJUMPTRUE"
	opNameTable[OpHalt] = "HALT"
	opNameTable[OpImag] = "IMAG"
	opNameTable[OpIndex] = "INDEX"
	opNameTable[OpIndexAddr] = "INDEXADDR"
	opNameTable[OpIndexOk] = "INDEXOK"
	opNameTable[OpIntGreaterLocalLocalJumpTrue] = "INTGREATERLOCALLOCALJUMPTRUE"
	opNameTable[OpIntLessEqLocalConstJumpFalse] = "INTLESSEQLOCALCONSTJUMPFALSE"
	opNameTable[OpIntLessEqLocalConstJumpTrue] = "INTLESSEQLOCALCONSTJUMPTRUE"
	opNameTable[OpIntLessLocalConstJumpFalse] = "INTLESSLOCALCONSTJUMPFALSE"
	opNameTable[OpIntLessLocalConstJumpTrue] = "INTLESSLOCALCONSTJUMPTRUE"
	opNameTable[OpIntLessLocalLocalJumpFalse] = "INTLESSLOCALLOCALJUMPFALSE"
	opNameTable[OpIntLessLocalLocalJumpTrue] = "INTLESSLOCALLOCALJUMPTRUE"
	opNameTable[OpIntLocal] = "INTLOCAL"
	opNameTable[OpIntLocalConstAddSetLocal] = "INTLOCALCONSTADDSETLOCAL"
	opNameTable[OpIntLocalConstMulSetLocal] = "INTLOCALCONSTMULSETLOCAL"
	opNameTable[OpIntLocalConstSubSetLocal] = "INTLOCALCONSTSUBSETLOCAL"
	opNameTable[OpIntLocalLocalAddSetLocal] = "INTLOCALLOCALADDSETLOCAL"
	opNameTable[OpIntLocalLocalMulSetLocal] = "INTLOCALLOCALMULSETLOCAL"
	opNameTable[OpIntLocalLocalSubSetLocal] = "INTLOCALLOCALSUBSETLOCAL"
	opNameTable[OpIntMoveLocal] = "INTMOVELOCAL"
	opNameTable[OpIntSetLocal] = "INTSETLOCAL"
	opNameTable[OpIntSliceGet] = "INTSLICEGET"
	opNameTable[OpIntSliceSet] = "INTSLICESET"
	opNameTable[OpIntSliceSetConst] = "INTSLICESETCONST"
	opNameTable[OpJump] = "JUMP"
	opNameTable[OpJumpFalse] = "JUMPFALSE"
	opNameTable[OpJumpTrue] = "JUMPTRUE"
	opNameTable[OpLen] = "LEN"
	opNameTable[OpLess] = "LESS"
	opNameTable[OpLessEq] = "LESSEQ"
	opNameTable[OpLessEqLocalConstJumpFalse] = "LESSEQLOCALCONSTJUMPFALSE"
	opNameTable[OpLessEqLocalConstJumpTrue] = "LESSEQLOCALCONSTJUMPTRUE"
	opNameTable[OpLessLocalConstJumpFalse] = "LESSLOCALCONSTJUMPFALSE"
	opNameTable[OpLessLocalConstJumpTrue] = "LESSLOCALCONSTJUMPTRUE"
	opNameTable[OpLessLocalLocalJumpFalse] = "LESSLOCALLOCALJUMPFALSE"
	opNameTable[OpLessLocalLocalJumpTrue] = "LESSLOCALLOCALJUMPTRUE"
	opNameTable[OpLocal] = "LOCAL"
	opNameTable[OpLocalConstAddSetLocal] = "LOCALCONSTADDSETLOCAL"
	opNameTable[OpLocalConstMulSetLocal] = "LOCALCONSTMULSETLOCAL"
	opNameTable[OpLocalConstSubSetLocal] = "LOCALCONSTSUBSETLOCAL"
	opNameTable[OpLocalLocalAddSetLocal] = "LOCALLOCALADDSETLOCAL"
	opNameTable[OpLocalLocalMulSetLocal] = "LOCALLOCALMULSETLOCAL"
	opNameTable[OpLocalLocalSubSetLocal] = "LOCALLOCALSUBSETLOCAL"
	opNameTable[OpLsh] = "LSH"
	opNameTable[OpMake] = "MAKE"
	opNameTable[OpMakeArray] = "MAKEARRAY"
	opNameTable[OpMakeChan] = "MAKECHAN"
	opNameTable[OpMakeInterface] = "MAKEINTERFACE"
	opNameTable[OpMakeMap] = "MAKEMAP"
	opNameTable[OpMakeSlice] = "MAKESLICE"
	opNameTable[OpMakeStruct] = "MAKESTRUCT"
	opNameTable[OpMapIter] = "MAPITER"
	opNameTable[OpMapIterNext] = "MAPITERNEXT"
	opNameTable[OpMethod] = "METHOD"
	opNameTable[OpMethodCall] = "METHODCALL"
	opNameTable[OpMod] = "MOD"
	opNameTable[OpMul] = "MUL"
	opNameTable[OpMulLocalLocal] = "MULLOCALLOCAL"
	opNameTable[OpNeg] = "NEG"
	opNameTable[OpNew] = "NEW"
	opNameTable[OpNil] = "NIL"
	opNameTable[OpNop] = "NOP"
	opNameTable[OpNot] = "NOT"
	opNameTable[OpNotEqual] = "NOTEQUAL"
	opNameTable[OpOr] = "OR"
	opNameTable[OpPack] = "PACK"
	opNameTable[OpPanic] = "PANIC"
	opNameTable[OpPop] = "POP"
	opNameTable[OpPrint] = "PRINT"
	opNameTable[OpPrintln] = "PRINTLN"
	opNameTable[OpRange] = "RANGE"
	opNameTable[OpRangeNext] = "RANGENEXT"
	opNameTable[OpReal] = "REAL"
	opNameTable[OpRecover] = "RECOVER"
	opNameTable[OpRecv] = "RECV"
	opNameTable[OpRecvOk] = "RECVOK"
	opNameTable[OpReturn] = "RETURN"
	opNameTable[OpReturnVal] = "RETURNVAL"
	opNameTable[OpRsh] = "RSH"
	opNameTable[OpRunDefers] = "RUNDEFERS"
	opNameTable[OpSelect] = "SELECT"
	opNameTable[OpSend] = "SEND"
	opNameTable[OpSetDeref] = "SETDEREF"
	opNameTable[OpSetField] = "SETFIELD"
	opNameTable[OpSetFree] = "SETFREE"
	opNameTable[OpSetGlobal] = "SETGLOBAL"
	opNameTable[OpSetIndex] = "SETINDEX"
	opNameTable[OpSetLocal] = "SETLOCAL"
	opNameTable[OpSlice] = "SLICE"
	opNameTable[OpSub] = "SUB"
	opNameTable[OpSubLocalConst] = "SUBLOCALCONST"
	opNameTable[OpSubLocalLocal] = "SUBLOCALLOCAL"
	opNameTable[OpSubSetLocal] = "SUBSETLOCAL"
	opNameTable[OpTrue] = "TRUE"
	opNameTable[OpTryRecv] = "TRYRECV"
	opNameTable[OpTrySend] = "TRYSEND"
	opNameTable[OpUnpack] = "UNPACK"
	opNameTable[OpXor] = "XOR"
}

// String returns the name of the opcode as a human-readable string.
func (op OpCode) String() string {
	if int(op) < len(opNameTable) {
		return opNameTable[op]
	}
	return unknownOpName
}

// OperandWidth returns the operand byte width for an opcode using O(1) array lookup.
func OperandWidth(op OpCode) int {
	return operandWidthTable[op]
}
