// Code generated by gig/packages/tool. DO NOT EDIT.
package text_template

import (
	"reflect"
	text_template "text/template"

	"gig/importer"
	"gig/value"
)

func init() {
	pkg := importer.RegisterPackage("text/template", "template")

	// Functions
	pkg.AddFunction("HTMLEscape", text_template.HTMLEscape, "", nil)
	pkg.AddFunction("HTMLEscapeString", text_template.HTMLEscapeString, "", direct_HTMLEscapeString)
	pkg.AddFunction("HTMLEscaper", text_template.HTMLEscaper, "", direct_HTMLEscaper)
	pkg.AddFunction("IsTrue", text_template.IsTrue, "", direct_IsTrue)
	pkg.AddFunction("JSEscape", text_template.JSEscape, "", nil)
	pkg.AddFunction("JSEscapeString", text_template.JSEscapeString, "", direct_JSEscapeString)
	pkg.AddFunction("JSEscaper", text_template.JSEscaper, "", direct_JSEscaper)
	pkg.AddFunction("Must", text_template.Must, "", nil)
	pkg.AddFunction("New", text_template.New, "", direct_New)
	pkg.AddFunction("ParseFS", text_template.ParseFS, "", nil)
	pkg.AddFunction("ParseFiles", text_template.ParseFiles, "", direct_ParseFiles)
	pkg.AddFunction("ParseGlob", text_template.ParseGlob, "", direct_ParseGlob)
	pkg.AddFunction("URLQueryEscaper", text_template.URLQueryEscaper, "", direct_URLQueryEscaper)

	// Types
	pkg.AddType("ExecError", reflect.TypeOf(text_template.ExecError{}), "")
	pkg.AddType("FuncMap", reflect.TypeOf((*text_template.FuncMap)(nil)).Elem(), "")
	pkg.AddType("Template", reflect.TypeOf(text_template.Template{}), "")

}

func direct_HTMLEscapeString(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(text_template.HTMLEscapeString(a0)))
}

func direct_HTMLEscaper(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	return value.MakeString(string(text_template.HTMLEscaper(varArgs...)))
}

func direct_IsTrue(args []value.Value) value.Value {
	a0 := args[0].Interface()
	r0, r1 := text_template.IsTrue(a0)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_JSEscapeString(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.MakeString(string(text_template.JSEscapeString(a0)))
}

func direct_JSEscaper(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	return value.MakeString(string(text_template.JSEscaper(varArgs...)))
}

func direct_New(args []value.Value) value.Value {
	a0 := args[0].String()
	return value.FromInterface(text_template.New(a0))
}

func direct_ParseFiles(args []value.Value) value.Value {
	varArgs := make([]string, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].String()
	}
	r0, r1 := text_template.ParseFiles(varArgs...)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_ParseGlob(args []value.Value) value.Value {
	a0 := args[0].String()
	r0, r1 := text_template.ParseGlob(a0)
	return value.FromInterface([]interface{}{r0, r1})
}

func direct_URLQueryEscaper(args []value.Value) value.Value {
	varArgs := make([]interface{}, len(args)-0)
	for i := 0; i < len(args); i++ {
		varArgs[i-0] = args[i].Interface()
	}
	return value.MakeString(string(text_template.URLQueryEscaper(varArgs...)))
}
