// Package main - Memory Leak Log Analyzer
//
// Analyzes the memory log generated by TestStress_MemoryLeak
//
// Usage:
//
//	go run cmd/analyze_memory_log.go stress_memory_leak.log
//	go run cmd/analyze_memory_log.go stress_memory_leak.log --plot
package main

import (
	"bufio"
	"encoding/csv"
	"flag"
	"fmt"
	"math"
	"os"
	"strconv"
	"time"
)

type MemorySample struct {
	Timestamp   time.Time
	HeapAlloc   float64
	HeapSys     float64
	HeapInUse   float64
	HeapIdle    float64
	StackInUse  float64
	NumGC       int
	Goroutines  int
	TotalOps    int64
	OngoingOps  int
	Errors      int
}

func main() {
	plotFlag := flag.Bool("plot", false, "Generate ASCII plot")
	flag.Parse()

	if flag.NArg() < 1 {
		fmt.Println("Usage: go run analyze_memory_log.go <logfile> [--plot]")
		os.Exit(1)
	}

	filename := flag.Arg(0)
	file, err := os.Open(filename)
	if err != nil {
		fmt.Printf("Error opening file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	// Parse CSV
	reader := csv.NewReader(bufio.NewReader(file))
	reader.FieldsPerRecord = 11

	records, err := reader.ReadAll()
	if err != nil {
		fmt.Printf("Error reading CSV: %v\n", err)
		os.Exit(1)
	}

	if len(records) < 2 {
		fmt.Println("Not enough data points")
		os.Exit(1)
	}

	// Skip header, parse samples
	var samples []MemorySample
	for i, record := range records[1:] {
		sample, err := parseRecord(record)
		if err != nil {
			fmt.Printf("Error parsing record %d: %v\n", i+2, err)
			continue
		}
		samples = append(samples, sample)
	}

	if len(samples) == 0 {
		fmt.Println("No valid samples found")
		os.Exit(1)
	}

	// Analyze
	analyzeSamples(samples, *plotFlag)
}

func parseRecord(record []string) (MemorySample, error) {
	var sample MemorySample
	var err error

	t, err := time.Parse(time.RFC3339, record[0])
	if err != nil {
		return sample, fmt.Errorf("invalid timestamp: %v", err)
	}
	sample.Timestamp = t

	sample.HeapAlloc, err = strconv.ParseFloat(record[1], 64)
	if err != nil {
		return sample, fmt.Errorf("invalid HeapAlloc: %v", err)
	}

	sample.HeapSys, err = strconv.ParseFloat(record[2], 64)
	if err != nil {
		return sample, fmt.Errorf("invalid HeapSys: %v", err)
	}

	sample.HeapInUse, err = strconv.ParseFloat(record[3], 64)
	if err != nil {
		return sample, fmt.Errorf("invalid HeapInUse: %v", err)
	}

	sample.HeapIdle, err = strconv.ParseFloat(record[4], 64)
	if err != nil {
		return sample, fmt.Errorf("invalid HeapIdle: %v", err)
	}

	sample.StackInUse, err = strconv.ParseFloat(record[5], 64)
	if err != nil {
		return sample, fmt.Errorf("invalid StackInUse: %v", err)
	}

	numGC, err := strconv.Atoi(record[6])
	if err != nil {
		return sample, fmt.Errorf("invalid NumGC: %v", err)
	}
	sample.NumGC = numGC

	goroutines, err := strconv.Atoi(record[7])
	if err != nil {
		return sample, fmt.Errorf("invalid Goroutines: %v", err)
	}
	sample.Goroutines = goroutines

	totalOps, err := strconv.ParseInt(record[8], 10, 64)
	if err != nil {
		return sample, fmt.Errorf("invalid TotalOps: %v", err)
	}
	sample.TotalOps = totalOps

	ongoingOps, err := strconv.Atoi(record[9])
	if err != nil {
		return sample, fmt.Errorf("invalid OngoingOps: %v", err)
	}
	sample.OngoingOps = ongoingOps

	errors, err := strconv.Atoi(record[10])
	if err != nil {
		return sample, fmt.Errorf("invalid Errors: %v", err)
	}
	sample.Errors = errors

	return sample, nil
}

func analyzeSamples(samples []MemorySample, plot bool) {
	first := samples[0]
	last := samples[len(samples)-1]
	duration := last.Timestamp.Sub(first.Timestamp)

	// Calculate statistics
	var minHeap, maxHeap, sumHeap float64
	var minGoroutines, maxGoroutines int
	minHeap = math.MaxFloat64
	maxHeap = 0
	minGoroutines = math.MaxInt32
	maxGoroutines = 0

	for _, s := range samples {
		if s.HeapAlloc < minHeap {
			minHeap = s.HeapAlloc
		}
		if s.HeapAlloc > maxHeap {
			maxHeap = s.HeapAlloc
		}
		sumHeap += s.HeapAlloc

		if s.Goroutines < minGoroutines {
			minGoroutines = s.Goroutines
		}
		if s.Goroutines > maxGoroutines {
			maxGoroutines = s.Goroutines
		}
	}

	avgHeap := sumHeap / float64(len(samples))
	heapGrowth := last.HeapAlloc - first.HeapAlloc
	goroutineGrowth := last.Goroutines - first.Goroutines

	// Calculate throughput
	ops := last.TotalOps - first.TotalOps
	opsPerSec := float64(ops) / duration.Seconds()

	// Print report
	fmt.Println("══════════════════════════════════════════════════════════════")
	fmt.Println("MEMORY LEAK ANALYSIS REPORT")
	fmt.Println("══════════════════════════════════════════════════════════════")
	fmt.Printf("  Duration:           %v\n", duration.Round(time.Second))
	fmt.Printf("  Samples Collected:  %d\n", len(samples))
	fmt.Printf("  Total Operations:   %d\n", ops)
	fmt.Printf("  Ops/Second:         %.0f\n", opsPerSec)
	fmt.Printf("  Total Errors:       %d\n", last.Errors)
	fmt.Println("────────────────────────────────────────────────────────────────")
	fmt.Printf("  Initial HeapAlloc:  %.2f MB\n", first.HeapAlloc)
	fmt.Printf("  Final HeapAlloc:    %.2f MB\n", last.HeapAlloc)
	fmt.Printf("  Heap Growth:        %.2f MB\n", heapGrowth)
	fmt.Printf("  Min HeapAlloc:      %.2f MB\n", minHeap)
	fmt.Printf("  Max HeapAlloc:      %.2f MB\n", maxHeap)
	fmt.Printf("  Avg HeapAlloc:      %.2f MB\n", avgHeap)
	fmt.Println("────────────────────────────────────────────────────────────────")
	fmt.Printf("  Initial Goroutines: %d\n", first.Goroutines)
	fmt.Printf("  Final Goroutines:   %d\n", last.Goroutines)
	fmt.Printf("  Goroutine Growth:   %d\n", goroutineGrowth)
	fmt.Printf("  Min Goroutines:     %d\n", minGoroutines)
	fmt.Printf("  Max Goroutines:     %d\n", maxGoroutines)
	fmt.Println("────────────────────────────────────────────────────────────────")
	fmt.Printf("  Initial NumGC:      %d\n", first.NumGC)
	fmt.Printf("  Final NumGC:        %d\n", last.NumGC)
	fmt.Printf("  GC Cycles:          %d\n", last.NumGC-first.NumGC)
	fmt.Println("══════════════════════════════════════════════════════════════")

	// Verdict
	fmt.Println()
	fmt.Println("VERDICT:")
	if heapGrowth > 50 {
		fmt.Printf("  🚨 CRITICAL: Heap grew %.2f MB (>50 MB) - MEMORY LEAK DETECTED!\n", heapGrowth)
	} else if heapGrowth > 20 {
		fmt.Printf("  ⚠️  WARNING: Heap grew %.2f MB (>20 MB) - potential leak\n", heapGrowth)
	} else if heapGrowth > 10 {
		fmt.Printf("  ⚠️  NOTICE: Heap grew %.2f MB (>10 MB) - monitor closely\n", heapGrowth)
	} else {
		fmt.Printf("  ✅ PASS: Heap growth %.2f MB is within normal range\n", heapGrowth)
	}

	if goroutineGrowth > 10 {
		fmt.Printf("  🚨 CRITICAL: %d goroutines leaked!\n", goroutineGrowth)
	} else if goroutineGrowth > 5 {
		fmt.Printf("  ⚠️  WARNING: %d goroutines leaked\n", goroutineGrowth)
	} else {
		fmt.Printf("  ✅ PASS: No goroutine leak (%d growth)\n", goroutineGrowth)
	}

	// ASCII Plot
	if plot {
		fmt.Println()
		fmt.Println("══════════════════════════════════════════════════════════════")
		fmt.Println("HEAP ALLOC OVER TIME (MB)")
		fmt.Println("══════════════════════════════════════════════════════════════")
		plotLine(samples, func(s MemorySample) float64 { return s.HeapAlloc }, 60)
		fmt.Println()

		fmt.Println("══════════════════════════════════════════════════════════════")
		fmt.Println("GOROUTINES OVER TIME")
		fmt.Println("══════════════════════════════════════════════════════════════")
		plotLine(samples, func(s MemorySample) float64 { return float64(s.Goroutines) }, 20)
	}
}

func plotLine(samples []MemorySample, getValue func(MemorySample) float64, width int) {
	if len(samples) == 0 {
		return
	}

	// Find min/max
	min := math.MaxFloat64
	max := 0.0
	for _, s := range samples {
		v := getValue(s)
		if v < min {
			min = v
		}
		if v > max {
			max = v
		}
	}

	// Scale factor
	range_ := max - min
	if range_ == 0 {
		range_ = 1
	}

	// Sample data points (downsample if too many)
	step := 1
	if len(samples) > width {
		step = len(samples) / width
	}

	// Plot
	var lastBar int = -1
	for i := 0; i < len(samples); i += step {
		v := getValue(samples[i])
		bar := int((v - min) / range_ * float64(width-1))
		
		// Avoid duplicate bars
		if bar == lastBar && i > 0 && i < len(samples)-step {
			continue
		}
		lastBar = bar

		// Draw bar
		fmt.Printf("%s |", samples[i].Timestamp.Format("15:04:05"))
		for j := 0; j < width; j++ {
			if j <= bar {
				fmt.Print("█")
			} else {
				fmt.Print(" ")
			}
		}
		fmt.Printf(" %.2f\n", v)
	}
}
