// Code generated by gig/packages/tool. DO NOT EDIT.
package container_ring

import (
	container_ring "container/ring"
	"reflect"

	"gig/importer"
	"gig/value"
)

func init() {
	pkg := importer.RegisterPackage("container/ring", "ring")

	// Functions
	pkg.AddFunction("New", container_ring.New, "", direct_New)

	// Types
	pkg.AddType("Ring", reflect.TypeOf(container_ring.Ring{}), "")

}

func direct_New(args []value.Value) value.Value {
	a0 := int(args[0].Int())
	return value.FromInterface(container_ring.New(a0))
}
