// Package packages contains standard library and third-party package registrations.
// All imports are side-effect only — they trigger init() functions that register packages.
package packages

import (
	_ "gig/packages/bytes"
	_ "gig/packages/container_heap"
	_ "gig/packages/container_list"
	_ "gig/packages/container_ring"
	_ "gig/packages/context"
	_ "gig/packages/crypto_hmac"
	_ "gig/packages/crypto_md5"
	_ "gig/packages/crypto_sha256"
	_ "gig/packages/encoding_base64"
	_ "gig/packages/encoding_csv"
	_ "gig/packages/encoding_hex"
	_ "gig/packages/encoding_json"
	_ "gig/packages/encoding_xml"
	_ "gig/packages/errors"
	_ "gig/packages/fmt"
	_ "gig/packages/html"
	_ "gig/packages/html_template"
	_ "gig/packages/io"
	_ "gig/packages/log"
	_ "gig/packages/math"
	_ "gig/packages/math_rand"
	_ "gig/packages/net_http"
	_ "gig/packages/net_url"
	_ "gig/packages/os"
	_ "gig/packages/path"
	_ "gig/packages/path_filepath"
	_ "gig/packages/regexp"
	_ "gig/packages/sort"
	_ "gig/packages/strconv"
	_ "gig/packages/strings"
	_ "gig/packages/sync"
	_ "gig/packages/sync_atomic"
	_ "gig/packages/text_template"
	_ "gig/packages/time"
	_ "gig/packages/unicode"
	_ "gig/packages/unicode_utf16"
	_ "gig/packages/unicode_utf8"
)
